//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Base test: base_test
// *** Each agent's active/passive mode is toggled HERE ***, via
// uvm_resource_db, before the env (and therefore its agents) is
// created. Edit UVM_ACTIVE/UVM_PASSIVE below to change a given
// agent's mode -- no env or agent code needs to change.
class base_test extends uvm_test;

  `uvm_component_utils(base_test)

  lpddr5c_env env;
 lpddr5c_axi_agent_base_seq base_seq;
 lpddr5c_axi_agent_base_read_seq read_seq;
 lpddr5c_apb_reg_ctrl0_write_seq w_seq;

  function new(string name = "base_test", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);

    // --- Agent active/passive configuration ------------------------
    uvm_resource_db#(uvm_active_passive_enum)::set({"*.", "axi_agent"}, "is_active", UVM_ACTIVE, this);  // "axi_agent" (AXI): flip to UVM_PASSIVE to toggle
    uvm_resource_db#(uvm_active_passive_enum)::set({"*.", "apb_agent"}, "is_active", UVM_ACTIVE, this);  // "apb_agent" (APB): flip to UVM_PASSIVE to toggle
    uvm_resource_db#(uvm_active_passive_enum)::set({"*.", "dfi_agent"}, "is_active", UVM_ACTIVE, this);  // "dfi_agent" (DFI): flip to UVM_PASSIVE to toggle
    // -----------------------------------------------------------------

    env = lpddr5c_env::type_id::create("env", this);
    //base_seq = lpddr5c_axi_agent_base_seq::type_id::create("base_seq",this);
    w_seq = lpddr5c_apb_reg_ctrl0_write_seq::type_id::create("w_seq",this);
  endfunction

 /* function void end_of_elaboration_phase(uvm_phase phase);
    super.end_of_elaboration_phase(phase);
    uvm_test_top.print_topology();
  endfunction*/
task run_phase(uvm_phase phase);

 lpddr5c_axi_agent_base_seq seq;

  phase.raise_objection(this);
  fork
  w_seq.start(env.apb_agent.sequencer);
join
base_seq = lpddr5c_axi_agent_base_seq::type_id::create("base_seq",this);
  base_seq.start(env.axi_agent.sequencer);
  
  read_seq = lpddr5c_axi_agent_base_read_seq::type_id::create("read_seq"); 
  `uvm_info("TEST", "Starting AXI READ sequence", UVM_MEDIUM) 
  read_seq.start(env.axi_agent.sequencer); 
  `uvm_info("TEST", "AXI READ sequence completed", UVM_MEDIUM)

  phase.drop_objection(this);

endtask
endclass : base_test

/*class axi_write_test extends base_test;

  `uvm_component_utils(axi_write_test)


  function new(string name = "axi_write_test",
               uvm_component parent = null);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);

    //env = lpddr_env::type_id::create("env", this);
  endfunction

  virtual task run_phase(uvm_phase phase);

    axi_write_sequence seq;

    phase.raise_objection(this);

    `uvm_info("TEST",
              "Starting AXI Write Test",
              UVM_LOW)

    // Wait for reset / initialization
    #100ns;

    seq = axi_write_sequence::type_id::create("seq");

    seq.start(env.axi_agent.sequencer);

    // Allow transaction to complete
    #500ns;

    `uvm_info("TEST",
              "AXI Write Test Completed",
              UVM_LOW)

    phase.drop_objection(this);

  endtask

endclass*/


