/* bitmanip_shadd.c
 *
 * BP-DV-041: Zba sh1add/sh2add/sh3add and .uw forms on both harts.
 * Currently FAILS: the hardware uses rs2[5:0] as the shift amount instead
 * of 1/2/3 (bp_be_pipe_int.sv shamt selects rs2 when irs2_r_v) - Jira.
 * GENERATED by scripts/gen_bitmanip_test.py - do not edit by hand; expected
 * values come from that script's reference model of each instruction.
 *
 * 12 checks over 6 instructions: register, unary and
 * immediate forms, with shift amounts whose upper bits must be ignored,
 * zero inputs for clz/ctz/cpop, 32-bit W forms (sign-extended results) and
 * .uw forms (zero-extended inputs).
 *
 * An unimplemented instruction raises an illegal-instruction trap; the
 * handler counts it and skips the instruction, so the run never hangs.
 *
 * tohost (dual_core.h): (hart1 << 32) | hart0; per hart 0 = pass, else the
 * 1-based number of the first failing check (see the CHECK list), or
 * 0x8000 | trap count if any instruction trapped without a failing check.
 * Built with -march=rv64ima_zba_zbb_zbs (Makefile, by program name).
 */

#include <stdint.h>
#include "dual_core.h"

#define BM_R(op, a, b) ({ uint64_t _r; __asm__ volatile (op " %0, %1, %2" \
    : "=r"(_r) : "r"((uint64_t)(a)), "r"((uint64_t)(b))); _r; })
#define BM_U(op, a) ({ uint64_t _r; __asm__ volatile (op " %0, %1" \
    : "=r"(_r) : "r"((uint64_t)(a))); _r; })
#define BM_I(op, a, imm) ({ uint64_t _r; __asm__ volatile (op " %0, %1, " #imm \
    : "=r"(_r) : "r"((uint64_t)(a))); _r; })

/* Illegal-instruction safety net: count, skip. Record at HART_DRAM. */
#define REC_BASE 0x8000A000UL
__asm__ (
  ".text\n"
  ".align 2\n"
  ".global bm_m_trap\n"
  "bm_m_trap:\n"
  "  csrrw t6, mscratch, t6\n"
  "  sd t0, 8(t6)\n"
  "  ld t0, 0(t6)\n"
  "  addi t0, t0, 1\n"
  "  sd t0, 0(t6)\n"
  "  csrr t0, mepc\n"
  "  addi t0, t0, 4\n"
  "  csrw mepc, t0\n"
  "  ld t0, 8(t6)\n"
  "  csrrw t6, mscratch, t6\n"
  "  mret\n"
);
extern char bm_m_trap[];

#define CHECK(n, got, exp) do { if (rc == 0 && (got) != (exp)) rc = (n); } while (0)

static uint64_t run_bitmanip(void)
{
  volatile uint64_t *rec = (volatile uint64_t *)HART_DRAM(REC_BASE);
  uint64_t rc = 0;

  rec[0] = 0;
  __asm__ volatile ("csrw mtvec, %0" :: "r"(bm_m_trap));
  __asm__ volatile ("csrw mscratch, %0" :: "r"(rec));

  CHECK(  1, BM_R("sh1add", 0x80000000F0F0A5C3ULL, 0x0F0F0F0F0F0F0F0FULL), 0x0F0F0F10F0F05A95ULL);
  CHECK(  2, BM_R("sh1add", 0x7FFFFFFF00000001ULL, 0x80000000F0F0A5C3ULL), 0x7FFFFFFEF0F0A5C5ULL);
  CHECK(  3, BM_R("sh2add", 0x80000000F0F0A5C3ULL, 0x0F0F0F0F0F0F0F0FULL), 0x0F0F0F12D2D1A61BULL);
  CHECK(  4, BM_R("sh2add", 0x7FFFFFFF00000001ULL, 0x80000000F0F0A5C3ULL), 0x7FFFFFFCF0F0A5C7ULL);
  CHECK(  5, BM_R("sh3add", 0x80000000F0F0A5C3ULL, 0x0F0F0F0F0F0F0F0FULL), 0x0F0F0F1696943D27ULL);
  CHECK(  6, BM_R("sh3add", 0x7FFFFFFF00000001ULL, 0x80000000F0F0A5C3ULL), 0x7FFFFFF8F0F0A5CBULL);
  CHECK(  7, BM_R("sh1add.uw", 0x80000000F0F0A5C3ULL, 0x0F0F0F0F0F0F0F0FULL), 0x0F0F0F10F0F05A95ULL);
  CHECK(  8, BM_R("sh1add.uw", 0x7FFFFFFF00000001ULL, 0x80000000F0F0A5C3ULL), 0x80000000F0F0A5C5ULL);
  CHECK(  9, BM_R("sh2add.uw", 0x80000000F0F0A5C3ULL, 0x0F0F0F0F0F0F0F0FULL), 0x0F0F0F12D2D1A61BULL);
  CHECK( 10, BM_R("sh2add.uw", 0x7FFFFFFF00000001ULL, 0x80000000F0F0A5C3ULL), 0x80000000F0F0A5C7ULL);
  CHECK( 11, BM_R("sh3add.uw", 0x80000000F0F0A5C3ULL, 0x0F0F0F0F0F0F0F0FULL), 0x0F0F0F1696943D27ULL);
  CHECK( 12, BM_R("sh3add.uw", 0x7FFFFFFF00000001ULL, 0x80000000F0F0A5C3ULL), 0x80000000F0F0A5CBULL);

  if (rc == 0 && rec[0] != 0)
    rc = 0x8000 | rec[0];
  return rc;
}

static void start_main(void);

__attribute__((naked, section(".text.start"), used))
void _start(void)
{
  __asm__ volatile (
    DUAL_CORE_STACK_INIT
    "jal ra, start_main\n"
    "1: j 1b\n"
  );
}

static void start_main(void)
{
  tohost_exit(run_bitmanip());
}
