//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-09 04:51
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(19 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[PASS]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Reset agent: reset_agent
class reset_agent extends uvm_agent;
  `uvm_component_utils(reset_agent)

  // ---------------------------------------------------------------------------
  // Components
  // ---------------------------------------------------------------------------
  reset_sequencer  seqr;
  reset_driver     drv;
  reset_monitor    mon;

  // ---------------------------------------------------------------------------
  // Constructor
  // ---------------------------------------------------------------------------
  function new(string name = "reset_agent", uvm_component parent = null);
    super.new(name, parent);
  endfunction : new

  // ---------------------------------------------------------------------------
  // Build Phase
  // ---------------------------------------------------------------------------
  function void build_phase(uvm_phase phase);
    uvm_active_passive_enum mode;
    super.build_phase(phase);
    if (!uvm_resource_db#(uvm_active_passive_enum)::read_by_name(
            get_full_name(), "is_active", mode, this)) begin
      `uvm_warning("NOMODE", $sformatf(
          "[%s] No is_active resource found -- defaulting to UVM_ACTIVE",
          get_full_name()))
      mode = UVM_ACTIVE;
    end
    is_active = mode;
    // Propagate vif to children via resource_db (no modport)
    begin
      virtual reset_if vif_all;
      if (uvm_resource_db#(virtual reset_if)::read_by_name(
              get_full_name(), "vif", vif_all, this)) begin
        uvm_resource_db#(virtual reset_if)::set(
            {get_full_name(), ".drv.*"}, "vif", vif_all, this);
        uvm_resource_db#(virtual reset_if)::set(
            {get_full_name(), ".mon.*"}, "vif", vif_all, this);
      end
    end
    mon = reset_monitor::type_id::create("mon", this);
    if (is_active == UVM_ACTIVE) begin
      seqr = reset_sequencer ::type_id::create("seqr", this);
      drv  = reset_driver    ::type_id::create("drv",  this);
    end
  endfunction : build_phase

  // ---------------------------------------------------------------------------
  // Connect Phase
  // ---------------------------------------------------------------------------
  function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    if (is_active == UVM_ACTIVE) begin
      drv.seq_item_port.connect(seqr.seq_item_export);
    end
  endfunction : connect_phase

endclass : reset_agent
