//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Base sequence for agent "dfi_agent"
class lpddr5c_dfi_agent_base_seq extends uvm_sequence #(lpddr5c_dfi_agent_seq_item);

  `uvm_object_utils(lpddr5c_dfi_agent_base_seq)

  rand int unsigned num_items = 10;

  function new(string name = "lpddr5c_dfi_agent_base_seq");
    super.new(name);
  endfunction

  task body();
    lpddr5c_dfi_agent_seq_item item;
    repeat (num_items) begin
      item = lpddr5c_dfi_agent_seq_item::type_id::create("item");
      start_item(item);
      if (!item.randomize())
        `uvm_error("RANDFAIL", "Item randomization failed")
      finish_item(item);
    end
  endtask

endclass : lpddr5c_dfi_agent_base_seq
