//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Functional coverage collector for agent "utmi_agent" (interface group
// "utmi"). Implemented as a uvm_subscriber so it plugs
// directly into the monitor's existing analysis port (ap.connect) with
// no extra TLM export declarations needed.
class usbh_host_utmi_agent_coverage extends uvm_subscriber #(usbh_host_utmi_agent_seq_item);

  `uvm_component_utils(usbh_host_utmi_agent_coverage)

  usbh_host_utmi_agent_seq_item item;

  covergroup cg_utmi_agent;
    option.per_instance = 1;
    option.name = $sformatf("%s_cg_utmi_agent", get_full_name());
    cp_utmi_data_in_i: coverpoint item.utmi_data_in_i;  // <=8b -- auto bins
    cp_utmi_txready_i: coverpoint item.utmi_txready_i;  // 1-bit -- auto bins (0/1)
    cp_utmi_rxvalid_i: coverpoint item.utmi_rxvalid_i;  // 1-bit -- auto bins (0/1)
    cp_utmi_rxactive_i: coverpoint item.utmi_rxactive_i;  // 1-bit -- auto bins (0/1)
    cp_utmi_rxerror_i: coverpoint item.utmi_rxerror_i;  // 1-bit -- auto bins (0/1)
    cp_utmi_linestate_i: coverpoint item.utmi_linestate_i;  // <=8b -- auto bins
    cp_utmi_data_out_o: coverpoint item.utmi_data_out_o;  // <=8b -- auto bins
    cp_utmi_txvalid_o: coverpoint item.utmi_txvalid_o;  // 1-bit -- auto bins (0/1)
    cp_utmi_op_mode_o: coverpoint item.utmi_op_mode_o;  // <=8b -- auto bins
    cp_utmi_xcvrselect_o: coverpoint item.utmi_xcvrselect_o;  // <=8b -- auto bins
    cp_utmi_termselect_o: coverpoint item.utmi_termselect_o;  // 1-bit -- auto bins (0/1)
    cp_utmi_dppulldown_o: coverpoint item.utmi_dppulldown_o;  // 1-bit -- auto bins (0/1)
    cp_utmi_dmpulldown_o: coverpoint item.utmi_dmpulldown_o;  // 1-bit -- auto bins (0/1)
    cx_utmi_data_in_i_utmi_txready_i: cross cp_utmi_data_in_i, cp_utmi_txready_i;  // TODO: prune/expand as needed

  endgroup

  function new(string name = "usbh_host_utmi_agent_coverage", uvm_component parent = null);
    super.new(name, parent);
    cg_utmi_agent = new();
  endfunction

  function void write(usbh_host_utmi_agent_seq_item t);
    item = t;
    cg_utmi_agent.sample();
  endfunction

  function void report_phase(uvm_phase phase);
    super.report_phase(phase);
    `uvm_info("COV", $sformatf("[%s] Coverage = %0.2f%%", get_full_name(),
              cg_utmi_agent.get_coverage()), UVM_LOW)
  endfunction

endclass : usbh_host_utmi_agent_coverage
