//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Sequence item for agent "utmi_agent" (bound to interface group "utmi").
class usbh_host_utmi_agent_seq_item extends uvm_sequence_item;

    rand bit respond; // Indicates whether the USB device sends a response
    //For utmi_data_i: 
    		      //first received byte is interpreted as the response PID.
    		      // DATA0 / DATA1 / ACK / NAK / STALL
    rand bit [7:0] response_pid; //What packet (kind of response)  should the USB device send?
    rand bit [7:0] payload[]; // Payload for DATA0/DATA1 response    
    rand bit crc_error; // Inject CRC error in DATA0 / DATA1 response

  `uvm_object_utils_begin(usbh_host_utmi_agent_seq_item)
    `uvm_field_int(respond, UVM_ALL_ON)
    `uvm_field_int(response_pid, UVM_ALL_ON)
    `uvm_field_array(payload, UVM_ALL_ON)
    `uvm_field_int(crc_error, UVM_ALL_ON)
  `uvm_object_utils_end

  function new(string name = "usbh_host_utmi_agent_seq_item");
    super.new(name);
  endfunction

   
    // ---------------------------------------------------------
    // Constraints
    // ---------------------------------------------------------
    
    //By default, device reponds
    constraint response_c{
    	respond dist {
    	    8'hC3, // PID_DATA0
    	    8'h4B, // PID_DATA1
    	    8'hD2, // PID_ACK
    	    8'h5A, // PID_NAK
    	    8'h1E  // PID_STALL
    	};
    }   
    // CRC error is meaningful only for DATA packets
    constraint crc_error_c {
        if (response_pid inside {8'hC3, 8'h4B}) {
            crc_error dist {
                1'b0 := 90,
                1'b1 := 10
            };
        }
        else {
            crc_error == 1'b0;
        }
    }    
    //Payload is only valid for DATA0 / DATA1
    constraint payload_c {
        if (response_pid inside {8'hC3, 8'h4B}) {
            payload.size() inside {[0:64]};
        }
        else {
            payload.size() == 0;
        }
    }

endclass : usbh_host_utmi_agent_seq_item
