//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Monitor for agent "utmi_agent" -- observes interface group "utmi".
class usbh_host_utmi_agent_monitor extends uvm_monitor;

  `uvm_component_utils(usbh_host_utmi_agent_monitor)

  virtual usbh_host_utmi_if vif;
  uvm_analysis_port #(usbh_host_utmi_agent_seq_item) ap;

  function new(string name = "usbh_host_utmi_agent_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    ap = new("ap", this);
    if (!uvm_resource_db#(virtual usbh_host_utmi_if)::read_by_name(
            get_full_name(), "vif", vif, this))
      `uvm_fatal("NOVIF", $sformatf("[%s] Virtual interface not found in resource_db", get_full_name()))
  endfunction

  task run_phase(uvm_phase phase);
    usbh_host_utmi_agent_seq_item item;
    forever begin
      @(vif.mon_cb);
      item = usbh_host_utmi_agent_seq_item::type_id::create("item");
      item.utmi_data_in_i = vif.mon_cb.utmi_data_in_i;
      item.utmi_txready_i = vif.mon_cb.utmi_txready_i;
      item.utmi_rxvalid_i = vif.mon_cb.utmi_rxvalid_i;
      item.utmi_rxactive_i = vif.mon_cb.utmi_rxactive_i;
      item.utmi_rxerror_i = vif.mon_cb.utmi_rxerror_i;
      item.utmi_linestate_i = vif.mon_cb.utmi_linestate_i;
      item.utmi_data_out_o = vif.mon_cb.utmi_data_out_o;
      item.utmi_txvalid_o = vif.mon_cb.utmi_txvalid_o;
      item.utmi_op_mode_o = vif.mon_cb.utmi_op_mode_o;
      item.utmi_xcvrselect_o = vif.mon_cb.utmi_xcvrselect_o;
      item.utmi_termselect_o = vif.mon_cb.utmi_termselect_o;
      item.utmi_dppulldown_o = vif.mon_cb.utmi_dppulldown_o;
      item.utmi_dmpulldown_o = vif.mon_cb.utmi_dmpulldown_o;
      // TODO: gate on a valid/done condition specific to "utmi".
      ap.write(item);
    end
  endtask

endclass : usbh_host_utmi_agent_monitor
