//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Driver for agent "utmi_agent" -- drives interface group "utmi".
class usbh_host_utmi_agent_driver extends uvm_driver #(usbh_host_utmi_agent_seq_item);

  `uvm_component_utils(usbh_host_utmi_agent_driver)

  virtual usbh_host_utmi_if vif;

  function new(string name = "usbh_host_utmi_agent_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_resource_db#(virtual usbh_host_utmi_if)::read_by_name(
            get_full_name(), "vif", vif, this))
      `uvm_fatal("NOVIF", $sformatf("[%s] Virtual interface not found in resource_db", get_full_name()))
  endfunction

  task run_phase(uvm_phase phase);
    forever begin
      // Reset is input -- when asserted (rst_i==0) hold driver in reset
      if (vif.rst_i === 1'b0) begin
        do_reset();
        @(posedge vif.rst_i);
        `uvm_info(get_type_name(), "Reset deasserted -- driver resuming", UVM_MEDIUM)
      end
      // When reset not applied (rst_i==1) continue normal drive
      seq_item_port.get_next_item(req);
      // Re-check reset after blocking get (may have asserted)
      if (vif.rst_i === 1'b0) begin
        `uvm_info(get_type_name(), "Reset asserted during item fetch -- dropping item", UVM_MEDIUM)
        seq_item_port.item_done();
        do_reset();
        continue;
      end
      drive_item(req);
      seq_item_port.item_done();
    end
  endtask

  task do_reset();
    // Drive interface to reset/idle state while reset is applied
    @(vif.drv_cb);
    // TODO: drive reset defaults for utmi (e.g., valid->0)
  endtask

  task drive_item(usbh_host_utmi_agent_seq_item req);
    @(vif.drv_cb);
      vif.drv_cb.utmi_data_in_i <= req.utmi_data_in_i;
      vif.drv_cb.utmi_txready_i <= req.utmi_txready_i;
      vif.drv_cb.utmi_rxvalid_i <= req.utmi_rxvalid_i;
      vif.drv_cb.utmi_rxactive_i <= req.utmi_rxactive_i;
      vif.drv_cb.utmi_rxerror_i <= req.utmi_rxerror_i;
      vif.drv_cb.utmi_linestate_i <= req.utmi_linestate_i;
    // TODO: add protocol handshake wait specific to "utmi".
  endtask

endclass : usbh_host_utmi_agent_driver
