//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Base sequence for agent "axi4_agent"
class usbh_host_axi4_agent_base_seq extends uvm_sequence #(usbh_host_axi4_agent_seq_item);

  `uvm_object_utils(usbh_host_axi4_agent_base_seq)

  rand int unsigned num_items = 10;

  function new(string name = "usbh_host_axi4_agent_base_seq");
    super.new(name);
  endfunction

  task body();
    usbh_host_axi4_agent_seq_item item;
    repeat (num_items) begin
      item = usbh_host_axi4_agent_seq_item::type_id::create("item");
      start_item(item);
      if (!item.randomize())
        `uvm_error("RANDFAIL", "Item randomization failed")
      finish_item(item);
    end
  endtask

endclass : usbh_host_axi4_agent_base_seq
