//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


 // Testbench top: usbh_top_tb
 // Instantiates one interface per finalized signal group, connects
 // each to the DUT, and publishes every group's virtual interface into
 // uvm_resource_db (global scope "*") so any agent can read it by name.
 // Dedicated reset_if + reset_agent drive reset via resource_db.
 `include "uvm_macros.svh"
 import uvm_pkg::*;
 /*
 `include "usbh_host_pkg.sv"
 `include "usbh_host_axi4_if.sv"
 `include "usbh_host_utmi_if.sv"
 `include "reset_if.sv"
 `include "reset_transaction.sv"
 `include "reset_sequencer.sv "
 `include "reset_driver.sv "
 `include "reset_monitor.sv "
 `include "reset_agent.sv "
 `include "usbh_host_axi4_agent_seq_item.sv"
 `include "usbh_host_axi4_agent_sequencer.sv"
 `include "usbh_host_axi4_agent_driver.sv"
 `include "usbh_host_axi4_agent_monitor.sv"
 `include "usbh_host_axi4_agent.sv"
 `include "usbh_host_axi4_agent_coverage.sv"
 `include "usbh_host_axi4_agent_base_seq.sv"
 `include "usbh_host_utmi_agent_seq_item.sv"
 `include "usbh_host_utmi_agent_sequencer.sv"
 `include "usbh_host_utmi_agent_driver.sv"
 `include "usbh_host_utmi_agent_monitor.sv"
 `include "usbh_host_utmi_agent.sv"
 `include "usbh_host_utmi_agent_coverage.sv"
 `include "usbh_host_utmi_agent_base_seq.sv"
 `include "usbh_host_scoreboard.sv"
 `include "usbh_host_env.sv"
 `include "base_test.sv"
 `include "usb_device_bfm.sv"*/

 module usbh_top_tb;

   logic clk_i;
  logic rst_i;

   //reset_if rst_i_vif();

   usbh_host_axi4_if axi4_vif (.clk_i(clk_i));
  assign axi4_vif.rst_i = rst_i;

  usbh_host_utmi_if utmi_vif (.clk_i(clk_i));
  assign utmi_vif.rst_i = rst_i;

   //assign rst_i = rst_i_vif.rst_i;
   
   

   usbh_host dut (
         .clk_i(clk_i),
        .rst_i(rst_i),
        .cfg_awvalid_i(axi4_vif.cfg_awvalid_i),
        .cfg_awaddr_i(axi4_vif.cfg_awaddr_i),
        .cfg_wvalid_i(axi4_vif.cfg_wvalid_i),
        .cfg_wdata_i(axi4_vif.cfg_wdata_i),
        .cfg_wstrb_i(axi4_vif.cfg_wstrb_i),
        .cfg_bready_i(axi4_vif.cfg_bready_i),
        .cfg_arvalid_i(axi4_vif.cfg_arvalid_i),
        .cfg_araddr_i(axi4_vif.cfg_araddr_i),
        .cfg_rready_i(axi4_vif.cfg_rready_i),
        .utmi_data_in_i(utmi_vif.utmi_data_in_i),
        .utmi_txready_i(utmi_vif.utmi_txready_i),
        .utmi_rxvalid_i(utmi_vif.utmi_rxvalid_i),
        .utmi_rxactive_i(utmi_vif.utmi_rxactive_i),
        .utmi_rxerror_i(utmi_vif.utmi_rxerror_i),
        .utmi_linestate_i(utmi_vif.utmi_linestate_i),
        .cfg_awready_o(axi4_vif.cfg_awready_o),
        .cfg_wready_o(axi4_vif.cfg_wready_o),
        .cfg_bvalid_o(axi4_vif.cfg_bvalid_o),
        .cfg_bresp_o(axi4_vif.cfg_bresp_o),
        .cfg_arready_o(axi4_vif.cfg_arready_o),
        .cfg_rvalid_o(axi4_vif.cfg_rvalid_o),
        .cfg_rdata_o(axi4_vif.cfg_rdata_o),
        .cfg_rresp_o(axi4_vif.cfg_rresp_o),
        .intr_o(axi4_vif.intr_o),
        .utmi_data_out_o(utmi_vif.utmi_data_out_o),
        .utmi_txvalid_o(utmi_vif.utmi_txvalid_o),
        .utmi_op_mode_o(utmi_vif.utmi_op_mode_o),
        .utmi_xcvrselect_o(utmi_vif.utmi_xcvrselect_o),
        .utmi_termselect_o(utmi_vif.utmi_termselect_o),
        .utmi_dppulldown_o(utmi_vif.utmi_dppulldown_o),
        .utmi_dmpulldown_o(utmi_vif.utmi_dmpulldown_o)
   );
   
   //Device BFM Instance
   usb_device_bfm #(
      .DEVICE_IFS_CLKS(7),
      .MAX_IN_DATA(64)
   ) device_bfm (
            .clk_i(clk_i),
	    .rst_i(rst_i),

	    // DUT -> Device BFM
	    .utmi_data_out_o   (utmi_vif.utmi_data_out_o),
	    .utmi_txvalid_o    (utmi_vif.utmi_txvalid_o),
	    .utmi_op_mode_o    (utmi_vif.utmi_op_mode_o),
	    .utmi_xcvrselect_o (utmi_vif.utmi_xcvrselect_o),
	    .utmi_termselect_o (utmi_vif.utmi_termselect_o),
	    .utmi_dppulldown_o (utmi_vif.utmi_dppulldown_o),
	    .utmi_dmpulldown_o (utmi_vif.utmi_dmpulldown_o),

	    // Device BFM -> DUT
	    .utmi_data_in_i    (utmi_vif.utmi_data_in_i),
	    .utmi_txready_i    (utmi_vif.utmi_txready_i),
	    .utmi_rxvalid_i    (utmi_vif.utmi_rxvalid_i),
	    .utmi_rxactive_i   (utmi_vif.utmi_rxactive_i),
	    .utmi_rxerror_i    (utmi_vif.utmi_rxerror_i),
	    .utmi_linestate_i  (utmi_vif.utmi_linestate_i)  
   );
   
   initial clk_i = 0;
  always #5 clk_i = ~clk_i;   // 100MHz; TODO: adjust to target frequency
   
   initial begin
       rst_i = 1'b1;
       repeat (5) @(posedge clk_i);
       rst_i = 1'b0;
       //repeat (5) @(posedge clk_i);
       //rst_i = 1'b0;
   end   
   
   initial begin
     $dumpfile("usbh_top_tb.vcd");
     $dumpvars(0, usbh_top_tb);
   end

   initial begin
     uvm_resource_db#(virtual usbh_host_axi4_if)::set("*", "vif", axi4_vif);
    uvm_resource_db#(virtual usbh_host_utmi_if)::set("*", "vif", utmi_vif);
    //uvm_resource_db#(virtual reset_if)::set("uvm_test_top.env.reset_agent_rst_i.*", "vif", rst_i_vif);
    //uvm_resource_db#(virtual reset_if)::set("*", "vif", rst_i_vif); // fallback wildcard
     run_test("pid_data0_test"); //do reset_test also
     //run_test("reset_test_1"); //do reset_test also
     
   end

 endmodule : usbh_top_tb
 
