$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/accumulator_buffer.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/activation_fifo.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/activation_unit.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/decoder.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/fetcher.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/layernorm_unit.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/matrix_controller.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/memory_controller.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/pe.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/sequencer.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/softmax_unit.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/systolic_array.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/tiling_controller.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/tpu_top.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/unified_buffer.sv
$REPO_ROOT/DSN/ip/compute/tpu/ip/tpu/rtl/src/weight_fifo.sv
