class power_on_reset_seq extends uvm_sequence #(reset_item);  // Declares this UVM testbench class.
    `uvm_object_utils(power_on_reset_seq)  // Registers this sequence-item or sequence type with the UVM factory.
    task body();  // Defines the stimulus generated by this sequence.
        reset_item t=reset_item::type_id::create("t");  // Creates this UVM object/component through the UVM factory.
        start_item(t);  // Implements this testbench declaration or operation.
        t.assert_cycles=10;  // Updates t.assert_cycles for the current transaction or testbench state.
        finish_item(t);  // Implements this testbench declaration or operation.
    endtask  // Ends this task.
endclass  // Ends this UVM class definition.
class axil_write_seq extends uvm_sequence #(axil_item);  // Declares this UVM testbench class.
    `uvm_object_utils(axil_write_seq)  // Registers this sequence-item or sequence type with the UVM factory.
    bit[11:0] addr;  // Declares storage used by this testbench object or operation.
    bit[31:0] data;  // Declares storage used by this testbench object or operation.
    task body();  // Defines the stimulus generated by this sequence.
        axil_item t=axil_item::type_id::create("t");  // Creates this UVM object/component through the UVM factory.
        start_item(t);  // Implements this testbench declaration or operation.
        t.op=AXIL_WRITE;  // Updates t.op for the current transaction or testbench state.
        t.addr=addr;  // Updates t.addr for the current transaction or testbench state.
        t.data=data;  // Updates t.data for the current transaction or testbench state.
        t.strb='1;  // Updates t.strb for the current transaction or testbench state.
        finish_item(t);  // Implements this testbench declaration or operation.
    endtask  // Ends this task.
endclass  // Ends this UVM class definition.
class axil_read_seq extends uvm_sequence #(axil_item);  // Declares this UVM testbench class.
    `uvm_object_utils(axil_read_seq)  // Registers this sequence-item or sequence type with the UVM factory.
    bit[11:0] addr;  // Declares storage used by this testbench object or operation.
    bit[31:0] data;  // Declares storage used by this testbench object or operation.
    task body();  // Defines the stimulus generated by this sequence.
        axil_item t=axil_item::type_id::create("t");  // Creates this UVM object/component through the UVM factory.
        start_item(t);  // Implements this testbench declaration or operation.
        t.op=AXIL_READ;  // Updates t.op for the current transaction or testbench state.
        t.addr=addr;  // Updates t.addr for the current transaction or testbench state.
        finish_item(t);  // Implements this testbench declaration or operation.
        data=t.data;  // Updates data for the current transaction or testbench state.
    endtask  // Ends this task.
endclass  // Ends this UVM class definition.
