class dma_tx_vseq extends uvm_sequence;  // Declares this UVM testbench class.
    `uvm_object_utils(dma_tx_vseq)  // Registers this sequence-item or sequence type with the UVM factory.
    `uvm_declare_p_sequencer(ethernet_virtual_sequencer)  // Declares the typed virtual sequencer used by this virtual sequence.
    task body();  // Defines the stimulus generated by this sequence.
        axil_write_seq w;  // Implements this testbench declaration or operation.
        w=axil_write_seq::type_id::create("tx_base_l");  // Creates this UVM object/component through the UVM factory.
        w.addr='h10;  // Updates w.addr for the current transaction or testbench state.
        w.data='h1000_0000;  // Updates w.data for the current transaction or testbench state.
        w.start(p_sequencer.axil_sqr);  // Starts this sequence on the selected sequencer.
        w=axil_write_seq::type_id::create("tx_base_h");  // Creates this UVM object/component through the UVM factory.
        w.addr='h14;  // Updates w.addr for the current transaction or testbench state.
        w.data=0;  // Updates w.data for the current transaction or testbench state.
        w.start(p_sequencer.axil_sqr);  // Starts this sequence on the selected sequencer.
        w=axil_write_seq::type_id::create("tx_len");  // Creates this UVM object/component through the UVM factory.
        w.addr='h18;  // Updates w.addr for the current transaction or testbench state.
        w.data=8;  // Updates w.data for the current transaction or testbench state.
        w.start(p_sequencer.axil_sqr);  // Starts this sequence on the selected sequencer.
        w=axil_write_seq::type_id::create("int_en");  // Creates this UVM object/component through the UVM factory.
        w.addr='h08;  // Updates w.addr for the current transaction or testbench state.
        w.data=1;  // Updates w.data for the current transaction or testbench state.
        w.start(p_sequencer.axil_sqr);  // Starts this sequence on the selected sequencer.
        w=axil_write_seq::type_id::create("dma_en");  // Creates this UVM object/component through the UVM factory.
        w.addr='h00;  // Updates w.addr for the current transaction or testbench state.
        w.data=1;  // Updates w.data for the current transaction or testbench state.
        w.start(p_sequencer.axil_sqr);  // Starts this sequence on the selected sequencer.
        w=axil_write_seq::type_id::create("doorbell");  // Creates this UVM object/component through the UVM factory.
        w.addr='h1c;  // Updates w.addr for the current transaction or testbench state.
        w.data=1;  // Updates w.data for the current transaction or testbench state.
        w.start(p_sequencer.axil_sqr);  // Starts this sequence on the selected sequencer.
    endtask  // Ends this task.
endclass  // Ends this UVM class definition.
class dma_rx_vseq extends uvm_sequence;  // Declares this UVM testbench class.
    `uvm_object_utils(dma_rx_vseq)  // Registers this sequence-item or sequence type with the UVM factory.
    `uvm_declare_p_sequencer(ethernet_virtual_sequencer)  // Declares the typed virtual sequencer used by this virtual sequence.
    task body();  // Defines the stimulus generated by this sequence.
        axil_write_seq w;  // Implements this testbench declaration or operation.
        w=axil_write_seq::type_id::create("rx_base_l");  // Creates this UVM object/component through the UVM factory.
        w.addr='h20;  // Updates w.addr for the current transaction or testbench state.
        w.data='h3000_0000;  // Updates w.data for the current transaction or testbench state.
        w.start(p_sequencer.axil_sqr);  // Starts this sequence on the selected sequencer.
        w=axil_write_seq::type_id::create("rx_base_h");  // Creates this UVM object/component through the UVM factory.
        w.addr='h24;  // Updates w.addr for the current transaction or testbench state.
        w.data=0;  // Updates w.data for the current transaction or testbench state.
        w.start(p_sequencer.axil_sqr);  // Starts this sequence on the selected sequencer.
        w=axil_write_seq::type_id::create("rx_len");  // Creates this UVM object/component through the UVM factory.
        w.addr='h28;  // Updates w.addr for the current transaction or testbench state.
        w.data=8;  // Updates w.data for the current transaction or testbench state.
        w.start(p_sequencer.axil_sqr);  // Starts this sequence on the selected sequencer.
        w=axil_write_seq::type_id::create("int_en");  // Creates this UVM object/component through the UVM factory.
        w.addr='h08;  // Updates w.addr for the current transaction or testbench state.
        w.data=2;  // Updates w.data for the current transaction or testbench state.
        w.start(p_sequencer.axil_sqr);  // Starts this sequence on the selected sequencer.
        w=axil_write_seq::type_id::create("dma_en");  // Creates this UVM object/component through the UVM factory.
        w.addr='h00;  // Updates w.addr for the current transaction or testbench state.
        w.data=2;  // Updates w.data for the current transaction or testbench state.
        w.start(p_sequencer.axil_sqr);  // Starts this sequence on the selected sequencer.
        w=axil_write_seq::type_id::create("doorbell");  // Creates this UVM object/component through the UVM factory.
        w.addr='h2c;  // Updates w.addr for the current transaction or testbench state.
        w.data=1;  // Updates w.data for the current transaction or testbench state.
        w.start(p_sequencer.axil_sqr);  // Starts this sequence on the selected sequencer.
    endtask  // Ends this task.
endclass  // Ends this UVM class definition.
