// SPDX-License-Identifier: GPL-3.0-or-later OR Commercial
//
// SPI master controller.
//
// Implements the four classical Motorola SPI modes (CPOL x CPHA = 4 modes)
// with parametrizable word width (4..32 bits), parametrizable chip-select
// count, programmable clock divider, and MSB-first / LSB-first selection.
//
// Mode legend (Motorola SPI block guide MOTOROLA M68HC11 §8.5):
//
//   MODE  CPOL  CPHA  Idle SCK  Sample edge       Shift edge
//   ----  ----  ----  --------  -----------       ----------
//     0     0     0   low       rising  (1st)     falling (2nd)
//     1     0     1   low       falling (2nd)     rising  (1st)
//     2     1     0   high      falling (1st)     rising  (2nd)
//     3     1     1   high      rising  (2nd)     falling (1st)
//
// CPHA=0 quirk: the FIRST data bit must be PRESENTED on MOSI when CS goes
// low (no SCK edge has happened yet). The slave samples on the first
// edge; master shifts on the second.
// CPHA=1 quirk: the master CHANGES data on the first edge of each bit
// (the rising edge for mode 1, falling for mode 3). The very first
// "change" simply re-presents the loaded byte. The slave samples on
// the second edge.
//
// SCK is generated by dividing clk_i by 2*(div_i+1). div_i=0 gives the
// fastest SCK (clk_i / 2), div_i=255 the slowest (clk_i / 512).
//
// CS is active-low. cs_idle_cycles_i delays SCK after CS-fall (setup) and
// CS-rise after the last shift edge (hold). cs_inter_byte_i optionally
// keeps CS asserted across multiple FIFO words for back-to-back transfers
// without de-asserting the slave.
//
// Reset is synchronous active-low (rst_ni). Mid-transfer reset is safe.

module spi_master #(
  parameter int unsigned DATA_WIDTH = 8,
  parameter int unsigned NUM_CS     = 4,
  parameter int unsigned FIFO_DEPTH = 16,
  parameter int unsigned DIV_WIDTH  = 16,
  parameter int unsigned CS_DLY_W   = 8
) (
  input  logic                          clk_i,
  input  logic                          rst_ni,

  input  logic                          cpol_i,
  input  logic                          cpha_i,
  input  logic                          lsb_first_i,
  input  logic [DIV_WIDTH-1:0]          clk_div_i,
  input  logic [$clog2(NUM_CS)-1:0]     cs_sel_i,
  input  logic [CS_DLY_W-1:0]           cs_setup_cycles_i,
  input  logic [CS_DLY_W-1:0]           cs_hold_cycles_i,
  input  logic                          cs_inter_byte_i,

  input  logic                          tx_we_i,
  input  logic [DATA_WIDTH-1:0]         tx_wdata_i,
  output logic                          tx_full_o,
  output logic                          tx_empty_o,
  output logic [$clog2(FIFO_DEPTH+1)-1:0] tx_count_o,

  input  logic                          rx_re_i,
  output logic [DATA_WIDTH-1:0]         rx_rdata_o,
  output logic                          rx_full_o,
  output logic                          rx_empty_o,
  output logic [$clog2(FIFO_DEPTH+1)-1:0] rx_count_o,

  input  logic                          start_i,
  output logic                          busy_o,
  output logic                          xfer_done_o,

  output logic                          sck_o,
  output logic                          mosi_o,
  input  logic                          miso_i,
  output logic [NUM_CS-1:0]             cs_n_o
);

  // -----------------------------------------------------------------
  // FIFOs
  // -----------------------------------------------------------------
  logic                          tx_fifo_rd_en;
  logic [DATA_WIDTH-1:0]         tx_fifo_rdata;
  logic                          tx_fifo_empty;

  spi_fifo #(.WIDTH(DATA_WIDTH), .DEPTH(FIFO_DEPTH)) u_tx_fifo (
    .clk_i    (clk_i),
    .rst_ni   (rst_ni),
    .wr_en_i  (tx_we_i),
    .wr_data_i(tx_wdata_i),
    .rd_en_i  (tx_fifo_rd_en),
    .rd_data_o(tx_fifo_rdata),
    .empty_o  (tx_fifo_empty),
    .full_o   (tx_full_o),
    .count_o  (tx_count_o)
  );
  assign tx_empty_o = tx_fifo_empty;

  logic                          rx_fifo_wr_en;
  logic [DATA_WIDTH-1:0]         rx_fifo_wdata;

  spi_fifo #(.WIDTH(DATA_WIDTH), .DEPTH(FIFO_DEPTH)) u_rx_fifo (
    .clk_i    (clk_i),
    .rst_ni   (rst_ni),
    .wr_en_i  (rx_fifo_wr_en),
    .wr_data_i(rx_fifo_wdata),
    .rd_en_i  (rx_re_i),
    .rd_data_o(rx_rdata_o),
    .empty_o  (rx_empty_o),
    .full_o   (rx_full_o),
    .count_o  (rx_count_o)
  );

  // -----------------------------------------------------------------
  // FSM and bit-clock generator
  // -----------------------------------------------------------------
  typedef enum logic [2:0] {
    S_IDLE       = 3'd0,
    S_LOAD_WAIT  = 3'd1,
    S_CS_SETUP   = 3'd2,
    S_SHIFT      = 3'd3,
    S_CS_HOLD    = 3'd4,
    S_DONE       = 3'd5
  } state_e;

  state_e state_q, state_d;

  logic                       cpol_q, cpha_q, lsb_q;
  logic [DIV_WIDTH-1:0]       div_q;
  logic [$clog2(NUM_CS)-1:0]  cs_sel_q;
  logic [CS_DLY_W-1:0]        setup_q, hold_q;
  logic                       inter_byte_q;

  logic [DIV_WIDTH-1:0]       div_cnt_q;
  logic [$clog2(2*32+2)-1:0]  edge_cnt_q;     // 0..2*DATA_WIDTH
  logic [$clog2(33)-1:0]      sample_cnt_q;   // bits sampled so far
  logic [CS_DLY_W:0]          dly_cnt_q;
  logic                       sck_q;
  logic [DATA_WIDTH-1:0]      tx_shift_q;
  logic [DATA_WIDTH-1:0]      rx_shift_q;

  logic                       sck_tick;
  assign sck_tick = (div_cnt_q == '0);

  logic [$clog2(2*32+2)-1:0]  edge_cnt_max;
  assign edge_cnt_max = ($clog2(2*32+2))'(2*DATA_WIDTH);

  // -----------------------------------------------------------------
  // Combinational next-state.
  // -----------------------------------------------------------------
  always_comb begin
    state_d = state_q;
    case (state_q)
      S_IDLE: begin
        if (start_i && !tx_fifo_empty)
          state_d = S_LOAD_WAIT;
      end
      S_LOAD_WAIT: begin
        // 1 extra cycle so the FIFO read settles into tx_shift_q.
        state_d = S_CS_SETUP;
      end
      S_CS_SETUP: begin
        if (dly_cnt_q == '0)
          state_d = S_SHIFT;
      end
      S_SHIFT: begin
        if (sck_tick && (edge_cnt_q == edge_cnt_max - 1'b1))
          state_d = S_CS_HOLD;
      end
      S_CS_HOLD: begin
        if (dly_cnt_q == '0) begin
          if (inter_byte_q && !tx_fifo_empty) state_d = S_LOAD_WAIT;
          else                                state_d = S_DONE;
        end
      end
      S_DONE: state_d = S_IDLE;
      default: state_d = S_IDLE;
    endcase
  end

  // FIFO read: pulse 1 cycle on entering LOAD_WAIT.
  assign tx_fifo_rd_en  = (state_q == S_IDLE && state_d == S_LOAD_WAIT)
                       || (state_q == S_CS_HOLD && state_d == S_LOAD_WAIT);

  // RX push: registered pulse one cycle AFTER the last sample so the
  // last bit is included in rx_shift_q.
  logic                  rx_fifo_wr_en_q;
  logic [DATA_WIDTH-1:0] rx_fifo_wdata_q;
  logic [DATA_WIDTH-1:0] rx_next_w;
  logic                  do_sample_w;
  assign rx_fifo_wr_en = rx_fifo_wr_en_q;
  assign rx_fifo_wdata = rx_fifo_wdata_q;

  // Combinational rx_next/do_sample compute, used inside the SHIFT
  // sequential block. Yosys-friendly (no `automatic`).
  always_comb begin
    rx_next_w   = rx_shift_q;
    do_sample_w = 1'b0;
    if (state_q == S_SHIFT && div_cnt_q == '0) begin
      if (cpha_q == 1'b0) begin
        if (!edge_cnt_q[0]) begin
          do_sample_w = 1'b1;
          rx_next_w   = lsb_q ? {miso_i, rx_shift_q[DATA_WIDTH-1:1]}
                              : {rx_shift_q[DATA_WIDTH-2:0], miso_i};
        end
      end else begin
        if (edge_cnt_q[0]) begin
          do_sample_w = 1'b1;
          rx_next_w   = lsb_q ? {miso_i, rx_shift_q[DATA_WIDTH-1:1]}
                              : {rx_shift_q[DATA_WIDTH-2:0], miso_i};
        end
      end
    end
  end

  // CS active when transferring (LOAD_WAIT through CS_HOLD).
  always_comb begin
    cs_n_o = '1;
    if (state_q == S_LOAD_WAIT || state_q == S_CS_SETUP ||
        state_q == S_SHIFT     || state_q == S_CS_HOLD)
      cs_n_o[cs_sel_q] = 1'b0;
  end

  // mosi and sck.
  assign mosi_o = (state_q == S_SHIFT)
                    ? (lsb_q ? tx_shift_q[0] : tx_shift_q[DATA_WIDTH-1])
                    : 1'b0;
  assign sck_o  = sck_q;

  // -----------------------------------------------------------------
  // Sequential block
  // -----------------------------------------------------------------
  always_ff @(posedge clk_i) begin
    if (!rst_ni) begin
      state_q         <= S_IDLE;
      cpol_q          <= 1'b0;
      cpha_q          <= 1'b0;
      lsb_q           <= 1'b0;
      div_q           <= '0;
      cs_sel_q        <= '0;
      setup_q         <= '0;
      hold_q          <= '0;
      inter_byte_q    <= 1'b0;
      div_cnt_q       <= '0;
      edge_cnt_q      <= '0;
      sample_cnt_q    <= '0;
      dly_cnt_q       <= '0;
      sck_q           <= 1'b0;
      tx_shift_q      <= '0;
      rx_shift_q      <= '0;
      rx_fifo_wr_en_q <= 1'b0;
      rx_fifo_wdata_q <= '0;
      busy_o          <= 1'b0;
      xfer_done_o     <= 1'b0;
    end else begin
      state_q         <= state_d;
      busy_o          <= (state_d != S_IDLE);
      xfer_done_o     <= (state_q == S_DONE);
      rx_fifo_wr_en_q <= 1'b0;

      // Latch configuration on transition out of IDLE into LOAD_WAIT.
      if (state_q == S_IDLE && state_d == S_LOAD_WAIT) begin
        cpol_q       <= cpol_i;
        cpha_q       <= cpha_i;
        lsb_q        <= lsb_first_i;
        div_q        <= clk_div_i;
        cs_sel_q     <= cs_sel_i;
        setup_q      <= cs_setup_cycles_i;
        hold_q       <= cs_hold_cycles_i;
        inter_byte_q <= cs_inter_byte_i;
        sck_q        <= cpol_i;
        rx_shift_q   <= '0;
        edge_cnt_q   <= '0;
        div_cnt_q    <= clk_div_i;
      end

      // Capture FIFO output one cycle after rd_en.
      if (state_q == S_LOAD_WAIT) begin
        tx_shift_q   <= tx_fifo_rdata;
        rx_shift_q   <= '0;
        edge_cnt_q   <= '0;
        sample_cnt_q <= '0;
      end

      // CS_SETUP delay countdown
      if (state_q == S_LOAD_WAIT && state_d == S_CS_SETUP) begin
        dly_cnt_q <= {1'b0, setup_q};
      end else if (state_q == S_CS_SETUP) begin
        if (dly_cnt_q != '0) dly_cnt_q <= dly_cnt_q - 1'b1;
      end

      // CS_HOLD delay countdown
      if (state_q == S_SHIFT && state_d == S_CS_HOLD) begin
        dly_cnt_q <= {1'b0, hold_q};
      end else if (state_q == S_CS_HOLD) begin
        if (dly_cnt_q != '0) dly_cnt_q <= dly_cnt_q - 1'b1;
      end

      // SCK divider + sample/shift logic.
      // We treat the data flow as a sequence of "bit slots". For each
      // bit slot:
      //   * CPHA=0: SAMPLE on first SCK edge, SHIFT on second.
      //   * CPHA=1: SHIFT on first SCK edge (no actual change for bit 0
      //             since the loaded byte is already presented), SAMPLE
      //             on second.
      //
      // edge_cnt_q runs 0..2*DATA_WIDTH-1. For mode 0/2 (CPHA=0), even
      // edges (0, 2, 4, ...) sample MISO into rx_shift_q, odd edges
      // shift tx_shift_q. For mode 1/3 (CPHA=1), even edges shift
      // (the very first one is a no-op because tx_shift_q is already
      // showing bit 7), odd edges sample.
      if (state_q == S_SHIFT) begin
        if (div_cnt_q == '0) begin
          div_cnt_q  <= div_q;
          sck_q      <= ~sck_q;
          edge_cnt_q <= edge_cnt_q + 1'b1;

          // Sample / shift logic. Use the combinational do_sample_w /
          // rx_next_w computed above; emit the shift assignments here
          // for the corresponding edge classes.
          if (cpha_q == 1'b0) begin
            // Mode 0/2: even=sample (handled below), odd=shift.
            if (edge_cnt_q[0] && (edge_cnt_q != edge_cnt_max - 1'b1)) begin
              tx_shift_q <= lsb_q ? {1'b0, tx_shift_q[DATA_WIDTH-1:1]}
                                  : {tx_shift_q[DATA_WIDTH-2:0], 1'b0};
            end
          end else begin
            // Mode 1/3: even=shift (skip first), odd=sample (below).
            if (!edge_cnt_q[0] && (edge_cnt_q != '0)) begin
              tx_shift_q <= lsb_q ? {1'b0, tx_shift_q[DATA_WIDTH-1:1]}
                                  : {tx_shift_q[DATA_WIDTH-2:0], 1'b0};
            end
          end
          if (do_sample_w) begin
            rx_shift_q   <= rx_next_w;
            sample_cnt_q <= sample_cnt_q + 1'b1;
            if (sample_cnt_q == DATA_WIDTH-1) begin
              rx_fifo_wr_en_q <= 1'b1;
              rx_fifo_wdata_q <= rx_next_w;
            end
          end
        end else begin
          div_cnt_q <= div_cnt_q - 1'b1;
        end
      end else begin
        // Outside SHIFT, hold SCK at the latched idle polarity. We
        // snap sck_q to the new cpol only at the moment of transfer
        // launch (IDLE -> LOAD_WAIT) — see the launch-latching block
        // above. While idle we leave sck_q where it was so the SVA
        // can verify that SCK never toggles while CS is high.
        if (state_q != S_IDLE && state_d != S_SHIFT) sck_q <= cpol_q;
        // Reload divider so SHIFT starts with a fresh count.
        if (state_d == S_SHIFT)       div_cnt_q <= div_q;
        else                          div_cnt_q <= '0;
      end

      // Reset edge counter when leaving SHIFT to CS_HOLD.
      if (state_q == S_SHIFT && state_d == S_CS_HOLD) begin
        edge_cnt_q <= '0;
      end
    end
  end

endmodule
