// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_axi4_to_apb_bridge_cdc.h for the primary calling header

#ifndef VERILATED_VTB_AXI4_TO_APB_BRIDGE_CDC___024ROOT_H_
#define VERILATED_VTB_AXI4_TO_APB_BRIDGE_CDC___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_axi4_to_apb_bridge_cdc__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_axi4_to_apb_bridge_cdc___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__ACLK;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__PCLK;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__ARESETn;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__PRESETn;
        CData/*3:0*/ tb_axi4_to_apb_bridge_cdc__DOT__AWID;
        CData/*7:0*/ tb_axi4_to_apb_bridge_cdc__DOT__AWLEN;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__AWSIZE;
        CData/*1:0*/ tb_axi4_to_apb_bridge_cdc__DOT__AWBURST;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__AWLOCK;
        CData/*3:0*/ tb_axi4_to_apb_bridge_cdc__DOT__AWCACHE;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__AWPROT;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__AWVALID;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__WLAST;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__WVALID;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__BREADY;
        CData/*3:0*/ tb_axi4_to_apb_bridge_cdc__DOT__ARID;
        CData/*7:0*/ tb_axi4_to_apb_bridge_cdc__DOT__ARLEN;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__ARSIZE;
        CData/*1:0*/ tb_axi4_to_apb_bridge_cdc__DOT__ARBURST;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__ARLOCK;
        CData/*3:0*/ tb_axi4_to_apb_bridge_cdc__DOT__ARCACHE;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__ARPROT;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__ARVALID;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__RREADY;
        CData/*7:0*/ tb_axi4_to_apb_bridge_cdc__DOT__psel_bus;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__gpio_pready;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__gpio_pslverr;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__mipi_pready;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__mipi_pslverr;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__hdmi_pready;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__hdmi_pslverr;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__timer_pready;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__timer_pslverr;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__debug_pready;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__debug_pslverr;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__ARREADY;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__spi_psel;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__i2c_psel;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__uart_psel;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__gpio_psel;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__mipi_psel;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__hdmi_psel;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__timer_psel;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__debug_psel;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_full;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_empty;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_full;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_empty;
        CData/*3:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__axi_state;
        CData/*3:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__id_r;
        CData/*7:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__len_r;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__size_r;
        CData/*1:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__burst_r;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__prot_r;
        CData/*7:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__beat_cnt_r;
        CData/*1:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__sub_cnt_r;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__wresp_err_r;
        CData/*3:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__bid_r;
        CData/*1:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__bresp_r;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__bvalid_r;
        CData/*3:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__rid_r;
        CData/*1:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__rresp_r;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__rlast_r;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__rvalid_r;
    };
    struct {
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__rresp_err_acc_r;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__rresp_err_next;
        CData/*1:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__apb_state;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__p_write_r;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__p_prot_r;
        CData/*3:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__p_wstrb_r;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__p_err_r;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__psel_active;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__w_en;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__r_en;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__g_wptr_sync;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__g_rptr_sync;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__b_wptr;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__b_rptr;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__g_wptr;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__g_rptr;
        CData/*1:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__waddr;
        CData/*1:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__raddr;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__sync_rptr__DOT__q1;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__sync_wptr__DOT__q1;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__rptr_h__DOT__b_rptr_next;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__rptr_h__DOT__g_rptr_next;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__wptr_h__DOT__b_wptr_next;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__wptr_h__DOT__g_wptr_next;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__wptr_h__DOT__wrap_around;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__w_en;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__r_en;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__g_wptr_sync;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__g_rptr_sync;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__b_wptr;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__b_rptr;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__g_wptr;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__g_rptr;
        CData/*1:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__waddr;
        CData/*1:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__raddr;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__sync_rptr__DOT__q1;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__sync_wptr__DOT__q1;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__rptr_h__DOT__b_rptr_next;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__rptr_h__DOT__g_rptr_next;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__wptr_h__DOT__b_wptr_next;
        CData/*2:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__wptr_h__DOT__g_wptr_next;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__wptr_h__DOT__wrap_around;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__i2c_bfm__DOT__PREADY;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__spi_bfm__DOT__PREADY;
        CData/*0:0*/ tb_axi4_to_apb_bridge_cdc__DOT__uart_bfm__DOT__PREADY;
        CData/*7:0*/ __VdfgRegularize_h6e95ff9d_0_0;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_1;
        CData/*1:0*/ __Vdly__tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__apb_state;
        CData/*0:0*/ __Vdly__tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__p_write_r;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWID__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLEN__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWSIZE__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWBURST__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLOCK__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWCACHE__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWPROT__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WSTRB__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WLAST__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v1;
    };
    struct {
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARID__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLEN__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARSIZE__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARBURST__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLOCK__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARCACHE__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARPROT__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWID__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLEN__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWSIZE__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWBURST__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLOCK__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWCACHE__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWPROT__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WSTRB__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WLAST__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARID__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLEN__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARSIZE__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARBURST__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLOCK__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARCACHE__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARPROT__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWID__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLEN__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWSIZE__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWBURST__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLOCK__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWCACHE__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWPROT__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WSTRB__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WLAST__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARID__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLEN__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARSIZE__v2;
    };
    struct {
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARBURST__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLOCK__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARCACHE__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARPROT__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWID__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLEN__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWSIZE__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWBURST__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLOCK__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWCACHE__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWPROT__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v7;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WSTRB__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WLAST__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v7;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v7;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARID__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLEN__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARSIZE__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARBURST__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLOCK__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARCACHE__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARPROT__v3;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v7;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v7;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWID__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLEN__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWSIZE__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWBURST__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLOCK__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWCACHE__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWPROT__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v8;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v9;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WSTRB__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WLAST__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v8;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v9;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v8;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v9;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWID__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLEN__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWSIZE__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWBURST__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLOCK__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWCACHE__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWPROT__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v10;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v11;
    };
    struct {
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WSTRB__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WLAST__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v10;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v11;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v10;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v11;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWID__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLEN__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWSIZE__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWBURST__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWLOCK__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWCACHE__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWPROT__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v12;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__AWVALID__v13;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WSTRB__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WLAST__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v12;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__WVALID__v13;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v12;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__BREADY__v13;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARID__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLEN__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARSIZE__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARBURST__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLOCK__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARCACHE__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARPROT__v4;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v8;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v9;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v8;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v9;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARID__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLEN__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARSIZE__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARBURST__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLOCK__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARCACHE__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARPROT__v5;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v10;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v11;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v10;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v11;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARID__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLEN__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARSIZE__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARBURST__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARLOCK__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARCACHE__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARPROT__v6;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v12;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__ARVALID__v13;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v12;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__RREADY__v13;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__dummy_mem__v0;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__dummy_mem__v1;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__dummy_mem__v2;
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__dummy_mem__v3;
    };
    struct {
        CData/*0:0*/ __VdlySet__tb_axi4_to_apb_bridge_cdc__DOT__dummy_mem__v4;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_axi4_to_apb_bridge_cdc__DOT__PCLK__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_axi4_to_apb_bridge_cdc__DOT__PRESETn__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_axi4_to_apb_bridge_cdc__DOT__ACLK__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_axi4_to_apb_bridge_cdc__DOT__ARESETn__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__ARREADY__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__bvalid_r__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__rvalid_r__0;
        CData/*0:0*/ __Vtrigprevexpr_hb61146a0__1;
        CData/*0:0*/ __Vtrigprevexpr_hb611562d__1;
        SData/*15:0*/ tb_axi4_to_apb_bridge_cdc__DOT__WSTRB;
        SData/*15:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__wstrb_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__AWADDR;
        VlWide<4>/*127:0*/ tb_axi4_to_apb_bridge_cdc__DOT__WDATA;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__ARADDR;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__gpio_prdata;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__mipi_prdata;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__hdmi_prdata;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__timer_prdata;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__debug_prdata;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__d;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__a;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__decode_error_count;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__error_count;
        VlWide<4>/*127:0*/ tb_axi4_to_apb_bridge_cdc__DOT__exp_data;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__idx;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__PRDATA;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cur_addr_r;
        VlWide<4>/*127:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__wdata_reg;
        VlWide<4>/*127:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__rdata_r;
        VlWide<4>/*127:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__rdata_acc_r;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__sub_addr;
        VlWide<4>/*127:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__rdata_acc_next;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__p_addr_r;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__p_wdata_r;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__p_rdata_r;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__fifom__DOT__i;
        VlWide<3>/*71:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__data_out;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__fifom__DOT__i;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__i2c_bfm__DOT__data_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__i2c_bfm__DOT__ctrl_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__i2c_bfm__DOT__clk_div_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__i2c_bfm__DOT__irq_status_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__i2c_bfm__DOT__status_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__i2c_bfm__DOT__wait_count;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__spi_bfm__DOT__tx_data_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__spi_bfm__DOT__ctrl_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__spi_bfm__DOT__clk_div_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__spi_bfm__DOT__wait_count;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__uart_bfm__DOT__data_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__uart_bfm__DOT__ctrl_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__uart_bfm__DOT__baud_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__uart_bfm__DOT__irq_status_reg;
        IData/*31:0*/ tb_axi4_to_apb_bridge_cdc__DOT__uart_bfm__DOT__wait_count;
        IData/*31:0*/ __Vdly__tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__p_addr_r;
        IData/*31:0*/ __Vdly__tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__p_wdata_r;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v0;
        VlWide<4>/*127:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v0;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v0;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v1;
        VlWide<4>/*127:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v1;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v1;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v2;
        VlWide<4>/*127:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v2;
    };
    struct {
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v2;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v3;
        VlWide<4>/*127:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v3;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v3;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v4;
        VlWide<4>/*127:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v4;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v5;
        VlWide<4>/*127:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v5;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__AWADDR__v6;
        VlWide<4>/*127:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__WDATA__v6;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v4;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v5;
        IData/*31:0*/ __VdlyVal__tb_axi4_to_apb_bridge_cdc__DOT__ARADDR__v6;
        IData/*31:0*/ __Vi;
        QData/*32:0*/ tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__data_out;
        VlUnpacked<IData/*31:0*/, 8> tb_axi4_to_apb_bridge_cdc__DOT__PERIPH_BASE;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 256>, 5> tb_axi4_to_apb_bridge_cdc__DOT__dummy_mem;
        VlUnpacked<VlWide<4>/*127:0*/, 8> tb_axi4_to_apb_bridge_cdc__DOT__test_data;
        VlUnpacked<QData/*32:0*/, 4> tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__resp_fifo__DOT__fifom__DOT__fifo;
        VlUnpacked<VlWide<3>/*71:0*/, 4> tb_axi4_to_apb_bridge_cdc__DOT__dut__DOT__cmd_fifo__DOT__fifom__DOT__fifo;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggeredAcc;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
        VlUnpacked<CData/*0:0*/, 12> __Vm_traceActivity;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h0fe8bbce__0;
    VlTriggerScheduler __VtrigSched_hd312c1ce__0;
    VlTriggerScheduler __VtrigSched_h3239ee00__0;
    VlTriggerScheduler __VtrigSched_h96a50c21__0;
    VlTriggerScheduler __VtrigSched_h32259481__0;
    VlTriggerScheduler __VtrigSched_h3225845e__0;
    VlTriggerScheduler __VtrigSched_h631cf408__0;
    VlTriggerScheduler __VtrigSched_h0daa99c9__0;
    VlTriggerScheduler __VtrigSched_h6021f084__0;

    // INTERNAL VARIABLES
    Vtb_axi4_to_apb_bridge_cdc__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtb_axi4_to_apb_bridge_cdc___024root(Vtb_axi4_to_apb_bridge_cdc__Syms* symsp, const char* namep);
    ~Vtb_axi4_to_apb_bridge_cdc___024root();
    VL_UNCOPYABLE(Vtb_axi4_to_apb_bridge_cdc___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
