//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------
`timescale 1ns/1ps

`include "usbh_host_pkg.sv"
import usbh_host_pkg::*;
 // Interface: usbh_host_axi4_if
 // Bundles the "axi4" signal group (18 signal(s)),
 // auto-classified by AMBA naming convention (or user-assigned in the
 // grouping step). Port widths come from usbh_host_pkg parameters
 // (the package is `included AND imported so width parameters such as
 // CFG_AWVALID_I_W resolve here).
interface usbh_host_axi4_if (
    input logic clk_i
);

    logic rst_i;

    logic cfg_awvalid_i;  // input
    logic [CFG_AWADDR_I_W-1:0] cfg_awaddr_i;  // input [31:0]
    logic cfg_wvalid_i;  // input
    logic [CFG_WDATA_I_W-1:0] cfg_wdata_i;  // input [31:0]
    logic [CFG_WSTRB_I_W-1:0] cfg_wstrb_i;  // input [3:0]
    logic cfg_bready_i;  // input
    logic cfg_arvalid_i;  // input
    logic [CFG_ARADDR_I_W-1:0] cfg_araddr_i;  // input [31:0]
    logic cfg_rready_i;  // input
    logic cfg_awready_o;  // output
    logic cfg_wready_o;  // output
    logic cfg_bvalid_o;  // output
    logic [CFG_BRESP_O_W-1:0] cfg_bresp_o;  // output [1:0]
    logic cfg_arready_o;  // output
    logic cfg_rvalid_o;  // output
    logic [CFG_RDATA_O_W-1:0] cfg_rdata_o;  // output [31:0]
    logic [CFG_RRESP_O_W-1:0] cfg_rresp_o;  // output [1:0]
    logic intr_o;  // output

    clocking drv_cb @(posedge clk_i);
        default input #1step output #1step;
        output cfg_awvalid_i;
        output cfg_awaddr_i;
        output cfg_wvalid_i;
        output cfg_wdata_i;
        output cfg_wstrb_i;
        output cfg_bready_i;
        output cfg_arvalid_i;
        output cfg_araddr_i;
        output cfg_rready_i;
        input cfg_awready_o;
        input cfg_wready_o;
        input cfg_bvalid_o;
        input cfg_bresp_o;
        input cfg_arready_o;
        input cfg_rvalid_o;
        input cfg_rdata_o;
        input cfg_rresp_o;
        input intr_o;
    endclocking

    clocking mon_cb @(posedge clk_i);
        default input #1step;
        input cfg_awvalid_i;
        input cfg_awaddr_i;
        input cfg_wvalid_i;
        input cfg_wdata_i;
        input cfg_wstrb_i;
        input cfg_bready_i;
        input cfg_arvalid_i;
        input cfg_araddr_i;
        input cfg_rready_i;
        input cfg_awready_o;
        input cfg_wready_o;
        input cfg_bvalid_o;
        input cfg_bresp_o;
        input cfg_arready_o;
        input cfg_rvalid_o;
        input cfg_rdata_o;
        input cfg_rresp_o;
        input intr_o;
    endclocking

    modport DRIVER (clocking drv_cb, input clk_i, output rst_i);
    modport MONITOR (clocking mon_cb, input clk_i, input rst_i);

endinterface : usbh_host_axi4_if
 
