//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------
`timescale 1ns/1ps

`include "usbh_host_pkg.sv"
import usbh_host_pkg::*;
 // Interface: usbh_host_utmi_if
 // Bundles the "utmi" signal group (13 signal(s)),
 // auto-classified by AMBA naming convention (or user-assigned in the
 // grouping step). Port widths come from usbh_host_pkg parameters
 // (the package is `included AND imported so width parameters such as
 // UTMI_DATA_IN_I_W resolve here).
interface usbh_host_utmi_if (
    input logic clk_i
);

    logic rst_i;

    logic [UTMI_DATA_IN_I_W-1:0] utmi_data_in_i;  // input [7:0]
    logic utmi_txready_i;  // input
    logic utmi_rxvalid_i;  // input
    logic utmi_rxactive_i;  // input
    logic utmi_rxerror_i;  // input
    logic [UTMI_LINESTATE_I_W-1:0] utmi_linestate_i;  // input [1:0]
    logic [UTMI_DATA_OUT_O_W-1:0] utmi_data_out_o;  // output [7:0]
    logic utmi_txvalid_o;  // output
    logic [UTMI_OP_MODE_O_W-1:0] utmi_op_mode_o;  // output [1:0]
    logic [UTMI_XCVRSELECT_O_W-1:0] utmi_xcvrselect_o;  // output [1:0]
    logic utmi_termselect_o;  // output
    logic utmi_dppulldown_o;  // output
    logic utmi_dmpulldown_o;  // output

    clocking drv_cb @(posedge clk_i);
        default input #1step output #1step;
        output utmi_data_in_i;
        output utmi_txready_i;
        output utmi_rxvalid_i;
        output utmi_rxactive_i;
        output utmi_rxerror_i;
        output utmi_linestate_i;
        input utmi_data_out_o;
        input utmi_txvalid_o;
        input utmi_op_mode_o;
        input utmi_xcvrselect_o;
        input utmi_termselect_o;
        input utmi_dppulldown_o;
        input utmi_dmpulldown_o;
    endclocking

    clocking mon_cb @(posedge clk_i);
        default input #1step;
        input utmi_data_in_i;
        input utmi_txready_i;
        input utmi_rxvalid_i;
        input utmi_rxactive_i;
        input utmi_rxerror_i;
        input utmi_linestate_i;
        input utmi_data_out_o;
        input utmi_txvalid_o;
        input utmi_op_mode_o;
        input utmi_xcvrselect_o;
        input utmi_termselect_o;
        input utmi_dppulldown_o;
        input utmi_dmpulldown_o;
    endclocking

    //modport DRIVER (clocking drv_cb, input clk_i, output rst_i);
    modport DRIVER (clocking drv_cb, input clk_i, input rst_i);
    modport MONITOR (clocking mon_cb, input clk_i, input rst_i);

endinterface : usbh_host_utmi_if
 
