
//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


 // Package: usbh_host_pkg
 // Captures every DUT top-level signal port as a width parameter.
 // UVM imports are outside the package for universal include.
 `timescale 1ns/1ps
 
 `ifndef USBH_HOST_PKG_SV
 `define USBH_HOST_PKG_SV
 `include "uvm_macros.svh"
 import uvm_pkg::*;
 package usbh_host_pkg;

   // ---- DUT clock / reset configuration (global defaults) ----
   parameter string CLK_NAME       = "clk_i";
   parameter string RST_NAME       = "rst_i";
   parameter bit    RST_ACTIVE_LOW = 0;

   // ---- Per-interface clock / reset configuration ----
   parameter string AXI4_CLK = "clk_i";
  parameter string AXI4_RST = "rst_i";
  parameter bit    AXI4_RST_ACTIVE_LOW = 0;
  parameter string UTMI_CLK = "clk_i";
  parameter string UTMI_RST = "rst_i";
  parameter bit    UTMI_RST_ACTIVE_LOW = 0;

   // ---- DUT top-level signal port parameters ----
   parameter int CLK_I_W = 1;  // input 
  parameter int RST_I_W = 1;  // input 
  parameter int CFG_AWVALID_I_W = 1;  // input 
  parameter int CFG_AWADDR_I_W = 32;  // input [31:0]
  parameter int CFG_WVALID_I_W = 1;  // input 
  parameter int CFG_WDATA_I_W = 32;  // input [31:0]
  parameter int CFG_WSTRB_I_W = 4;  // input [3:0]
  parameter int CFG_BREADY_I_W = 1;  // input 
  parameter int CFG_ARVALID_I_W = 1;  // input 
  parameter int CFG_ARADDR_I_W = 32;  // input [31:0]
  parameter int CFG_RREADY_I_W = 1;  // input 
  parameter int UTMI_DATA_IN_I_W = 8;  // input [7:0]
  parameter int UTMI_TXREADY_I_W = 1;  // input 
  parameter int UTMI_RXVALID_I_W = 1;  // input 
  parameter int UTMI_RXACTIVE_I_W = 1;  // input 
  parameter int UTMI_RXERROR_I_W = 1;  // input 
  parameter int UTMI_LINESTATE_I_W = 2;  // input [1:0]
  parameter int CFG_AWREADY_O_W = 1;  // output 
  parameter int CFG_WREADY_O_W = 1;  // output 
  parameter int CFG_BVALID_O_W = 1;  // output 
  parameter int CFG_BRESP_O_W = 2;  // output [1:0]
  parameter int CFG_ARREADY_O_W = 1;  // output 
  parameter int CFG_RVALID_O_W = 1;  // output 
  parameter int CFG_RDATA_O_W = 32;  // output [31:0]
  parameter int CFG_RRESP_O_W = 2;  // output [1:0]
  parameter int INTR_O_W = 1;  // output 
  parameter int UTMI_DATA_OUT_O_W = 8;  // output [7:0]
  parameter int UTMI_TXVALID_O_W = 1;  // output 
  parameter int UTMI_OP_MODE_O_W = 2;  // output [1:0]
  parameter int UTMI_XCVRSELECT_O_W = 2;  // output [1:0]
  parameter int UTMI_TERMSELECT_O_W = 1;  // output 
  parameter int UTMI_DPPULLDOWN_O_W = 1;  // output 
  parameter int UTMI_DMPULLDOWN_O_W = 1;  // output 

 endpackage : usbh_host_pkg
 `endif
 
