//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Monitor for agent "axi_agent" -- observes interface group "AXI".
class lpddr5c_axi_agent_monitor extends uvm_monitor;

  `uvm_component_utils(lpddr5c_axi_agent_monitor)

  virtual lpddr5c_AXI_if vif;
  uvm_analysis_port #(lpddr5c_axi_agent_seq_item) ap;

  function new(string name = "lpddr5c_axi_agent_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    ap = new("ap", this);
    if (!uvm_resource_db#(virtual lpddr5c_AXI_if)::read_by_name(
            get_full_name(), "vif", vif, this))
      `uvm_fatal("NOVIF", $sformatf("[%s] Virtual interface not found in resource_db", get_full_name()))
  endfunction

  task run_phase(uvm_phase phase);
    lpddr5c_axi_agent_seq_item item;
    forever begin
      @(vif.mon_cb);
      item = lpddr5c_axi_agent_seq_item::type_id::create("item");
      item.axi_awvalid = vif.mon_cb.axi_awvalid;
      item.axi_awready = vif.mon_cb.axi_awready;
      item.axi_awaddr = vif.mon_cb.axi_awaddr;
      item.axi_awlen = vif.mon_cb.axi_awlen;
      item.axi_awsize = vif.mon_cb.axi_awsize;
      item.axi_awburst = vif.mon_cb.axi_awburst;
      item.axi_wvalid = vif.mon_cb.axi_wvalid;
      item.axi_wready = vif.mon_cb.axi_wready;
      item.axi_wdata = vif.mon_cb.axi_wdata;
      item.axi_wstrb = vif.mon_cb.axi_wstrb;
      item.axi_wlast = vif.mon_cb.axi_wlast;
      item.axi_bvalid = vif.mon_cb.axi_bvalid;
      item.axi_bready = vif.mon_cb.axi_bready;
      item.axi_bresp = vif.mon_cb.axi_bresp;
      item.axi_arvalid = vif.mon_cb.axi_arvalid;
      item.axi_arready = vif.mon_cb.axi_arready;
      item.axi_araddr = vif.mon_cb.axi_araddr;
      item.axi_arlen = vif.mon_cb.axi_arlen;
      item.axi_arsize = vif.mon_cb.axi_arsize;
      item.axi_arburst = vif.mon_cb.axi_arburst;
      item.axi_rvalid = vif.mon_cb.axi_rvalid;
      item.axi_rready = vif.mon_cb.axi_rready;
      item.axi_rdata = vif.mon_cb.axi_rdata;
      item.axi_rresp = vif.mon_cb.axi_rresp;
      item.axi_rlast = vif.mon_cb.axi_rlast;
      // TODO: gate on a valid/done condition specific to "AXI".
      ap.write(item);
    end
  endtask

endclass : lpddr5c_axi_agent_monitor
