//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Sequencer for agent "axi_agent"
typedef uvm_sequencer #(lpddr5c_axi_agent_seq_item) lpddr5c_axi_agent_sequencer;
