//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Functional coverage collector for agent "axi_agent" (interface group
// "AXI"). Implemented as a uvm_subscriber so it plugs
// directly into the monitor's existing analysis port (ap.connect) with
// no extra TLM export declarations needed.
class lpddr5c_axi_agent_coverage extends uvm_subscriber #(lpddr5c_axi_agent_seq_item);

  `uvm_component_utils(lpddr5c_axi_agent_coverage)

  lpddr5c_axi_agent_seq_item item;

  covergroup cg_axi_agent;
    option.per_instance = 1;
    option.name = $sformatf("%s_cg_axi_agent", get_full_name());
    cp_axi_awvalid: coverpoint item.axi_awvalid;  // 1-bit -- auto bins (0/1)
    cp_axi_awready: coverpoint item.axi_awready;  // 1-bit -- auto bins (0/1)
    cp_axi_awaddr: coverpoint item.axi_awaddr;  // 1-bit -- auto bins (0/1)
    cp_axi_awlen: coverpoint item.axi_awlen;  // <=8b -- auto bins
    cp_axi_awsize: coverpoint item.axi_awsize;  // <=8b -- auto bins
    cp_axi_awburst: coverpoint item.axi_awburst;  // <=8b -- auto bins
    cp_axi_wvalid: coverpoint item.axi_wvalid;  // 1-bit -- auto bins (0/1)
    cp_axi_wready: coverpoint item.axi_wready;  // 1-bit -- auto bins (0/1)
    cp_axi_wdata: coverpoint item.axi_wdata;  // 1-bit -- auto bins (0/1)
    cp_axi_wstrb: coverpoint item.axi_wstrb;  // 1-bit -- auto bins (0/1)
    cp_axi_wlast: coverpoint item.axi_wlast;  // 1-bit -- auto bins (0/1)
    cp_axi_bvalid: coverpoint item.axi_bvalid;  // 1-bit -- auto bins (0/1)
    cp_axi_bready: coverpoint item.axi_bready;  // 1-bit -- auto bins (0/1)
    cp_axi_bresp: coverpoint item.axi_bresp;  // <=8b -- auto bins
    cp_axi_arvalid: coverpoint item.axi_arvalid;  // 1-bit -- auto bins (0/1)
    cp_axi_arready: coverpoint item.axi_arready;  // 1-bit -- auto bins (0/1)
    cp_axi_araddr: coverpoint item.axi_araddr;  // 1-bit -- auto bins (0/1)
    cp_axi_arlen: coverpoint item.axi_arlen;  // <=8b -- auto bins
    cp_axi_arsize: coverpoint item.axi_arsize;  // <=8b -- auto bins
    cp_axi_arburst: coverpoint item.axi_arburst;  // <=8b -- auto bins
    cp_axi_rvalid: coverpoint item.axi_rvalid;  // 1-bit -- auto bins (0/1)
    cp_axi_rready: coverpoint item.axi_rready;  // 1-bit -- auto bins (0/1)
    cp_axi_rdata: coverpoint item.axi_rdata;  // 1-bit -- auto bins (0/1)
    cp_axi_rresp: coverpoint item.axi_rresp;  // <=8b -- auto bins
    cp_axi_rlast: coverpoint item.axi_rlast;  // 1-bit -- auto bins (0/1)
    cx_axi_awvalid_axi_awready: cross cp_axi_awvalid, cp_axi_awready;  // TODO: prune/expand as needed

  endgroup

  function new(string name = "lpddr5c_axi_agent_coverage", uvm_component parent = null);
    super.new(name, parent);
    cg_axi_agent = new();
  endfunction

  function void write(lpddr5c_axi_agent_seq_item t);
    item = t;
    cg_axi_agent.sample();
  endfunction

  function void report_phase(uvm_phase phase);
    super.report_phase(phase);
    `uvm_info("COV", $sformatf("[%s] Coverage = %0.2f%%", get_full_name(),
              cg_axi_agent.get_coverage()), UVM_LOW)
  endfunction

endclass : lpddr5c_axi_agent_coverage
