//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------
`include "uvm_macros.svh"
import uvm_pkg::*;

// Sequence item for agent "axi_agent" (bound to interface group "AXI").
class lpddr5c_axi_agent_seq_item extends uvm_sequence_item;

  rand bit axi_awvalid;
       bit axi_awready;
  rand bit [31:0]axi_awaddr;
  rand bit [7:0] axi_awlen;
  rand bit [2:0] axi_awsize;
  rand bit [1:0] axi_awburst;
  rand bit axi_wvalid;
       bit axi_wready;
  rand bit [127:0] axi_wdata;
  rand bit axi_wstrb;
  rand bit axi_wlast;
       bit axi_bvalid;
  rand bit axi_bready;
       bit [1:0] axi_bresp;
  rand bit axi_arvalid;
       bit axi_arready;
  rand bit [31:0]axi_araddr;
  rand bit [7:0] axi_arlen;
  rand bit [2:0] axi_arsize;
  rand bit [1:0] axi_arburst;
       bit axi_rvalid;
  rand bit axi_rready;
       bit [127:0]axi_rdata;
       bit [1:0] axi_rresp;
       bit axi_rlast;
       bit is_write;
       
    `uvm_object_utils(lpddr5c_axi_agent_seq_item)

 /* `uvm_object_utils_begin(lpddr5c_axi_agent_seq_item)
    `uvm_field_int(axi_awvalid, UVM_ALL_ON)
    `uvm_field_int(axi_awready, UVM_ALL_ON)
    `uvm_field_int(axi_awaddr, UVM_ALL_ON)
    `uvm_field_int(axi_awlen, UVM_ALL_ON)
    `uvm_field_int(axi_awsize, UVM_ALL_ON)
    `uvm_field_int(axi_awburst, UVM_ALL_ON)
    `uvm_field_int(axi_wvalid, UVM_ALL_ON)
    `uvm_field_int(axi_wready, UVM_ALL_ON)
    `uvm_field_int(axi_wdata, UVM_ALL_ON)
    `uvm_field_int(axi_wstrb, UVM_ALL_ON)
    `uvm_field_int(axi_wlast, UVM_ALL_ON)
    `uvm_field_int(axi_bvalid, UVM_ALL_ON)
    `uvm_field_int(axi_bready, UVM_ALL_ON)
    `uvm_field_int(axi_bresp, UVM_ALL_ON)
    `uvm_field_int(axi_arvalid, UVM_ALL_ON)
    `uvm_field_int(axi_arready, UVM_ALL_ON)
    `uvm_field_int(axi_araddr, UVM_ALL_ON)
    `uvm_field_int(axi_arlen, UVM_ALL_ON)
    `uvm_field_int(axi_arsize, UVM_ALL_ON)
    `uvm_field_int(axi_arburst, UVM_ALL_ON)
    `uvm_field_int(axi_rvalid, UVM_ALL_ON)
    `uvm_field_int(axi_rready, UVM_ALL_ON)
    `uvm_field_int(axi_rdata, UVM_ALL_ON)
    `uvm_field_int(axi_rresp, UVM_ALL_ON)
    `uvm_field_int(axi_rlast, UVM_ALL_ON)
  `uvm_object_utils_end */

  function new(string name = "lpddr5c_axi_agent_seq_item");
    super.new(name);
  endfunction

  constraint c_default {
    // TODO: add constraints specific to agent "axi_agent"
  }

endclass : lpddr5c_axi_agent_seq_item
