//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Driver for agent "axi4_agent" -- drives interface group "axi4".
class usbh_host_axi4_agent_driver extends uvm_driver #(usbh_host_axi4_agent_seq_item);

  `uvm_component_utils(usbh_host_axi4_agent_driver)

  virtual usbh_host_axi4_if vif;

  function new(string name = "usbh_host_axi4_agent_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_resource_db#(virtual usbh_host_axi4_if)::read_by_name(
            get_full_name(), "vif", vif, this))
      `uvm_fatal("NOVIF", $sformatf("[%s] Virtual interface not found in resource_db", get_full_name()))
  endfunction



  task run_phase(uvm_phase phase);
      
      // Wait for reset to be deasserted before accepting AXI items
     /* `uvm_info(get_type_name(), "Waiting for reset deassertion", UVM_MEDIUM)
      wait (vif.rst_i === 1'b1);
      `uvm_info("AXI_DRV", "Reset deasserted -- driver resuming", UVM_MEDIUM)*/
           
    forever begin
	      // Reset is input -- when asserted (rst_i==0) hold driver in reset
	      fork
	      if (vif.rst_i === 1'b1) begin
		do_reset();
		@(posedge vif.clk_i);
		wait (vif.rst_i === 1'b0);
		`uvm_info("AXI_DRV", "Reset deasserted -- driver resuming", UVM_MEDIUM)
	      end
	      join
	      // When reset not applied (rst_i==1) continue normal drive
	      `uvm_info("AXI_DRV", "Waiting for AXI sequence item", UVM_LOW)
	      seq_item_port.get_next_item(req);
	      `uvm_info("AXI_DRV", "Got AXI sequence item", UVM_LOW)
	      drive_item(req);
	      seq_item_port.item_done();
    end
  endtask



  task do_reset();
    // Drive interface to reset/idle state while reset is applied
    @(vif.drv_cb);
    // TODO: drive reset defaults for axi4 (e.g., valid->0)
    vif.drv_cb.cfg_awvalid_i <= 1'b0;
      vif.drv_cb.cfg_awaddr_i <= '0;
      vif.drv_cb.cfg_wvalid_i <= 1'b0;
      vif.drv_cb.cfg_wdata_i <= '0;
      vif.drv_cb.cfg_wstrb_i <= '0;
      vif.drv_cb.cfg_bready_i <= 1'b0;
      vif.drv_cb.cfg_arvalid_i <= 1'b0;
      vif.drv_cb.cfg_araddr_i <= '0;
      vif.drv_cb.cfg_rready_i <= 1'b0;
    
  endtask

  task drive_item(usbh_host_axi4_agent_seq_item req);
      if (req.write) 
          drive_write(req); 
      else 
          drive_read(req);
  endtask
  
  //============================================================= // WRITE transaction //=============================================================
  task drive_write(usbh_host_axi4_agent_seq_item req);
      int timeout;
      timeout = 0;
  
      `uvm_info("AXI4_DRV", $sformatf("WRITE ADDR=%08h DATA=%08h STRB=%h", req.addr, req.data, req.strb), UVM_MEDIUM)
      //------------------ 1. WRITE ADDRESS CHANNEL --------------------------------
      vif.drv_cb.cfg_awaddr_i <= req.addr; 
      vif.drv_cb.cfg_awvalid_i <= 1'b1; 
      `uvm_info("AXI_DRV", "AWVALID is asserted , Waiting for AWREADY", UVM_MEDIUM)
      // Wait for AWREADY 
      do begin 
          @(vif.drv_cb); 
      end 
      while (!vif.drv_cb.cfg_awready_o); 
      `uvm_info("AXI_DRV", "AW handshake completed", UVM_MEDIUM)
      // AW handshake completed 
      vif.drv_cb.cfg_awvalid_i <= 1'b0;
      //------------------ 2. WRITE DATA CHANNEL -----------------------------------
      vif.drv_cb.cfg_wdata_i <= req.data; 
      vif.drv_cb.cfg_wstrb_i <= req.strb; 
      vif.drv_cb.cfg_wvalid_i <= 1'b1; 
      `uvm_info("AXI_DRV", "Asserted WVALID", UVM_MEDIUM)
      `uvm_info("AXI_DRV", "Waiting for WREADY", UVM_MEDIUM)
      // Wait for WREADY
      /*timeout = 0;
      while(!vif.drv_cb.cfg_wready_o) begin
          @(vif.drv_cb);
          timeout++;
          if(timeout == 1000) begin
              `uvm_fatal("AXI_TIMEOUT", $sformatf( "WREADY timeout: ADDR=%08h WVALID=1 rst_i=%b", req.addr, vif.rst_i))
          end
      end*/
      `uvm_info("AXI_DRV", "W handshake completed", UVM_MEDIUM)
       
      do begin 
          @(vif.drv_cb); 
      end 
      while (!vif.drv_cb.cfg_wready_o); 
      
      // W handshake completed 
      vif.drv_cb.cfg_wvalid_i <= 1'b0;
      
      //------------------ 3. WRITE RESPONSE CHANNEL --------------------------------
      vif.drv_cb.cfg_bready_i <= 1'b1; 
      // Wait for BVALID 
      `uvm_info("AXI_DRV", "Waiting for BVALID", UVM_MEDIUM)
      timeout = 0;
      while(!vif.drv_cb.cfg_bvalid_o) begin
          @(vif.drv_cb);
          timeout++;
          if(timeout == 1000) begin
              `uvm_fatal("AXI_TIMEOUT", $sformatf( "BVALID timeout: ADDR=%08h WVALID=1 rst_i=%b", req.addr, vif.rst_i))
          end
      end
      /*do begin 
          @(vif.drv_cb); 
      end 
      while (!vif.drv_cb.cfg_bvalid_o); */
      // Capture write response 
      req.resp = vif.drv_cb.cfg_bresp_o;
      `uvm_info("AXI_DRV", "B handshake completed", UVM_MEDIUM) // B handshake completed       
      vif.drv_cb.cfg_bready_i <= 1'b0;      
      `uvm_info("AXI4_DRV", $sformatf("WRITE COMPLETE ADDR=%08h DATA=%08h STRB=%0b RESP=%0d", req.addr, req.data, req.strb, req.resp), UVM_MEDIUM)       
  endtask
  //============================================================= // READ transaction //=============================================================
  task drive_read(usbh_host_axi4_agent_seq_item req);
      `uvm_info("AXI4_DRV", $sformatf("READ ADDR=%08h", req.addr), UVM_MEDIUM)
      //-------------------- 1. READ ADDRESS CHANNEL ----------------------------------
      vif.drv_cb.cfg_araddr_i <= req.addr; 
      vif.drv_cb.cfg_arvalid_i <= 1'b1; 
      // Wait for ARREADY 
      do begin 
          @(vif.drv_cb); 
      end while (!vif.drv_cb.cfg_arready_o); 
      // AR handshake completed 
      vif.drv_cb.cfg_arvalid_i <= 1'b0;
      //-------------------- 2. READ DATA CHANNEL -------------------------------------
      vif.drv_cb.cfg_rready_i <= 1'b1; 
      // Wait for RVALID 
      do begin 
          @(vif.drv_cb); 
      end while (!vif.drv_cb.cfg_rvalid_o); 
      // Capture read response 
      req.rdata = vif.drv_cb.cfg_rdata_o; 
      req.resp = vif.drv_cb.cfg_rresp_o; 
      // R handshake completed 
      vif.drv_cb.cfg_rready_i <= 1'b0;
      
      `uvm_info("AXI4_DRV", $sformatf("READ COMPLETE ADDR=%08h RDATA=%08h RESP=%0d", req.addr, req.rdata, req.resp), UVM_MEDIUM) 
  endtask
  
endclass : usbh_host_axi4_agent_driver


