//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Sequence item for agent "axi4_agent" (bound to interface group "axi4").
class usbh_host_axi4_agent_seq_item extends uvm_sequence_item;

  	rand bit write; // Transaction type
	rand bit [31:0] addr; // Write / Read address
	rand bit [31:0] data; // Write data
	rand bit [ 3:0] strb; // Write strobe
	bit [31:0] rdata; // Response / Read data 
	bit [ 1:0] resp; // These are filled by the driver/monitor	

  `uvm_object_utils_begin(usbh_host_axi4_agent_seq_item)
    `uvm_field_int(write, UVM_ALL_ON)
    `uvm_field_int(addr, UVM_ALL_ON)
    `uvm_field_int(data, UVM_ALL_ON)
    `uvm_field_int(strb, UVM_ALL_ON)
    `uvm_field_int(rdata, UVM_ALL_ON)
    `uvm_field_int(resp, UVM_ALL_ON)
  `uvm_object_utils_end

  function new(string name = "usbh_host_axi4_agent_seq_item");
    super.new(name);
  endfunction

  	
	//=============================================================
	//Read / Write weighted constraint
	constraint write_c {
	    write dist {
		1'b0 := 40,
		1'b1 := 60
	    };
	}	
	//=============================================================
	// Address constraint
	constraint addr_c {
		addr inside {
			32'h00000000, // USB_CTRL
			32'h00000004, // USB_STATUS
			32'h00000008, // USB_IRQ_ACK
			32'h0000000C, // USB_IRQ_STS
			32'h00000010, // USB_IRQ_MASK
			32'h00000014, // USB_XFER_DATA
			32'h00000018, // USB_XFER_TOKEN
			32'h0000001C, // USB_RX_STAT
			32'h00000020  // USB_WR_DATA / USB_RD_DATA
		    };
	}
	
	//=============================================================
        // Write strobe constraint
        //=============================================================
	constraint strb_c {
	    strb == 4'b1111;
	}
	//=============================================================
	// Read / Write access constraint
	//=============================================================
	    // Read-only registers:
	    //
	    // USB_STATUS   = 0x04
	    // USB_IRQ_STS  = 0x0C
	    // USB_RX_STAT  = 0x1C
	    //
	    // Address 0x20:
	    //     WRITE -> USB_WR_DATA
	    //     READ  -> USB_RD_DATA
	    //
	constraint access_c {
		if(!write) {
			addr inside {
				32'h04,   //USB_STATUS
				32'h0C,   //USB_IRQ_STS
				32'h1C,   //USB_RX_STAT
				32'h20    //USB_RD_DATA
			};
		}
		else {
			addr inside {
				32'h00,   //USB_CTRL
				32'h08,   //USB_IRQ_ACK
				32'h10,   //USB_IRQ_MASK
				32'h14,   //USB_XFER_DATA
				32'h18,   //USB_XFER_TOKEN
				32'h20    //USB_WR_DATA
			};
		}
	}
	//=============================================================
        // Write data constraints
        //=============================================================
        // Only defined bits should be randomized.
        // Reserved bits are kept at 0.
	constraint data_c {
	    if (!write)
		data == 32'b0;
	    // USB_CTRL : 0x00
		        //
		        // [8]    TX_FLUSH
		        // [7]    PHY_DMPULLDOWN
		        // [6]    PHY_DPPULLDOWN
		        // [5]    PHY_TERMSELECT
		        // [4:3] PHY_XCVRSELECT
		        // [2:1] PHY_OPMODE
		        // [0]    ENABLE_SOF
	    else if (addr == 32'h00000000)
		data[31:9] == 23'b0;
		
	    // USB_IRQ_ACK : 0x08
		        //
		        // [3] DEVICE_DETECT
		        // [2] ERR
		        // [1] DONE
		        // [0] SOF
	    else if (addr == 32'h00000008)
		data[31:4] == 28'b0;
		
	    // USB_XFER_DATA : 0x14
		        //
		        // [15:0] TX_LEN
	    else if (addr == 32'h00000014)
		data[31:16] == 16'b0;
	    
	    // USB_XFER_TOKEN : 0x18
		        //
		        // [31]    START
		        // [30]    IN
		        // [29]    ACK
		        // [28]    PID_DATAX
		        // [27:24] reserved
		        // [23:16] PID_BITS
		        // [15:9]  DEV_ADDR
		        // [8:5]   EP_ADDR
		        // [4:0]   reserved
	    else if (addr == 32'h00000018) {
		data[27:24] == 4'b0;
		data[4:0]   == 5'b0;
	    }
	    
	    // USB_WR_DATA : 0x20
	    // [7:0] DATA
	    else if (addr == 32'h00000020)
		data[31:8] == 24'b0;
		
	     //For READ transaction, write data is irrelevant.
	    else
		data == 32'b0;
	}


endclass : usbh_host_axi4_agent_seq_item
