//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Agent "axi4_agent" -- unique agent shell bound to interface group
// "axi4". Active/passive mode is set by tests/base_test.sv
// via uvm_resource_db, scoped by this agent's instance name.
class usbh_host_axi4_agent extends uvm_agent;

  `uvm_component_utils(usbh_host_axi4_agent)

  usbh_host_axi4_agent_driver    driver;
  usbh_host_axi4_agent_sequencer sequencer;
  usbh_host_axi4_agent_monitor   monitor;
  virtual usbh_host_axi4_if         vif;

  function new(string name = "usbh_host_axi4_agent", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    uvm_active_passive_enum mode;
    super.build_phase(phase);

    if (!uvm_resource_db#(virtual usbh_host_axi4_if)::read_by_name(
            get_full_name(), "vif", vif, this))
      `uvm_fatal("NOVIF", $sformatf("[%s] Virtual interface not found in resource_db", get_full_name()))

    if (!uvm_resource_db#(uvm_active_passive_enum)::read_by_name(
            get_full_name(), "is_active", mode, this)) begin
      `uvm_warning("NOMODE", $sformatf(
          "[%s] No is_active resource found from test -- defaulting to UVM_PASSIVE",
          get_full_name()))
      mode = UVM_PASSIVE;
    end
    is_active = mode;

    uvm_resource_db#(virtual usbh_host_axi4_if)::set(
        {get_full_name(), ".*"}, "vif", vif, this);

    monitor = usbh_host_axi4_agent_monitor::type_id::create("monitor", this);

    if (is_active == UVM_ACTIVE) begin
      driver    = usbh_host_axi4_agent_driver::type_id::create("driver", this);
      sequencer = usbh_host_axi4_agent_sequencer::type_id::create("sequencer", this);
    end
  endfunction

  function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    if (is_active == UVM_ACTIVE)
      driver.seq_item_port.connect(sequencer.seq_item_export);
  endfunction

endclass : usbh_host_axi4_agent
