//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Functional coverage collector for agent "axi4_agent" (interface group
// "axi4"). Implemented as a uvm_subscriber so it plugs
// directly into the monitor's existing analysis port (ap.connect) with
// no extra TLM export declarations needed.
class usbh_host_axi4_agent_coverage extends uvm_subscriber #(usbh_host_axi4_agent_seq_item);

  `uvm_component_utils(usbh_host_axi4_agent_coverage)

  usbh_host_axi4_agent_seq_item item;

  covergroup cg_axi4_agent;
    option.per_instance = 1;
    option.name = $sformatf("%s_cg_axi4_agent", get_full_name());
    cp_cfg_awvalid_i: coverpoint item.cfg_awvalid_i;  // 1-bit -- auto bins (0/1)
    cp_cfg_awaddr_i: coverpoint item.cfg_awaddr_i {
      bins zero    = {0};
      bins nonzero = {[1:$]};
      // TODO: replace with meaningful range/boundary bins for 'cfg_awaddr_i'
    }
    cp_cfg_wvalid_i: coverpoint item.cfg_wvalid_i;  // 1-bit -- auto bins (0/1)
    cp_cfg_wdata_i: coverpoint item.cfg_wdata_i {
      bins zero    = {0};
      bins nonzero = {[1:$]};
      // TODO: replace with meaningful range/boundary bins for 'cfg_wdata_i'
    }
    cp_cfg_wstrb_i: coverpoint item.cfg_wstrb_i;  // <=8b -- auto bins
    cp_cfg_bready_i: coverpoint item.cfg_bready_i;  // 1-bit -- auto bins (0/1)
    cp_cfg_arvalid_i: coverpoint item.cfg_arvalid_i;  // 1-bit -- auto bins (0/1)
    cp_cfg_araddr_i: coverpoint item.cfg_araddr_i {
      bins zero    = {0};
      bins nonzero = {[1:$]};
      // TODO: replace with meaningful range/boundary bins for 'cfg_araddr_i'
    }
    cp_cfg_rready_i: coverpoint item.cfg_rready_i;  // 1-bit -- auto bins (0/1)
    cp_cfg_awready_o: coverpoint item.cfg_awready_o;  // 1-bit -- auto bins (0/1)
    cp_cfg_wready_o: coverpoint item.cfg_wready_o;  // 1-bit -- auto bins (0/1)
    cp_cfg_bvalid_o: coverpoint item.cfg_bvalid_o;  // 1-bit -- auto bins (0/1)
    cp_cfg_bresp_o: coverpoint item.cfg_bresp_o;  // <=8b -- auto bins
    cp_cfg_arready_o: coverpoint item.cfg_arready_o;  // 1-bit -- auto bins (0/1)
    cp_cfg_rvalid_o: coverpoint item.cfg_rvalid_o;  // 1-bit -- auto bins (0/1)
    cp_cfg_rdata_o: coverpoint item.cfg_rdata_o {
      bins zero    = {0};
      bins nonzero = {[1:$]};
      // TODO: replace with meaningful range/boundary bins for 'cfg_rdata_o'
    }
    cp_cfg_rresp_o: coverpoint item.cfg_rresp_o;  // <=8b -- auto bins
    cp_intr_o: coverpoint item.intr_o;  // 1-bit -- auto bins (0/1)
    cx_cfg_awvalid_i_cfg_awaddr_i: cross cp_cfg_awvalid_i, cp_cfg_awaddr_i;  // TODO: prune/expand as needed

  endgroup

  function new(string name = "usbh_host_axi4_agent_coverage", uvm_component parent = null);
    super.new(name, parent);
    cg_axi4_agent = new();
  endfunction

  function void write(usbh_host_axi4_agent_seq_item t);
    item = t;
    cg_axi4_agent.sample();
  endfunction

  function void report_phase(uvm_phase phase);
    super.report_phase(phase);
    `uvm_info("COV", $sformatf("[%s] Coverage = %0.2f%%", get_full_name(),
              cg_axi4_agent.get_coverage()), UVM_LOW)
  endfunction

endclass : usbh_host_axi4_agent_coverage
