//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Monitor for agent "axi4_agent" -- observes interface group "axi4".
class usbh_host_axi4_agent_monitor extends uvm_monitor;

  `uvm_component_utils(usbh_host_axi4_agent_monitor)

  virtual usbh_host_axi4_if vif;
  uvm_analysis_port #(usbh_host_axi4_agent_seq_item) ap;

  function new(string name = "usbh_host_axi4_agent_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    ap = new("ap", this);
    if (!uvm_resource_db#(virtual usbh_host_axi4_if)::read_by_name(
            get_full_name(), "vif", vif, this))
      `uvm_fatal("NOVIF", $sformatf("[%s] Virtual interface not found in resource_db", get_full_name()))
  endfunction

  /*task run_phase(uvm_phase phase);
    usbh_host_axi4_agent_seq_item item;
    forever begin
      @(vif.mon_cb);
      item = usbh_host_axi4_agent_seq_item::type_id::create("item");
      item.cfg_awvalid_i = vif.mon_cb.cfg_awvalid_i;
      item.cfg_awaddr_i = vif.mon_cb.cfg_awaddr_i;
      item.cfg_wvalid_i = vif.mon_cb.cfg_wvalid_i;
      item.cfg_wdata_i = vif.mon_cb.cfg_wdata_i;
      item.cfg_wstrb_i = vif.mon_cb.cfg_wstrb_i;
      item.cfg_bready_i = vif.mon_cb.cfg_bready_i;
      item.cfg_arvalid_i = vif.mon_cb.cfg_arvalid_i;
      item.cfg_araddr_i = vif.mon_cb.cfg_araddr_i;
      item.cfg_rready_i = vif.mon_cb.cfg_rready_i;
      item.cfg_awready_o = vif.mon_cb.cfg_awready_o;
      item.cfg_wready_o = vif.mon_cb.cfg_wready_o;
      item.cfg_bvalid_o = vif.mon_cb.cfg_bvalid_o;
      item.cfg_bresp_o = vif.mon_cb.cfg_bresp_o;
      item.cfg_arready_o = vif.mon_cb.cfg_arready_o;
      item.cfg_rvalid_o = vif.mon_cb.cfg_rvalid_o;
      item.cfg_rdata_o = vif.mon_cb.cfg_rdata_o;
      item.cfg_rresp_o = vif.mon_cb.cfg_rresp_o;
      item.intr_o = vif.mon_cb.intr_o;
      // TODO: gate on a valid/done condition specific to "axi4".
      ap.write(item);
    end
  endtask
  */

endclass : usbh_host_axi4_agent_monitor
