// ------------------------------------------------------------
// uart_scoreboard.sv
//
// Single scoreboard for the whole environment. Fed by BOTH
// d1_agent.monitor.analysis_port (-> write_d1) and
// d2_agent.monitor.analysis_port (-> write_d2), so it sees
// every APB transfer on either device regardless of which one
// is currently the RAL model's default_map target.
//
// Content checking (mode-agnostic):
//   * A THR write observed on d1  -> pushed to d1_to_d2_expected
//   * A RHR read  observed on d2  -> popped/checked against
//     d1_to_d2_expected
//   * A THR write observed on d2  -> pushed to d2_to_d1_expected
//   * A RHR read  observed on d1  -> popped/checked against
//     d2_to_d1_expected
// This works unchanged for all four uart_virtual_sequence modes
// (D1_TO_D2, D2_TO_D1, HALF_DUPLEX, FULL_DUPLEX): the scoreboard
// does not need to know which mode is running, only which
// device produced which event.
//
// Register-access visibility (d1 only, by construction -- the
// register regression sequences in uart_ral_sequences.sv only
// ever run while the RAL model's default_map is redirected to
// d1): any transfer that is not a THR write or RHR read
// is tallied as a register access rather than content-checked,
// since UVM's own mirror(UVM_CHECK) inside those sequences is
// what actually catches a mismatch there.
// ------------------------------------------------------------
`include "uvm_macros.svh"
import uvm_pkg::*;

class uart_scoreboard extends uvm_scoreboard;

    `uvm_component_utils(uart_scoreboard)

    `uvm_analysis_imp_decl(_d1)
    `uvm_analysis_imp_decl(_d2)

    uvm_analysis_imp_d1 #(uart_seq_item, uart_scoreboard) d1_imp;
    uvm_analysis_imp_d2 #(uart_seq_item, uart_scoreboard) d2_imp;

    bit [8:0] d1_to_d2_expected[$];
    bit [8:0] d2_to_d1_expected[$];

    int unsigned tx_d1_count, rx_d1_count;
    int unsigned tx_d2_count, rx_d2_count;
    int unsigned reg_access_d1_count;
    int unsigned pass_count, error_count;

   
    bit allow_empty_d1_to_d2_read = 1'b0;
    bit allow_empty_d2_to_d1_read = 1'b0;

    // SPEC_RX bypass: serial frames injected directly onto rx_i are
    // not generated by a TXDATA APB write, so they must not be
    // compared against the normal DUT-to-DUT expected queues.
    bit spec_rx_mode_active = 1'b0;

    // Suppress asynchronous pass prints during the FULL_DUPLEX read pair.
    // The virtual sequence prints each completed pair deterministically as
    // D1->D2 followed by D2->D1, while scoreboard comparisons/counters remain active.
    bit full_duplex_pair_log = 1'b0;

    localparam bit [31:0] ADDR_TXDATA = 32'h0000_0000;  // THR
    localparam bit [31:0] ADDR_RXDATA = 32'h0000_0004;  // RHR

    function new(string name = "uart_scoreboard", uvm_component parent = null);
        super.new(name, parent);
        d1_imp = new("d1_imp", this);
        d2_imp = new("d2_imp", this);
    endfunction

    // These helpers are reserved for DUT behaviors where a write is
    // intentionally accepted on APB but intentionally dropped inside
    // the DUT (for example TX-FIFO overflow or RX overrun).
    // A normal RX timeout must NEVER call them, because doing so would
    // hide missing DUT data.
    virtual function void discard_d1_to_d2_pending(bit intentional_drop = 1'b0);
        if (d1_to_d2_expected.size() > 0) begin
            void'(d1_to_d2_expected.pop_front());

            // The overflow test deliberately issues one extra APB TX write.
            // The DUT, not the testbench, rejects that byte because its FIFO
            // is full.  Remove only the matching expected item; no DUT data
            // is forced or removed here.
            if (!intentional_drop) begin
                error_count++;
                `uvm_error("UART_SB",
                    "Unexpected d1->d2 expected-entry discard requested; normal communication data must not be hidden")
            end
        end
    endfunction

    virtual function void discard_d2_to_d1_pending(bit intentional_drop = 1'b0);
        if (d2_to_d1_expected.size() > 0) begin
            void'(d2_to_d1_expected.pop_front());

            if (!intentional_drop) begin
                error_count++;
                `uvm_error("UART_SB",
                    "Unexpected d2->d1 expected-entry discard requested; normal communication data must not be hidden")
            end
        end
    endfunction

    // End-of-scenario isolation. A normal communication scenario must
    // consume every expected TX entry. If it does not, report it as a
    // real verification failure; never discard missing DUT data just
    // to make a scenario pass.
    virtual function void end_scenario_check(string scenario_name);
        int unsigned d1_pending;
        int unsigned d2_pending;

        d1_pending = d1_to_d2_expected.size();
        d2_pending = d2_to_d1_expected.size();

        if ((d1_pending != 0) || (d2_pending != 0)) begin
            error_count++;
            `uvm_error("UART_SB",
                $sformatf(
                    "%s left unmatched expected data: d1->d2=%0d d2->d1=%0d",
                    scenario_name, d1_pending, d2_pending
                ))
            d1_to_d2_expected.delete();
            d2_to_d1_expected.delete();
        end
    endfunction


    // ---------- d1-side events ----------
    virtual function void write_d1(uart_seq_item tr);
        if (tr.aborted_by_reset) return;

        if (tr.pwrite && tr.paddr == ADDR_TXDATA) begin
            d1_to_d2_expected.push_back(tr.pwdata[8:0]);
            tx_d1_count++;
            $display("  [SB] d1 sent 0x%03h (THR write) -> queued for d1->d2 check",
                      tr.pwdata[8:0]);
        end
        else if (!tr.pwrite && tr.paddr == ADDR_RXDATA) begin
            rx_d1_count++;
            if (spec_rx_mode_active) begin
                $display("  [SB] SPEC d1 RHR read observed: 0x%03h (content check bypassed)",
                         tr.prdata[8:0]);
            end else begin
                check_d2_to_d1(tr.prdata[8:0]);
            end
        end
        else begin
            reg_access_d1_count++;
        end
    endfunction

    // ---------- d2-side events ----------
    virtual function void write_d2(uart_seq_item tr);
        if (tr.aborted_by_reset) return;

        if (tr.pwrite && tr.paddr == ADDR_TXDATA) begin
            d2_to_d1_expected.push_back(tr.pwdata[8:0]);
            tx_d2_count++;
            $display("  [SB] d2 sent 0x%03h (THR write) -> queued for d2->d1 check",
                      tr.pwdata[8:0]);
        end
        else if (!tr.pwrite && tr.paddr == ADDR_RXDATA) begin
            rx_d2_count++;
            if (spec_rx_mode_active) begin
                $display("  [SB] SPEC d2 RHR read observed: 0x%03h (content check bypassed)",
                         tr.prdata[8:0]);
            end else begin
                check_d1_to_d2(tr.prdata[8:0]);
            end
        end
        else begin
            // d2 is not expected to run register-regression tests
            // (per the approved methodology, those are d1-only),
            // but d2's own BRDR/CR/IER config writes (issued via
            // the RAL, redirected to d2 -- see config_d2() in
            // uart_virtual_sequence.sv) still land here for
            // visibility.
        end
    endfunction

    // ---------- cross checks ----------
    virtual function void check_d1_to_d2(bit [8:0] actual);
        bit [8:0] expected;
        if (d1_to_d2_expected.size() == 0) begin
            if (allow_empty_d1_to_d2_read) begin
                `uvm_info("UART_SB",
                    $sformatf("d1->d2 RX with empty queue (expected -- FIFO empty-read probe): got 0x%03h", actual),
                    UVM_HIGH)
                return;
            end
            error_count++;
            `uvm_error("UART_SB",
                $sformatf("d1->d2 RX with empty queue: got 0x%03h", actual))
            return;
        end
        expected = d1_to_d2_expected.pop_front();
        if (actual === expected) begin
            pass_count++;
            if (!full_duplex_pair_log)
                $display("  [SB] PASS d1->d2  exp=0x%03h  act=0x%03h", expected, actual);
        end else begin
            error_count++;
            `uvm_error("UART_SB",
                $sformatf("FAIL d1->d2 exp=0x%03h act=0x%03h",
                          expected, actual))
        end
    endfunction

    virtual function void check_d2_to_d1(bit [8:0] actual);
        bit [8:0] expected;
        if (d2_to_d1_expected.size() == 0) begin
            if (allow_empty_d2_to_d1_read) begin
                `uvm_info("UART_SB",
                    $sformatf("d2->d1 RX with empty queue (expected -- FIFO empty-read probe): got 0x%03h", actual),
                    UVM_HIGH)
                return;
            end
            error_count++;
            `uvm_error("UART_SB",
                $sformatf("d2->d1 RX with empty queue: got 0x%03h", actual))
            return;
        end
        expected = d2_to_d1_expected.pop_front();
        if (actual === expected) begin
            pass_count++;
            if (!full_duplex_pair_log)
                $display("  [SB] PASS d2->d1  exp=0x%03h  act=0x%03h", expected, actual);
        end else begin
            error_count++;
            `uvm_error("UART_SB",
                $sformatf("FAIL d2->d1 exp=0x%03h act=0x%03h",
                          expected, actual))
        end
    endfunction

    function void check_phase(uvm_phase phase);
        super.check_phase(phase);

        if (d1_to_d2_expected.size() != 0) begin
            error_count++;
            `uvm_error("UART_SB",
                $sformatf("d1->d2 queue not empty at end: %0d",
                          d1_to_d2_expected.size()))
        end

        if (d2_to_d1_expected.size() != 0) begin
            error_count++;
            `uvm_error("UART_SB",
                $sformatf("d2->d1 queue not empty at end: %0d",
                          d2_to_d1_expected.size()))
        end
    endfunction
/*
    function void report_phase(uvm_phase phase);
        super.report_phase(phase);
        $display("\n========================================");
        $display("        UART SCOREBOARD SUMMARY");
        $display("========================================");
        $display("  d1 sent (THR wr)     : %0d", tx_d1_count);
        $display("  d2 recv (RHR rd)     : %0d", rx_d2_count);
        $display("  d2 sent (THR wr)     : %0d", tx_d2_count);
        $display("  d1 recv (RHR rd)     : %0d", rx_d1_count);
        $display("  d1 register accesses   : %0d", reg_access_d1_count);
        $display("  PASS                    : %0d", pass_count);
        $display("  ERROR                   : %0d", error_count);
        $display("========================================\n");
    endfunction
*/
endclass
