//      // verilator_coverage annotation
        //
        //------------------------------------------------------------------------------
        //   Copyright 2007-2010 Mentor Graphics Corporation
        //   Copyright 2007-2011 Cadence Design Systems, Inc. 
        //   Copyright 2010 Synopsys, Inc.
        //   All Rights Reserved Worldwide
        //
        //   Licensed under the Apache License, Version 2.0 (the
        //   "License"); you may not use this file except in
        //   compliance with the License.  You may obtain a copy of
        //   the License at
        //
        //       http://www.apache.org/licenses/LICENSE-2.0
        //
        //   Unless required by applicable law or agreed to in
        //   writing, software distributed under the License is
        //   distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
        //   CONDITIONS OF ANY KIND, either express or implied.  See
        //   the License for the specific language governing
        //   permissions and limitations under the License.
        //------------------------------------------------------------------------------
        
        `ifndef UVM_REPORT_SERVER_SVH
        `define UVM_REPORT_SERVER_SVH
        
        typedef class uvm_report_object;
        
        //------------------------------------------------------------------------------
        //
        // CLASS: uvm_report_server
        //
        // uvm_report_server is a global server that processes all of the reports
        // generated by an uvm_report_handler. None of its methods are intended to be
        // called by normal testbench code, although in some circumstances the virtual
        // methods process_report and/or compose_uvm_info may be overloaded in a
        // subclass.
        //
        //------------------------------------------------------------------------------
        
        typedef class uvm_report_catcher;
        class uvm_report_server extends uvm_object;
        
          local int max_quit_count; 
          local int quit_count;
          local int severity_count[uvm_severity];
        
          // Needed for callbacks
%000000   function string get_type_name();
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     return "uvm_report_server";
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
         
          // Variable: id_count
          //
          // An associative array holding the number of occurences
          // for each unique report ID.
        
          protected int id_count[string];
        
%000001   bit enable_report_id_count_summary=1;
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
        
        
          // Function: new
          //
          // Creates an instance of the class.
        
%000001   function new();
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     set_name("uvm_report_server");
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     set_max_quit_count(0);
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     reset_quit_count();
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     reset_severity_counts();
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
        
%000001   static protected uvm_report_server m_global_report_server = get_server();
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
        
          // Function: set_server
          //
          // Sets the global report server to use for reporting. The report
          // server is responsible for formatting messages.
        
%000000   static function void set_server(uvm_report_server server);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     if(m_global_report_server != null) begin
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       server.set_max_quit_count(m_global_report_server.get_max_quit_count());
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       server.set_quit_count(m_global_report_server.get_quit_count());
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       m_global_report_server.copy_severity_counts(server);
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       m_global_report_server.copy_id_counts(server);
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
            end
        
%000000     m_global_report_server = server;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
        
          // Function: get_server
          //
          // Gets the global report server. The method will always return 
          // a valid handle to a report server.
        
 002617   static function uvm_report_server get_server();
+002617  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
~002616     if (m_global_report_server == null)
-000001  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
+002616  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000001       m_global_report_server = new;
-000001  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
 002617     return m_global_report_server;
+002617  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
%000001   local bit m_max_quit_overridable = 1;
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
        
          // Function: set_max_quit_count
        
%000001   function void set_max_quit_count(int count, bit overridable = 1);
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     if (m_max_quit_overridable == 0) begin
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000001  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       uvm_report_info("NOMAXQUITOVR", $sformatf("The max quit count setting of %0d is not overridable to %0d due to a previous setting.", max_quit_count, count), UVM_NONE);
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       return;
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
            end
%000001     m_max_quit_overridable = overridable;
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     max_quit_count = count < 0 ? 0 : count;
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000001  point: type=expr comment=((count < 32'sh0)==0) => 0 hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=expr comment=((count < 32'sh0)==1) => 1 hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
          // Function: get_max_quit_count
          //
          // Get or set the maximum number of COUNT actions that can be tolerated
          // before an UVM_EXIT action is taken. The default is 0, which specifies
          // no maximum.
        
%000000   function int get_max_quit_count();
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     return max_quit_count;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
        
          // Function: set_quit_count
        
%000000   function void set_quit_count(int quit_count);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     quit_count = quit_count < 0 ? 0 : quit_count;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=expr comment=((quit_count < 32'sh0)==0) => 0 hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=expr comment=((quit_count < 32'sh0)==1) => 1 hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
          // Function: get_quit_count
        
%000000   function int get_quit_count();
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     return quit_count;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
          // Function: incr_quit_count
        
%000000   function void incr_quit_count();
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     quit_count++;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
          // Function: reset_quit_count
          //
          // Set, get, increment, or reset to 0 the quit count, i.e., the number of
          // COUNT actions issued.
        
%000001   function void reset_quit_count();
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     quit_count = 0;
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
          // Function: is_quit_count_reached
          //
          // If is_quit_count_reached returns 1, then the quit counter has reached
          // the maximum.
        
%000000   function bit is_quit_count_reached();
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     return (quit_count >= max_quit_count);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
        
          // Function: set_severity_count
        
%000000   function void set_severity_count(uvm_severity severity, int count);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     severity_count[severity] = count < 0 ? 0 : count;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=expr comment=((count < 32'sh0)==0) => 0 hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=expr comment=((count < 32'sh0)==1) => 1 hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
          // Function: get_severity_count
        
%000001   function int get_severity_count(uvm_severity severity);
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     return severity_count[severity];
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
          // Function: incr_severity_count
        
 002611   function void incr_severity_count(uvm_severity severity);
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 002611     severity_count[severity]++;
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
          // Function: reset_severity_counts
          //
          // Set, get, or increment the counter for the given severity, or reset
          // all severity counters to 0.
        
%000001   function void reset_severity_counts();
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     uvm_severity_type s;
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     s = s.first();
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000003     forever begin
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000003  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000003       severity_count[s] = 0;
-000003  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000003       if(s == s.last()) break;
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000003  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000003       s = s.next();
-000003  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
            end
          endfunction
        
        
          // Function: set_id_count
        
%000000   function void set_id_count(string id, int count);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     id_count[id] = count < 0 ? 0 : count;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=expr comment=((count < 32'sh0)==0) => 0 hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=expr comment=((count < 32'sh0)==1) => 1 hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
          // Function: get_id_count
        
%000000   function int get_id_count(string id);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     if(id_count.exists(id))
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       return id_count[id];
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     return 0;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
          // Function: incr_id_count
          //
          // Set, get, or increment the counter for reports with the given id.
        
 002611   function void incr_id_count(string id);
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 002593     if(id_count.exists(id))
+002593  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
+000018  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
 002593       id_count[id]++;
+002593  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
            else
 000018       id_count[id] = 1;
+000018  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
        
          // f_display
          //
          // This method sends string severity to the command line if file is 0 and to
          // the file(s) specified by file if it is not 0.
        
 000042   function void f_display(UVM_FILE file, string str);
+000042  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
~000042     if (file == 0)
+000042  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
 000042       $display("%s", str);
+000042  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
            else
%000000       $fdisplay(file, "%s", str);
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
          endfunction
        
        
          // Function- report
          //
          //
        
 002611   virtual function void report(
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
              uvm_severity severity,
              string name,
              string id,
              string message,
              int verbosity_level,
              string filename,
              int line,
              uvm_report_object client
              );
 002611     string m;
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 002611     uvm_action a;
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 002611     UVM_FILE f;
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 002611     bit report_ok;
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 002611     uvm_report_handler rh;
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
        
 002611     rh = client.get_report_handler();
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
          
            // filter based on verbosity level
         
~002611     if(!client.uvm_report_enabled(verbosity_level, severity, id)) begin
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
+002611  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000        return;
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
            end
        
            // determine file to send report and actions to execute
        
 002611     a = rh.get_action(severity, id); 
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
~002611     if( uvm_action_type'(a) == UVM_NO_ACTION )
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
+002611  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       return;
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
        
 002611     f = rh.get_file_handle(severity, id);
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
        
            // The hooks can do additional filtering.  If the hook function
            // return 1 then continue processing the report.  If the hook
            // returns 0 then skip processing the report.
        
~002611     if(a & UVM_CALL_HOOK)
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
+002611  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       report_ok = rh.run_hooks(client, severity, id,
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000                               message, verbosity_level, filename, line);
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
            else
 002611       report_ok = 1;
+002611  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
        
~002611     if(report_ok)
+002611  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
 002611       report_ok = uvm_report_catcher::process_all_report_catchers(
+002611  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
 002611                      this, client, severity, name, id, message,
+002611  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
 002611                      verbosity_level, a, filename, line);
+002611  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
        
~002611     if(report_ok) begin	
+002611  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
 002611       m = compose_message(severity, name, id, message, filename, line); 
+002611  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
 002611       process_report(severity, name, id, message, a, f, filename,
+002611  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
 002611                      line, m, verbosity_level, client);
+002611  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
            end
          
          endfunction
        
        
        
          // Function: process_report
          //
          // Calls <compose_message> to construct the actual message to be
          // output. It then takes the appropriate action according to the value of
          // action and file. 
          //
          // This method can be overloaded by expert users to customize the way the
          // reporting system processes reports and the actions enabled for them.
        
 002611   virtual function void process_report(
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
              uvm_severity severity,
              string name,
              string id,
              string message,
              uvm_action action,
              UVM_FILE file,
              string filename,
              int line,
              string composed_message,
              int verbosity_level,
              uvm_report_object client
              );
            // update counts
 002611     incr_severity_count(severity);
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 002611     incr_id_count(id);
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
        
~002611     if(action & UVM_DISPLAY)
+002611  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
 002611       $display("%s",composed_message);
+002611  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
        
            // if log is set we need to send to the file but not resend to the
            // display. So, we need to mask off stdout for an mcd or we need
            // to ignore the stdout file handle for a file handle.
~002611     if(action & UVM_LOG)
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
+002611  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       if( (file == 0) || (file != 32'h8000_0001) ) //ignore stdout handle
-000000  point: type=expr comment=((file != 32'h80000001)==1) => 1 hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=expr comment=((file == 32'sh0)==0 && (file != 32'h80000001)==0) => 0 hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=expr comment=((file == 32'sh0)==1) => 1 hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       begin
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000         UVM_FILE tmp_file = file;
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000         if( (file&32'h8000_0000) == 0) //is an mcd so mask off stdout
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000         begin
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000            tmp_file = file & 32'hffff_fffe;
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
                end
%000000         f_display(tmp_file,composed_message);
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
              end    
        
~002611     if(action & UVM_EXIT) client.die();
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
+002611  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
        
~002611     if(action & UVM_COUNT) begin
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
+002611  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       if(get_max_quit_count() != 0) begin
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000           incr_quit_count();
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000         if(is_quit_count_reached()) begin
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000           client.die();
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
                end
              end  
            end
        
 002611     if (action & UVM_STOP) $stop;
+002611  point: type=line comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
        
          endfunction
        
        
        
          // Function: compose_message
          //
          // Constructs the actual string sent to the file or command line
          // from the severity, component name, report id, and the message itself. 
          //
          // Expert users can overload this method to customize report formatting.
        
 002611   virtual function string compose_message(
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
              uvm_severity severity,
              string name,
              string id,
              string message,
              string filename,
              int    line
              );
 002611     uvm_severity_type sv;
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 002611     string time_str;
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 002611     string line_str;
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
            
 002611     sv = uvm_severity_type'(severity);
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 002611     $swrite(time_str, "%0t", $realtime);
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
         
 002611     case(1)
+002611  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       (name == "" && filename == ""):
-000000  point: type=line comment=case hier=uvm_pkg::uvm_report_server__Vclpkg
%000000 	       return {sv.name(), " @ ", time_str, " [", id, "] ", message};
-000000  point: type=line comment=case hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       (name != "" && filename == ""):
-000000  point: type=line comment=case hier=uvm_pkg::uvm_report_server__Vclpkg
%000000 	       return {sv.name(), " @ ", time_str, ": ", name, " [", id, "] ", message};
-000000  point: type=line comment=case hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       (name == "" && filename != ""):
-000000  point: type=line comment=case hier=uvm_pkg::uvm_report_server__Vclpkg
%000000            begin
-000000  point: type=line comment=case hier=uvm_pkg::uvm_report_server__Vclpkg
%000000                $swrite(line_str, "%0d", line);
-000000  point: type=line comment=case hier=uvm_pkg::uvm_report_server__Vclpkg
%000000 		 return {sv.name(), " ",filename, "(", line_str, ")", " @ ", time_str, " [", id, "] ", message};
-000000  point: type=line comment=case hier=uvm_pkg::uvm_report_server__Vclpkg
                   end
%000000       (name != "" && filename != ""):
-000000  point: type=line comment=case hier=uvm_pkg::uvm_report_server__Vclpkg
%000000            begin
-000000  point: type=line comment=case hier=uvm_pkg::uvm_report_server__Vclpkg
%000000                $swrite(line_str, "%0d", line);
-000000  point: type=line comment=case hier=uvm_pkg::uvm_report_server__Vclpkg
%000000 	         return {sv.name(), " ", filename, "(", line_str, ")", " @ ", time_str, ": ", name, " [", id, "] ", message};
-000000  point: type=line comment=case hier=uvm_pkg::uvm_report_server__Vclpkg
                   end
            endcase
          endfunction 
        
        
        
        
          // Function: summarize
          //
          // See <uvm_report_object::report_summarize> method.
        
%000001   virtual function void summarize(UVM_FILE file=0);
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     string id;
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     string name;
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     string output_str;
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     uvm_report_catcher::summarize_report_catcher(file);
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     f_display(file, "");
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     f_display(file, "--- UVM Report Summary ---");
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000001     f_display(file, "");
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
        
%000001     if(max_quit_count != 0) begin
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000001  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       if ( quit_count >= max_quit_count ) f_display(file, "Quit count reached!");
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       $sformat(output_str, "Quit count : %5d of %5d",
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000                              quit_count, max_quit_count);
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       f_display(file, output_str);
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
            end
        
%000001     f_display(file, "** Report counts by severity");
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000003     for(uvm_severity_type s = s.first(); 1; s = s.next()) begin
-000001  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000003  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000004       if(severity_count.exists(s)) begin
-000004  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000004         int cnt;
-000004  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000004         cnt = severity_count[s];
-000004  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000004         name = s.name();
-000004  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000004         $sformat(output_str, "%s :%5d", name, cnt);
-000004  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000004         f_display(file, output_str);
-000004  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
              end
%000003       if(s == s.last()) break;
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000003  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
            end
        
%000001     if (enable_report_id_count_summary) begin
-000001  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
        
%000001       f_display(file, "** Report counts by id");
-000001  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
~000018       for(int found = id_count.first(id);
-000001  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
+000018  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 000018            found;
+000018  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 000018            found = id_count.next(id)) begin
+000018  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 000018         int cnt;
+000018  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 000018         cnt = id_count[id];
+000018  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 000018         $sformat(output_str, "[%s] %5d", id, cnt);
+000018  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
 000018         f_display(file, output_str);
+000018  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
              end
        
            end
        
          endfunction
        
        
          // Function: dump_server_state
          //
          // Dumps server state information.
        
%000000   function void dump_server_state();
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
        
%000000     string s;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     uvm_severity_type sev;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     string id;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
        
%000000     f_display(0, "report server state");
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     f_display(0, "");   
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     f_display(0, "+-------------+");
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     f_display(0, "|   counts    |");
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     f_display(0, "+-------------+");
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     f_display(0, "");
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
        
%000000     $sformat(s, "max quit count = %5d", max_quit_count);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     f_display(0, s);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     $sformat(s, "quit count = %5d", quit_count);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     f_display(0, s);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
        
%000000     sev = sev.first();
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     forever begin
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       int cnt;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       cnt = severity_count[sev];
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       s = sev.name();
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       $sformat(s, "%s :%5d", s, cnt);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       f_display(0, s);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       if(sev == sev.last())
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000         break;
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       sev = sev.next();
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
            end
        
%000000     if(id_count.first(id))
-000000  point: type=branch comment=if hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=branch comment=else hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     do begin
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       int cnt;
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       cnt = id_count[id];
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       $sformat(s, "%s :%5d", id, cnt);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       f_display(0, s);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
            end
%000000     while (id_count.next(id));
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
        
          endfunction
        
        
          // Function- copy_severity_counts
          //
          // Internal method.
        
%000000   function void copy_severity_counts(uvm_report_server dst);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     foreach(severity_count[s]) begin
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       dst.set_severity_count(s,severity_count[s]);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
            end
          endfunction
        
        
          // Function- copy_severity_counts
          //
          // Internal method.
        
%000000   function void copy_id_counts(uvm_report_server dst);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000     foreach(id_count[s]) begin
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
%000000       dst.set_id_count(s,id_count[s]);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_server__Vclpkg
            end
          endfunction
        
        
        endclass
        
        
        
        //----------------------------------------------------------------------
        // CLASS- uvm_report_global_server
        //
        // Singleton object that maintains a single global report server
        //----------------------------------------------------------------------
        class uvm_report_global_server;
        
%000000   function new();
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_global_server__Vclpkg
%000000     void'(get_server());
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_global_server__Vclpkg
          endfunction
        
        
          // Function: get_server
          //
          // Returns a handle to the central report server.
        
%000000   function uvm_report_server get_server();
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_global_server__Vclpkg
%000000     return uvm_report_server::get_server();
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_global_server__Vclpkg
          endfunction
        
        
          // Function- set_server (deprecated)
          //
          //
        
%000000   function void set_server(uvm_report_server server);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_global_server__Vclpkg
%000000     uvm_report_server::set_server(server);
-000000  point: type=line comment=block hier=uvm_pkg::uvm_report_global_server__Vclpkg
          endfunction
        
        endclass
        
        
        `endif // UVM_REPORT_SERVER_SVH
        
