#!/usr/bin/env python3

import os
import sys
import html
import re
from pathlib import Path
from datetime import datetime


def classify_line(line):
    """
    Classify Verilator annotated coverage lines.
    """

    stripped = line.lstrip()

    # Coverage point generated by --annotate-points
    if "point: type=covergroup" in line:
        return "covergroup"

    if "point: type=user" in line:
        return "user"

    # Other functional coverage point descriptions
    if "point:" in line:
        return "point"

    # Coverage status markers
    if stripped.startswith("+"):
        return "covered"

    if stripped.startswith("-"):
        return "uncovered"

    if stripped.startswith("%"):
        return "uncovered"

    if stripped.startswith("~"):
        return "partial"

    return "source"


def extract_hit_count(line):
    """
    Verilator annotation normally places the hit count immediately
    after the coverage marker.

    Examples:

       +000123
       -000000
       %000004
       ~000010
    """

    match = re.match(r"^\s*[+\-%~]\s*(\d+)", line)

    if match:
        try:
            return int(match.group(1))
        except ValueError:
            pass

    return None


def extract_point_type(line):
    """
    Extract:
        type=covergroup
        type=user
        etc.
    """

    match = re.search(r"type=([A-Za-z0-9_]+)", line)

    if match:
        return match.group(1)

    return None


def extract_comment(line):
    """
    Extract the Verilator comment field if present.
    """

    match = re.search(r"comment=(.*?)(?:\s+hier=|\s*$)", line)

    if match:
        return match.group(1)

    return ""


def read_annotated_files(input_dir):
    files = []

    for path in sorted(Path(input_dir).rglob("*")):
        if path.is_file():
            files.append(path)

    return files


def analyze_file(path):
    try:
        text = path.read_text(errors="replace")
    except Exception:
        return None

    lines = text.splitlines()

    points = []

    for lineno, line in enumerate(lines, start=1):

        point_type = extract_point_type(line)

        if point_type in ("covergroup", "user"):

            hit_count = extract_hit_count(line)

            comment = extract_comment(line)

            points.append(
                {
                    "line": lineno,
                    "type": point_type,
                    "hits": hit_count,
                    "comment": comment,
                    "text": line,
                }
            )

    return {
        "path": str(path),
        "lines": lines,
        "points": points,
    }


def generate_html(input_dir, output_file):

    files = read_annotated_files(input_dir)

    reports = []

    total_points = 0
    covered_points = 0

    for path in files:

        result = analyze_file(path)

        if result is None:
            continue

        if result["points"]:
            reports.append(result)

            for point in result["points"]:

                total_points += 1

                if point["hits"] is not None and point["hits"] > 0:
                    covered_points += 1

    if total_points:
        overall = 100.0 * covered_points / total_points
    else:
        overall = 0.0

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    out = []

    out.append("<!DOCTYPE html>")
    out.append("<html>")
    out.append("<head>")
    out.append("<meta charset='UTF-8'>")
    out.append("<title>Verilator Functional Coverage</title>")

    out.append("""
<style>

body {
    font-family: Arial, Helvetica, sans-serif;
    background: #f4f6f8;
    margin: 0;
    padding: 0;
}

.header {
    background: #20252b;
    color: white;
    padding: 25px 35px;
}

.header h1 {
    margin: 0 0 8px 0;
}

.container {
    padding: 25px 35px;
}

.summary {
    display: flex;
    gap: 20px;
    margin-bottom: 30px;
}

.card {
    background: white;
    border-radius: 8px;
    padding: 20px;
    min-width: 180px;
    box-shadow: 0 2px 6px rgba(0,0,0,0.1);
}

.card-title {
    font-size: 13px;
    color: #666;
    margin-bottom: 8px;
}

.card-value {
    font-size: 30px;
    font-weight: bold;
}

.covered {
    color: #16803c;
}

.uncovered {
    color: #c62828;
}

.partial {
    color: #e68a00;
}

.file {
    background: white;
    margin-bottom: 25px;
    border-radius: 8px;
    box-shadow: 0 2px 6px rgba(0,0,0,0.08);
    overflow: hidden;
}

.file-header {
    background: #e9edf1;
    padding: 15px 20px;
    font-weight: bold;
}

table {
    width: 100%;
    border-collapse: collapse;
}

th {
    background: #f1f3f5;
    text-align: left;
    padding: 10px;
    border-bottom: 1px solid #ddd;
}

td {
    padding: 9px;
    border-bottom: 1px solid #eee;
    vertical-align: top;
}

td.line {
    width: 70px;
    color: #777;
}

td.type {
    width: 130px;
}

td.hits {
    width: 100px;
    font-weight: bold;
}

.source {
    font-family: monospace;
    white-space: pre-wrap;
}

.bar {
    height: 18px;
    width: 300px;
    background: #ddd;
    border-radius: 10px;
    overflow: hidden;
}

.bar-fill {
    height: 100%;
    background: #16803c;
}

.legend {
    margin: 20px 0;
    background: white;
    padding: 15px 20px;
    border-radius: 8px;
}

.badge {
    display: inline-block;
    padding: 3px 8px;
    border-radius: 4px;
    font-size: 12px;
    font-weight: bold;
}

.badge-covergroup {
    background: #d9ead3;
    color: #275e22;
}

.badge-user {
    background: #d9eaf7;
    color: #1d4f73;
}

.empty {
    background: white;
    padding: 30px;
    border-radius: 8px;
    color: #a00;
}

</style>
""")

    out.append("</head>")
    out.append("<body>")

    out.append("<div class='header'>")
    out.append("<h1>Verilator Functional Coverage</h1>")
    out.append(
        "<div>Generated: " + html.escape(now) + "</div>"
    )
    out.append("</div>")

    out.append("<div class='container'>")

    # Summary cards
    out.append("<div class='summary'>")

    out.append("<div class='card'>")
    out.append("<div class='card-title'>Functional Coverage</div>")
    out.append(
        "<div class='card-value covered'>"
        + f"{overall:.2f}%"
        + "</div>"
    )
    out.append("</div>")

    out.append("<div class='card'>")
    out.append("<div class='card-title'>Total Points</div>")
    out.append(
        "<div class='card-value'>"
        + str(total_points)
        + "</div>"
    )
    out.append("</div>")

    out.append("<div class='card'>")
    out.append("<div class='card-title'>Covered Points</div>")
    out.append(
        "<div class='card-value covered'>"
        + str(covered_points)
        + "</div>"
    )
    out.append("</div>")

    out.append("<div class='card'>")
    out.append("<div class='card-title'>Uncovered Points</div>")
    out.append(
        "<div class='card-value uncovered'>"
        + str(total_points - covered_points)
        + "</div>"
    )
    out.append("</div>")

    out.append("</div>")

    # Progress bar
    out.append("<h2>Overall Functional Coverage</h2>")

    out.append("<div class='bar'>")
    out.append(
        "<div class='bar-fill' style='width:"
        + f"{overall:.2f}%"
        + "'></div>"
    )
    out.append("</div>")

    out.append(
        f"<p>{covered_points} / {total_points} functional coverage points covered</p>"
    )

    out.append("""
<div class="legend">
<b>Legend</b><br><br>
<span class="badge badge-covergroup">covergroup</span>
SystemVerilog covergroup coverage<br><br>
<span class="badge badge-user">user</span>
User functional coverage point
</div>
""")

    if not reports:

        out.append("""
<div class="empty">
<b>No functional coverage points were found.</b>
<br><br>
Check that:
<br>
1. Verilator was compiled with --coverage.
<br>
2. Your covergroup is compiled.
<br>
3. Coverage data was generated after running the test.
<br>
4. You generated annotated coverage using:
<br><br>
verilator_coverage --filter-type covergroup --annotate functional_coverage --annotate-all --annotate-points merged_coverage.dat
</div>
""")

    # Each file
    for report in reports:

        relative_path = os.path.relpath(
            report["path"],
            input_dir
        )

        out.append("<div class='file'>")

        out.append(
            "<div class='file-header'>"
            + html.escape(relative_path)
            + "</div>"
        )

        out.append("<table>")

        out.append("""
<tr>
<th>Line</th>
<th>Type</th>
<th>Hits</th>
<th>Coverage Point</th>
<th>Source</th>
</tr>
""")

        for point in report["points"]:

            hits = point["hits"]

            if hits is None:
                hits_text = "-"
                status_class = "partial"
            elif hits > 0:
                hits_text = str(hits)
                status_class = "covered"
            else:
                hits_text = "0"
                status_class = "uncovered"

            comment = point["comment"]

            if not comment:
                comment = "(no comment)"

            out.append("<tr>")

            out.append(
                "<td class='line'>"
                + str(point["line"])
                + "</td>"
            )

            out.append(
                "<td class='type'>"
                + "<span class='badge badge-"
                + html.escape(point["type"])
                + "'>"
                + html.escape(point["type"])
                + "</span>"
                + "</td>"
            )

            out.append(
                "<td class='hits "
                + status_class
                + "'>"
                + hits_text
                + "</td>"
            )

            out.append(
                "<td>"
                + html.escape(comment)
                + "</td>"
            )

            out.append(
                "<td class='source'>"
                + html.escape(point["text"])
                + "</td>"
            )

            out.append("</tr>")

        out.append("</table>")
        out.append("</div>")

    out.append("</div>")
    out.append("</body>")
    out.append("</html>")

    Path(output_file).write_text(
        "\n".join(out),
        encoding="utf-8"
    )

    print()
    print("========================================")
    print(" FUNCTIONAL COVERAGE HTML")
    print("========================================")
    print(f"Input : {input_dir}")
    print(f"Output: {output_file}")
    print()
    print(f"Total points   : {total_points}")
    print(f"Covered points : {covered_points}")
    print(f"Coverage       : {overall:.2f}%")
    print()
    print("Open:")
    print(f"  file://{Path(output_file).resolve()}")
    print()


def main():

    if len(sys.argv) != 3:

        print(
            "Usage:\n"
            "  python3 generate_functional_coverage_html.py "
            "<annotated_dir> <output.html>"
        )

        sys.exit(1)

    input_dir = sys.argv[1]
    output_file = sys.argv[2]

    if not os.path.isdir(input_dir):

        print(
            f"ERROR: Directory does not exist: {input_dir}"
        )

        sys.exit(1)

    generate_html(
        input_dir,
        output_file
    )


if __name__ == "__main__":
    main()
