//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------

`timescale 1ns/1ps

// Testbench top: lpddr_tb_top
// Instantiates one interface per finalized signal group, connects
// each to the DUT, and publishes every group's virtual interface into
// uvm_resource_db (global scope "*") so any agent can read it by name.
`include "uvm_macros.svh"
import uvm_pkg::*;

module lpddr_tb_top;
 parameter int DATA_WIDTH = 64;
    parameter int ADDR_WIDTH = 32;

  logic sys_clk;
  logic sys_rst_n;

  lpddr5c_AXI_if AXI_vif (.sys_clk(sys_clk));
  assign AXI_vif.sys_rst_n = sys_rst_n;

  lpddr5c_APB_if APB_vif (.pclk(sys_clk));
  assign APB_vif.sys_rst_n = sys_rst_n;

  lpddr5c_DFI_if DFI_vif (.sys_clk(sys_clk));
  assign DFI_vif.sys_rst_n = sys_rst_n;

  lpddr5c_top dut (
        .sys_clk(sys_clk),
        .sys_rst_n(sys_rst_n),
    //============================================================
    // AXI WRITE ADDRESS
    //============================================================
//.s_axi_awid      (AXI_vif.axi_awid),
        .s_axi_awaddr    (AXI_vif.axi_awaddr),
        .s_axi_awlen     (AXI_vif.axi_awlen),
        .s_axi_awsize    (AXI_vif.axi_awsize),
        .s_axi_awburst   (AXI_vif.axi_awburst),
  //      .s_axi_awlock    (AXI_vif.axi_awlock),
    //    .s_axi_awcache   (AXI_vif.axi_awcache),
      //  .s_axi_awprot    (AXI_vif.axi_awprot),
        //.s_axi_awqos     (AXI_vif.axi_awqos),
        .s_axi_awvalid   (AXI_vif.axi_awvalid),
        .s_axi_awready   (AXI_vif.axi_awready),

        //========================================================
        // AXI WRITE DATA
        //========================================================
        .s_axi_wdata     (AXI_vif.axi_wdata),
        .s_axi_wstrb     (AXI_vif.axi_wstrb),
        .s_axi_wlast     (AXI_vif.axi_wlast),
        .s_axi_wvalid    (AXI_vif.axi_wvalid),
        .s_axi_wready    (AXI_vif.axi_wready),

        //========================================================
        // AXI WRITE RESPONSE
        //========================================================
       // .s_axi_bid       (AXI_vif.axi_bid),
        .s_axi_bresp     (AXI_vif.axi_bresp),
        .s_axi_bvalid    (AXI_vif.axi_bvalid),
        .s_axi_bready    (AXI_vif.axi_bready),

        //========================================================
        // AXI READ ADDRESS
        //========================================================
       // .s_axi_arid      (AXI_vif.axi_arid),
        .s_axi_araddr    (AXI_vif.axi_araddr),
        .s_axi_arlen     (AXI_vif.axi_arlen),
        .s_axi_arsize    (AXI_vif.axi_arsize),
        .s_axi_arburst   (AXI_vif.axi_arburst),
        //.s_axi_arlock    (AXI_vif.axi_arlock),
        //.s_axi_arcache   (AXI_vif.axi_arcache),
      //  .s_axi_arprot    (AXI_vif.axi_arprot),
       // .s_axi_arqos    (AXI_vif.axi_arqos),
        .s_axi_arvalid   (AXI_vif.axi_arvalid),
        .s_axi_arready   (AXI_vif.axi_arready),

        //========================================================
        // AXI READ DATA
        //========================================================
        //.s_axi_rid       (AXI_vif.axi_rid),
        .s_axi_rdata     (AXI_vif.axi_rdata),
        .s_axi_rresp     (AXI_vif.axi_rresp),
        .s_axi_rlast     (AXI_vif.axi_rlast),
        .s_axi_rvalid    (AXI_vif.axi_rvalid),
        .s_axi_rready    (AXI_vif.axi_rready),
        
        
      .dfi_clk(DFI_vif.dfi_clk),
        .dfi_rst_n(DFI_vif.dfi_rst_n),
        .dfi_cs_n(DFI_vif.dfi_cs_n),
        .dfi_cke(DFI_vif.dfi_cke),
        .dfi_ca(DFI_vif.dfi_ca),
        .dfi_rw(DFI_vif.dfi_rw),
        .dfi_rddata(DFI_vif.dfi_rddata),
        .dfi_rddata_valid(DFI_vif.dfi_rddata_valid),
        .dfi_wrdata(DFI_vif.dfi_wrdata),
        .dfi_wrdata_mask(DFI_vif.dfi_wrdata_mask),
        .dfi_wrdata_en(DFI_vif.dfi_wrdata_en),
        .dfi_phymstr_req(DFI_vif.dfi_phymstr_req),
        .dfi_phymstr_ack(DFI_vif.dfi_phymstr_ack),
        .dfi_phymstr_cs(DFI_vif.dfi_phymstr_cs),
        .dfi_rdlvl_req(DFI_vif.dfi_rdlvl_req),
        .dfi_rdlvl_en(DFI_vif.dfi_rdlvl_en),
        .dfi_wrlvl_req(DFI_vif.dfi_wrlvl_req),
        .dfi_wrlvl_en(DFI_vif.dfi_wrlvl_en),
        
        
        .pclk(APB_vif.pclk),
        .preset_n(APB_vif.preset_n),
        .psel(APB_vif.psel),
        .penable(APB_vif.penable),
        .pwrite(APB_vif.pwrite),
        .paddr(APB_vif.paddr),
        .pwdata(APB_vif.pwdata),
        .prdata(APB_vif.prdata),
        .pready(APB_vif.pready),
        .pslverr(APB_vif.pslverr),
        .intr_init_done(DFI_vif.intr_init_done),
        .intr_refresh_err(DFI_vif.intr_refresh_err),
        .intr_ecc_err(DFI_vif.intr_ecc_err),
        .intr_training_err(DFI_vif.intr_training_err),
        .intr_parity_err(DFI_vif.intr_parity_err),
        .debug_bus(DFI_vif.debug_bus)
  );

//PHY BFM
// rtl   (DFI.bfm);
lpddr5_phy_bfm phy_bfm (
        .dfi_clk          (sys_clk),
        .dfi_rst_n        (DFI_vif.sys_rst_n),

        .dfi_cs_n         (DFI_vif.dfi_cs_n),
        .dfi_cke          (DFI_vif.dfi_cke),
        .dfi_ca           (DFI_vif.dfi_ca),
        //.dfi_rw           (DFI_vif.dfi_rw),

        .dfi_cmd_addr     (DFI_vif.dfi_cmd_addr),
        .dfi_cmd_addr_valid(DFI_vif.dfi_cmd_addr_valid),

        .dfi_wrdata       (DFI_vif.dfi_wrdata),
        .dfi_wrdata_mask  (DFI_vif.dfi_wrdata_mask),
        .dfi_wrdata_en    (DFI_vif.dfi_wrdata_en),

        .dfi_rddata       (DFI_vif.dfi_rddata),
        .dfi_rddata_valid (DFI_vif.dfi_rddata_valid),

        .dfi_phymstr_req  (DFI_vif.dfi_phymstr_req),
        .dfi_phymstr_ack  (DFI_vif.dfi_phymstr_ack)
       // .dfi_phymstr_cs   (DFI_vif.dfi_phymstr_cs)

        //.dfi_rdlvl_req    (DFI_vif.dfi_rdlvl_req),
        //.dfi_rdlvl_en     (DFI_vif.dfi_rdlvl_en),

        //.dfi_wrlvl_req    (DFI_vif.dfi_wrlvl_req),
        //.dfi_wrlvl_en     (DFI_vif.dfi_wrlvl_en)
    );
    
 //DRAM MODEL
    
    lpddr5_dram_model #(
        .DATA_WIDTH(DATA_WIDTH),
        .ADDR_WIDTH(ADDR_WIDTH)
    ) dram (

        .sys_clk(sys_clk),
        .sys_rst_n(sys_rst_n),
        .cmd_valid(dram_cmd_valid),
       // .cmd_ready(dram_cmd_ready),
        .cmd(dram_cmd),
        .cmd_addr(dram_cmd_addr),

        .wrdata_valid(dram_wrdata_valid),
        .wrdata(dram_wrdata),
        .wrdata_mask(dram_wrdata_mask),

        .rddata_valid(dram_rddata_valid),
        .rddata(dram_rddata),

        .init_done(dram_init_done),
        .training_done(dram_training_done),
        .error(dram_error)

    );

  initial sys_clk = 0;
  always #5 sys_clk = ~sys_clk;   // 100MHz; TODO: adjust to target frequency
  initial begin
    sys_rst_n = 1'b0;
    repeat (5) @(posedge sys_clk);
    sys_rst_n = 1'b1;
    
  end

  initial begin
    uvm_resource_db#(virtual lpddr5c_AXI_if)::set("*", "vif", AXI_vif);
    uvm_resource_db#(virtual lpddr5c_APB_if)::set("*", "vif", APB_vif);
    uvm_resource_db#(virtual lpddr5c_DFI_if)::set("*", "vif", DFI_vif);
    run_test("base_test");
  end
  
  initial begin
  $dumpfile("lpddr_tb.vcd");
  $dumpvars(0,lpddr_tb_top);
  end

endmodule : lpddr_tb_top
