`include "uvm_macros.svh"
import uvm_pkg::*;

// ------------------------------------------------------------
// uart_config_sequence
//
// NOT currently instantiated anywhere in env/ or tests/ -- d2 is
// configured through the RAL model instead, via redirect_to_d2()
// + config_device_via_ral() in uart_virtual_sequence.sv (both d1
// and d2 reach the one shared RAL model by redirecting
// default_map's sequencer, so neither needs a raw, RAL-free
// path). Kept here, and kept correct against the current
// register map, since it's still compiled by sim/filelist.f and
// nothing should be left silently stale in case it's ever
// resurrected.
//
// Updated for the current THR/RHR/SR/CR/BRDR/IER/ISR map: CR[8]
// carries FLOW_EN and CR[13:9] carries RTS_THRESH; IER[3]
// carries RX_FULL_IRQ_EN. TX_WR_EN/RX_RD_EN remain pulse-like
// controls generated by uart_apb_top edge detection and are left 0
// here since this is a config-only write, not a send/receive.
// See uart_ral_pkg.sv for the same layout expressed as RAL
// fields.
// ------------------------------------------------------------

class uart_config_sequence extends uart_base_sequence;

    `uvm_object_utils(uart_config_sequence)

    localparam bit [31:0] ADDR_CR   = 32'h0000_000C;
    localparam bit [31:0] ADDR_BRDR = 32'h0000_0010;
    localparam bit [31:0] ADDR_IER  = 32'h0000_0014;

    rand bit [15:0] divisor;
    rand bit [3:0]  data_bits;
    rand bit        parity_en;
    rand bit [1:0]  parity_mode;
    rand bit        stop_2;
    rand bit        flow_en;
    rand bit [4:0]  rts_thresh;

    rand bit rx_irq_en;
    rand bit tx_empty_irq_en;
    rand bit err_irq_en;
    rand bit rx_full_irq_en;

    constraint valid_data_bits_c   { data_bits inside {7, 8, 9}; }
    constraint valid_parity_mode_c { parity_mode inside {[0:3]}; }
    constraint valid_rts_thresh_c { rts_thresh inside {[0:16]}; }

    function new(string name = "uart_config_sequence");
        super.new(name);
        divisor    = 16'd53;
        data_bits  = 4'd9;
        flow_en    = 1'b0;
        rts_thresh = 5'd14;
    endfunction

    function bit [1:0] encode_data_bits(bit [3:0] bits);
        case (bits)
            4'd7: return 2'b00;
            4'd8: return 2'b01;
            4'd9: return 2'b10;
            default: return 2'b01;
        endcase
    endfunction

    virtual task body();

        uart_seq_item req;

        // ---- BRDR ----
        req = uart_seq_item::type_id::create("req");
        start_item(req);
        req.paddr  = ADDR_BRDR;
        req.pwdata = {16'h0, divisor};
        req.pwrite = 1'b1;
        req.pstrb  = 4'hF;
        finish_item(req);

        // ---- CR (frame config only -- TX_WR_EN/RX_RD_EN = 0) ----
        req = uart_seq_item::type_id::create("req");
        start_item(req);
        req.paddr  = ADDR_CR;
        req.pwdata = {18'h0, rts_thresh, flow_en,
                      encode_data_bits(data_bits), stop_2,
                      parity_mode, parity_en, 1'b0, 1'b0};
        req.pwrite = 1'b1;
        req.pstrb  = 4'hF;
        finish_item(req);

        // ---- IER ----
        req = uart_seq_item::type_id::create("req");
        start_item(req);
        req.paddr  = ADDR_IER;
        req.pwdata = {28'h0, rx_full_irq_en, err_irq_en, rx_irq_en, tx_empty_irq_en};
        req.pwrite = 1'b1;
        req.pstrb  = 4'hF;
        finish_item(req);

    endtask

endclass
