//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Reset driver
class reset_driver extends uvm_driver #(reset_transaction);
  `uvm_component_utils(reset_driver)

  // ---------------------------------------------------------------------------
  // Virtual interface (no modport -- reset is input-observable)
  // ---------------------------------------------------------------------------
  virtual reset_if vif;

  // Default reset duration in time units (used if pulse_width not specified)
  localparam time DEFAULT_RESET_DURATION = 100;

  // ---------------------------------------------------------------------------
  // Constructor
  // ---------------------------------------------------------------------------
  function new(string name = "reset_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction : new

  // ---------------------------------------------------------------------------
  // Build Phase
  // ---------------------------------------------------------------------------
  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_resource_db#(virtual reset_if)::read_by_name(
            get_full_name(), "vif", vif, this)) begin
      `uvm_fatal(get_type_name(),
                 "Virtual interface 'vif' not set for reset_driver (reset_if).")
    end
  endfunction : build_phase

  // ---------------------------------------------------------------------------
  // Run Phase
  // ---------------------------------------------------------------------------
  task run_phase(uvm_phase phase);
    reset_transaction tr;
    // Initialize reset line to deasserted (1) by default to avoid X
    vif.rst_i = 1'b0;
    forever begin
      // Reset-aware: only drive when reset transaction arrives;
      // if reset is already deasserted (rst_i==1) we still wait for seq item.
      seq_item_port.get_next_item(tr);
      drive_reset(tr);
      seq_item_port.item_done();
    end
  endtask : run_phase

  // ---------------------------------------------------------------------------
  // Task: drive_reset
  // Drives reset according to the reset_transaction fields.
  // ---------------------------------------------------------------------------
  task drive_reset(reset_transaction tr);
    time width;
    width = (tr.pulse_width > 0) ? tr.pulse_width : DEFAULT_RESET_DURATION;
    `uvm_info(get_type_name(),$sformatf("Pulsing reset low for %0t time units (async). Start=%0t",
                        width, $time),UVM_LOW)
    vif.rst_i = 1'b0;
    #(width);
    vif.rst_i = 1'b1;
    `uvm_info(get_type_name(),$sformatf("Reset pulse complete. End=%0t", $time),UVM_LOW)
  endtask : drive_reset
endclass : reset_driver
