//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Reset monitor
class reset_monitor extends uvm_monitor;
  `uvm_component_utils(reset_monitor)

  // ---------------------------------------------------------------------------
  // Virtual interface (no modport)
  // ---------------------------------------------------------------------------
  virtual reset_if vif;

  // ---------------------------------------------------------------------------
  // Constructor
  // ---------------------------------------------------------------------------
  function new(string name = "reset_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction : new

  // ---------------------------------------------------------------------------
  // Build Phase
  // ---------------------------------------------------------------------------
  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_resource_db#(virtual reset_if)::read_by_name(
            get_full_name(), "vif", vif, this)) begin
      `uvm_fatal(get_type_name(),
                 "Virtual interface 'vif' not set for reset_monitor (reset_if).")
    end
  endfunction : build_phase

  // ---------------------------------------------------------------------------
  // Run Phase
  // ---------------------------------------------------------------------------
  task run_phase(uvm_phase phase);
    bit last_rst_n;
    // Initialize last_rst_n to current interface value to avoid X edges.
    last_rst_n = (vif.rst_i === 1'b1) ? 1'b1 : 1'b0;
    forever begin
      @(vif.rst_i); // Wait on any change of rst_i
      // Detect edges
      if ((last_rst_n === 1'b1) && (vif.rst_i === 1'b0)) begin
        // Assert edge (1 -> 0)
        send_event(1'b1);
      end
      else if ((last_rst_n === 1'b0) && (vif.rst_i === 1'b1)) begin
        // Deassert edge (0 -> 1)
        send_event(1'b0);
      end
      last_rst_n = vif.rst_i;
    end
  endtask : run_phase

  // ---------------------------------------------------------------------------
  // Task: send_event
  // ---------------------------------------------------------------------------
  task send_event(bit is_assert);
  endtask : send_event

endclass : reset_monitor
