//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Reset transaction: reset_transaction
class reset_transaction extends uvm_sequence_item;
  `uvm_object_utils(reset_transaction)

  rand time delay;       // delay before applying reset
  rand time pulse_width; // valid only for pulse type

  // Constraints
  constraint c_delay {
    delay >= 0;
  }

  function new(string name = "reset_transaction");
    super.new(name);
    delay = 0;
    pulse_width = 0;
  endfunction

  function string convert2string();
    return $sformatf("{delay=%0t, pulse_width=%0t}", delay, pulse_width);
  endfunction

endclass : reset_transaction
