`include "uvm_macros.svh"
import uvm_pkg::*;

// -----------------------------------------------------------------------------
// uart_stress_test.sv
//
// Stress methodology used here:
//   * Every stress testcase is FULL_DUPLEX only.
//   * Exactly 50 legal randomized TXDATA items are generated by D1 and 50 by D2.
//   * TX production and RX servicing run concurrently for the whole testcase.
//   * Frame/parity/break errors are injected on D2 rx_i at a randomized midpoint
//     gap, without inserting an unexpected APB TXDATA item into the scoreboard.
//   * FIFO-full / overrun scenarios deliberately pause the D2 RX service task.
//   * The normal stream resumes after the exceptional condition is observed.
//   * FIFO drain is therefore the normal continuous RX-service behavior at the end.
//
// No change to uart_virtual_sequence.sv is required. This test directly reuses
// the existing APB sequences and uart_if signals exposed by uart_env.
// -----------------------------------------------------------------------------

class uart_stress_test extends uart_base_test;

    `uvm_component_utils(uart_stress_test)

    localparam int unsigned DATA_COUNT  = 50;
    localparam int unsigned FIFO_DEPTH  = 16;
    localparam time         POLL_STEP   = 200;
    localparam time         RESET_WIDTH = 100;

    typedef enum int {
        STRESS_FRAME,
        STRESS_PARITY,
        STRESS_OVERRUN,
        STRESS_BREAK
    } stress_error_e;

    // Current DUT configuration for the active stress testcase.
    // Use a faster baud rate for stress traffic so 8 x 50-byte full-duplex
    // scenarios complete in reasonable wall-clock time. Both the DUT BRDR and
    // the stimulus timing helpers use this same divider.
    int unsigned  cfg_divisor = 10;
    bit [3:0]     cfg_data_bits;
    bit           cfg_parity_en;
    bit [1:0]     cfg_parity_mode;
    bit           cfg_stop_2;
    bit           cfg_flow_en;
    bit [4:0]     cfg_rts_thresh;

    // IER selection for the active testcase.
    bit cfg_rx_irq_en;
    bit cfg_tx_empty_irq_en;
    bit cfg_err_irq_en;
    bit cfg_rx_full_irq_en;

    // Shared runtime state for the concurrent D1/D2 producers/consumers.
    int unsigned d1_tx_count;
    int unsigned d2_tx_count;
    int unsigned d1_rx_count;
    int unsigned d2_rx_count;
    // Payload cursors are separate from actual RHR-read counts.  This lets
    // the test report a dropped legal frame and resynchronize comparisons so
    // one DUT loss does not turn the remainder of a 50-byte stream into a
    // misleading cascade of mismatches.
    int unsigned d1_rx_payload_cursor;
    int unsigned d2_rx_payload_cursor;

    // Mid-stream error coordination. The D1 producer stops before the selected
    // payload index, waits until its TX path is idle, then the test injects the
    // standalone malformed RX frame onto D2. The producer then continues.
    bit          error_injection_enable;
    stress_error_e active_error;
    int unsigned error_index;
    bit          error_source_ready;
    bit          release_error_source;

    // FIFO / flow-control pause coordination on D2 RX servicing.
    bit          fifo_pause_enable;
    bit          fifo_full_mode;
    bit          fifo_overrun_mode;
    bit          flow_pressure_mode;
    int unsigned fifo_pause_after_rx;
    bit          fifo_pause_ready;
    bit          release_fifo_pause;

    // For FIFO-full mode, stop before the first frame beyond capacity so that
    // the DUT can be observed at RX_FULL without intentionally creating an
    // overrun.  For overrun mode, allow exactly one 17th frame and then hold
    // the source until the stored 16 entries have been drained.
    bit          release_full_source;
    bit          allow_overrun_frame;
    bit          release_after_overrun;

    // Per-case local counters for explicit stress checks.
    int unsigned case_pass;
    int unsigned case_fail;
    int unsigned total_case_pass;
    int unsigned total_case_fail;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------
    function new(
        string name = "uart_stress_test",
        uvm_component parent = null
    );
        super.new(name, parent);
    endfunction

    // -------------------------------------------------------------------------
    // Small helpers
    // -------------------------------------------------------------------------
    function time uart_bit_time();
        return (cfg_divisor + 1) * 16 * 10;
    endfunction

    function time uart_frame_time();
        int unsigned frame_bits;

        frame_bits = 1 + cfg_data_bits +
                     (cfg_parity_en ? 1 : 0) +
                     (cfg_stop_2 ? 2 : 1);
        return frame_bits * uart_bit_time();
    endfunction

    function bit [1:0] encode_data_bits(bit [3:0] bits);
        case (bits)
            4'd7:    return 2'b00;
            4'd8:    return 2'b01;
            4'd9:    return 2'b10;
            default: begin
                `uvm_fatal("UART_STRESS_CFG",
                    $sformatf("Unsupported stress data_bits=%0d", bits))
                return 2'b00;
            end
        endcase
    endfunction

    function bit [8:0] random_data();
        bit [8:0] d;

        d = $urandom();
        case (cfg_data_bits)
            4'd7: d[8:7] = 2'b00;
            4'd8: d[8]   = 1'b0;
            4'd9: ;
            default: d = 9'h000;
        endcase
        return d;
    endfunction

    // The RTL break detector currently treats 11 consecutive low bit-times
    // as BREAK. A legal 9-bit zero with EVEN or SPACE parity creates exactly
    // that low run (start + 9 data bits + parity). Keep this corner visible
    // to stress verification rather than rewriting the payload; receivers
    // below report a dropped item and resynchronize after that one failure.
    function bit is_break_sensitive_zero(input bit [8:0] d);
        return (cfg_data_bits == 4'd9) && cfg_parity_en &&
               (d == 9'h000) &&
               ((cfg_parity_mode == 2'b00) ||
                (cfg_parity_mode == 2'b11));
    endfunction

    function bit calc_parity(bit [8:0] d);
        bit x;

        x = 1'b0;
        for (int i = 0; i < 9; i++) begin
            if (i < cfg_data_bits)
                x ^= d[i];
        end

        case (cfg_parity_mode)
            2'b00:   return x;       // even
            2'b01:   return ~x;      // odd
            2'b10:   return 1'b1;    // mark
            default: return 1'b0;    // space
        endcase
    endfunction

    function string parity_name();
        if (!cfg_parity_en)
            return "disabled";

        case (cfg_parity_mode)
            2'b00:   return "even";
            2'b01:   return "odd";
            2'b10:   return "mark";
            default: return "space";
        endcase
    endfunction

    function string error_name(stress_error_e e);
        case (e)
            STRESS_FRAME:   return "FRAME";
            STRESS_PARITY:  return "PARITY";
            STRESS_OVERRUN: return "OVERRUN";
            STRESS_BREAK:   return "BREAK";
            default:        return "?";
        endcase
    endfunction

    task stress_check(input string message, input bit condition);
        if (condition) begin
            case_pass++;
            $display("  [STRESS] PASS: %s", message);
        end
        else begin
            case_fail++;
            `uvm_error("UART_STRESS", $sformatf("FAIL: %s", message))
        end
    endtask

    // -------------------------------------------------------------------------
    // Raw APB access helpers. The two DUTs have independent APB sequencers,
    // so these helpers can be used concurrently by the two traffic threads.
    // -------------------------------------------------------------------------
    localparam bit [31:0] ADDR_THR  = 32'h0000_0000;
    localparam bit [31:0] ADDR_RHR  = 32'h0000_0004;
    localparam bit [31:0] ADDR_SR   = 32'h0000_0008;
    localparam bit [31:0] ADDR_CR   = 32'h0000_000C;
    localparam bit [31:0] ADDR_BRDR = 32'h0000_0010;
    localparam bit [31:0] ADDR_IER  = 32'h0000_0014;
    localparam bit [31:0] ADDR_ISR  = 32'h0000_0018;

    task automatic raw_apb_write(
        input  bit        is_d1,
        input  bit [31:0] addr,
        input  bit [31:0] data
    );
        uart_apb_write_sequence wr;

        wr = uart_apb_write_sequence::type_id::create(
            is_d1 ? "stress_wr_d1" : "stress_wr_d2"
        );
        wr.addr = addr;
        wr.data = data;
        wr.strb = 4'hF;

        if (is_d1)
            wr.start(env.virt_seqr.d1_sequencer);
        else
            wr.start(env.virt_seqr.d2_sequencer);
    endtask

    task automatic raw_apb_read(
        input  bit        is_d1,
        input  bit [31:0] addr,
        output bit [31:0] data
    );
        uart_apb_read_sequence rd;

        rd = uart_apb_read_sequence::type_id::create(
            is_d1 ? "stress_rd_d1" : "stress_rd_d2"
        );
        rd.addr = addr;

        if (is_d1)
            rd.start(env.virt_seqr.d1_sequencer);
        else
            rd.start(env.virt_seqr.d2_sequencer);

        data = rd.read_data;
    endtask

    function bit [31:0] build_cr();
        bit [31:0] cr;

        cr      = '0;
        cr[7:6] = encode_data_bits(cfg_data_bits);
        cr[5]   = cfg_stop_2;
        cr[4:3] = cfg_parity_mode;
        cr[2]   = cfg_parity_en;
        cr[8]   = cfg_flow_en;
        cr[13:9] = cfg_rts_thresh;
        return cr;
    endfunction

    function bit [31:0] build_ier();
        return {28'h0,
                cfg_rx_full_irq_en,
                cfg_err_irq_en,
                cfg_rx_irq_en,
                cfg_tx_empty_irq_en};
    endfunction

    // -------------------------------------------------------------------------
    // Reset/configuration
    // -------------------------------------------------------------------------
    task automatic stress_reset();
        reset_sequence rst;

        if (env.scoreboard != null) begin
            if (env.scoreboard.d1_to_d2_expected.size() != 0 ||
                env.scoreboard.d2_to_d1_expected.size() != 0) begin
                `uvm_error("UART_STRESS",
                    $sformatf("Starting case with stale scoreboard queues: d1->d2=%0d d2->d1=%0d",
                              env.scoreboard.d1_to_d2_expected.size(),
                              env.scoreboard.d2_to_d1_expected.size()))
                env.scoreboard.d1_to_d2_expected.delete();
                env.scoreboard.d2_to_d1_expected.delete();
            end
        end

        rst = reset_sequence::type_id::create("stress_rst");
        rst.delay       = 0;
        rst.pulse_width = RESET_WIDTH;
        rst.start(env.virt_seqr.reset_seqr);

        env.ral_model.reset();
    endtask

    task automatic configure_dut(input bit is_d1);
        raw_apb_write(is_d1, ADDR_BRDR, {16'h0, cfg_divisor[15:0]});
        raw_apb_write(is_d1, ADDR_CR,   build_cr());
        raw_apb_write(is_d1, ADDR_IER,  build_ier());
    endtask

    task automatic configure_both();
        configure_dut(1'b1);
        configure_dut(1'b0);
    endtask

    // -------------------------------------------------------------------------
    // APB-side TX/RX byte operations
    // -------------------------------------------------------------------------
    task automatic send_thr(input bit is_d1, input bit [8:0] data);
        bit [31:0] cr;

        raw_apb_write(is_d1, ADDR_THR, {23'h0, data});

        cr    = build_cr();
        cr[0] = 1'b1;
        raw_apb_write(is_d1, ADDR_CR, cr);
        raw_apb_write(is_d1, ADDR_CR, build_cr());
    endtask

    task automatic read_sr(input bit is_d1, output bit [31:0] sr);
        raw_apb_read(is_d1, ADDR_SR, sr);
    endtask

    task automatic wait_tx_space(input bit is_d1);
        bit [31:0] sr;
        time t0;

        t0 = $time;
        forever begin
            read_sr(is_d1, sr);
            if (!sr[1])
                return;

            if (($time - t0) > (uart_frame_time() * 8)) begin
                `uvm_error("UART_STRESS",
                    is_d1 ? "D1 TX FIFO stayed full too long" :
                            "D2 TX FIFO stayed full too long")
                return;
            end
            #POLL_STEP;
        end
    endtask

    task automatic wait_tx_empty_and_idle(input bit is_d1);
        bit [31:0] sr;
        virtual uart_if vif;
        bit line_idle;
        time t0;
        time high_start;

        // Avoid a conditional expression on virtual-interface handles;
        // Keep virtual-interface selection in explicit assignment branches.
        if (is_d1)
            vif = env.virt_seqr.d1_vif;
        else
            vif = env.virt_seqr.d2_vif;
        t0  = $time;

        forever begin
            read_sr(is_d1, sr);
            if (sr[0]) begin
                high_start = $time;
                line_idle  = 1'b1;

                while (($time - high_start) < uart_bit_time()) begin
                    if (vif.tx_o !== 1'b1) begin
                        line_idle = 1'b0;
                        break;
                    end
                    #POLL_STEP;
                end

                if (line_idle)
                    return;
            end

            if (($time - t0) > (uart_frame_time() * (FIFO_DEPTH + 4))) begin
                `uvm_error("UART_STRESS",
                    is_d1 ? "D1 TX path did not reach an idle state" :
                            "D2 TX path did not reach an idle state")
                return;
            end
            #POLL_STEP;
        end
    endtask

    // This stronger idle check is reserved for the malformed-frame boundary.
    // TX FIFO empty alone does not mean the shift register has finished the
    // stop bit. Require a whole frame-time of continuously-high TX after the
    // FIFO becomes empty so error injection cannot cut off the preceding
    // legal frame. Do not use this on every normal payload item.
    task automatic wait_tx_quiescent_for_error(input bit is_d1);
        bit [31:0] sr;
        virtual uart_if vif;
        bit line_idle;
        time t0;
        time high_start;

        if (is_d1)
            vif = env.virt_seqr.d1_vif;
        else
            vif = env.virt_seqr.d2_vif;

        t0 = $time;
        forever begin
            read_sr(is_d1, sr);
            if (sr[0] && (vif.tx_o === 1'b1)) begin
                high_start = $time;
                line_idle = 1'b1;
                while (($time - high_start) < uart_frame_time()) begin
                    if (vif.tx_o !== 1'b1) begin
                        line_idle = 1'b0;
                        break;
                    end
                    #POLL_STEP;
                end
                if (line_idle) begin
                    read_sr(is_d1, sr);
                    if (sr[0] && (vif.tx_o === 1'b1))
                        return;
                end
            end

            if (($time - t0) > (uart_frame_time() * (DATA_COUNT + FIFO_DEPTH + 16))) begin
                `uvm_error("UART_STRESS",
                    is_d1 ? "D1 TX did not become quiescent before error injection" :
                            "D2 TX did not become quiescent before error injection")
                return;
            end
            #POLL_STEP;
        end
    endtask

    task automatic wait_rx_empty(input bit is_d1);
        bit [31:0] sr;
        time t0;

        t0 = $time;
        forever begin
            read_sr(is_d1, sr);
            if (sr[2])
                return;

            if (($time - t0) > (uart_frame_time() * (FIFO_DEPTH + 8))) begin
                `uvm_error("UART_STRESS",
                    is_d1 ? "D1 RX FIFO did not become empty" :
                            "D2 RX FIFO did not become empty")
                return;
            end
            #POLL_STEP;
        end
    endtask

    task automatic wait_rx_full(input bit is_d1);
        bit [31:0] sr;
        time t0;

        t0 = $time;
        forever begin
            read_sr(is_d1, sr);
            if (sr[3])
                return;

            if (($time - t0) > (uart_frame_time() * (FIFO_DEPTH + 8))) begin
                `uvm_error("UART_STRESS",
                    is_d1 ? "D1 RX FIFO did not become full" :
                            "D2 RX FIFO did not become full")
                return;
            end
            #POLL_STEP;
        end
    endtask

    task automatic recv_rhr(input bit is_d1, output bit [8:0] data);
        bit [31:0] sr;
        bit [31:0] rhr;
        bit [31:0] cr;
        time t0;

        data = '0;
        t0   = $time;

        forever begin
            read_sr(is_d1, sr);
            if (!sr[2])
                break;

            if (($time - t0) > (uart_frame_time() * (FIFO_DEPTH + 8))) begin
                `uvm_error("UART_STRESS",
                    is_d1 ? "D1 RX service timed out" :
                            "D2 RX service timed out")
                return;
            end
            #POLL_STEP;
        end

        raw_apb_read(is_d1, ADDR_RHR, rhr);
        data = rhr[8:0];

        cr    = build_cr();
        cr[1] = 1'b1;
        raw_apb_write(is_d1, ADDR_CR, cr);
        raw_apb_write(is_d1, ADDR_CR, build_cr());
    endtask

    // -------------------------------------------------------------------------
    // IRQ observation helpers
    // -------------------------------------------------------------------------
    task automatic check_rx_irq_when_data_present(
        input bit           is_d1,
        input bit [31:0]    sr,
        input string        side_name
    );
        if (cfg_rx_irq_en && !sr[2]) begin
            stress_check(
                $sformatf("%s RX non-empty condition drives irq_o", side_name),
                (is_d1 ? env.virt_seqr.d1_vif.irq_o :
                         env.virt_seqr.d2_vif.irq_o) === 1'b1
            );
        end
    endtask

    task automatic check_tx_empty_irq(input bit is_d1, input string side_name);
        virtual uart_if vif;
        bit [31:0] sr;

        // Avoid a conditional expression on virtual-interface handles;
        // Keep virtual-interface selection in explicit assignment branches.
        if (is_d1)
            vif = env.virt_seqr.d1_vif;
        else
            vif = env.virt_seqr.d2_vif;
        read_sr(is_d1, sr);

        if (cfg_tx_empty_irq_en) begin
            stress_check(
                $sformatf("%s TX_EMPTY condition drives irq_o", side_name),
                (sr[0] && (vif.irq_o === 1'b1))
            );
        end
    endtask

    // -------------------------------------------------------------------------
    // Continuous producers
    // -------------------------------------------------------------------------
    task automatic producer_d1(input bit [8:0] payload[DATA_COUNT]);
        bit use_one_by_one;

        use_one_by_one = fifo_pause_enable;

        for (int i = 0; i < DATA_COUNT; i++) begin

            // Midpoint error-injection gate. No normal D1 byte at error_index
            // is sent until the malformed RX stimulus has been completed.
            if (error_injection_enable && (i == error_index)) begin
                wait_tx_quiescent_for_error(1'b1);
                error_source_ready = 1'b1;
                while (!release_error_source)
                    #POLL_STEP;
            end

            // FIFO boundary cases use one-frame-at-a-time production so the
            // exact FIFO transition can be observed without accidentally
            // creating multiple unintended overflow events.
            if (use_one_by_one)
                wait_tx_empty_and_idle(1'b1);
            else
                wait_tx_space(1'b1);

            // Overrun case: permit the 17th normal-link frame only after
            // RX_FULL has been observed. That frame is the intentional drop.
            if (fifo_overrun_mode && (i == FIFO_DEPTH)) begin
                while (!allow_overrun_frame)
                    #POLL_STEP;
            end

            // FIFO-full-only case: hold before frame 17 until RX_FULL has
            // been observed and the RX service task has been released.
            if (fifo_full_mode && !fifo_overrun_mode && (i == FIFO_DEPTH)) begin
                while (!release_full_source)
                    #POLL_STEP;
            end

            send_thr(1'b1, payload[i]);
            d1_tx_count++;

            if (fifo_overrun_mode && (i == FIFO_DEPTH)) begin
                while (!release_after_overrun)
                    #POLL_STEP;
            end
        end
    endtask

    task automatic producer_d2(input bit [8:0] payload[DATA_COUNT]);
        for (int i = 0; i < DATA_COUNT; i++) begin
            wait_tx_space(1'b0);
            send_thr(1'b0, payload[i]);
            d2_tx_count++;
        end
    endtask

    // -------------------------------------------------------------------------
    // Continuous receivers
    // -------------------------------------------------------------------------
    task automatic receiver_d1(input bit [8:0] payload[DATA_COUNT]);
        bit [8:0] got;
        bit [31:0] sr;
        int unsigned expected_payload_index;
        int unsigned matched_payload_index;
        bit recovered_after_zero_drop;
        time t0;
        time rx_timeout;

        t0 = $time;
        rx_timeout = uart_frame_time() * (DATA_COUNT + FIFO_DEPTH + 32);
        while (d1_rx_payload_cursor < DATA_COUNT) begin
            if (($time - t0) > rx_timeout) begin
                `uvm_error("UART_STRESS",
                    $sformatf("D1 RX timed out after %0d/%0d payload items",
                              d1_rx_count, DATA_COUNT))
                break;
            end
            read_sr(1'b1, sr);
            check_rx_irq_when_data_present(1'b1, sr, "D1");

            if (sr[2]) begin
                #POLL_STEP;
                continue;
            end

            recv_rhr(1'b1, got);
            expected_payload_index = d1_rx_payload_cursor;
            recovered_after_zero_drop = 1'b0;

            if (got !== payload[expected_payload_index]) begin
                // Detect the known 9-bit EVEN/SPACE zero-frame failure and
                // resynchronize after reporting it. The scoreboard has
                // already consumed the current expected head for this RHR
                // transaction, so discard any later expected entries through
                // the item that was actually received.
                if (is_break_sensitive_zero(payload[expected_payload_index])) begin
                    matched_payload_index = DATA_COUNT;
                    for (int j = expected_payload_index + 1; j < DATA_COUNT; j++) begin
                        if ((matched_payload_index == DATA_COUNT) && (got === payload[j]))
                            matched_payload_index = j;
                    end

                    if (matched_payload_index < DATA_COUNT) begin
                        stress_check(
                            $sformatf("DUT preserves legal 9-bit zero at D1 RX payload[%0d]", expected_payload_index),
                            1'b0);
                        #POLL_STEP;
                        if (env.scoreboard != null) begin
                            for (int k = expected_payload_index + 1;
                                 k <= matched_payload_index; k++)
                                env.scoreboard.discard_d2_to_d1_pending(1'b1);
                        end
                        d1_rx_payload_cursor = matched_payload_index + 1;
                        recovered_after_zero_drop = 1'b1;
                    end
                end

                if (!recovered_after_zero_drop) begin
                    `uvm_error("UART_STRESS",
                        $sformatf("D2->D1 stream mismatch at index %0d: expected=0x%03h received=0x%03h",
                                  expected_payload_index, payload[expected_payload_index], got))
                    d1_rx_payload_cursor++;
                end
            end
            else begin
                d1_rx_payload_cursor++;
            end
            d1_rx_count++;
        end
    endtask

    task automatic receiver_d2(input bit [8:0] payload[DATA_COUNT]);
        bit [8:0] got;
        bit [31:0] sr;
        int unsigned rx_target_count;
        int unsigned expected_payload_index;
        int unsigned matched_payload_index;
        bit recovered_after_zero_drop;
        time t0;
        time rx_timeout;

        t0 = $time;
        rx_timeout = uart_frame_time() * (DATA_COUNT + FIFO_DEPTH + 32);
        rx_target_count = fifo_overrun_mode ? (DATA_COUNT - 1) : DATA_COUNT;
        while (d2_rx_payload_cursor < rx_target_count) begin
            if (($time - t0) > rx_timeout) begin
                `uvm_error("UART_STRESS",
                    $sformatf("D2 RX timed out after %0d/%0d payload items",
                              d2_rx_count, DATA_COUNT))
                break;
            end

            if (fifo_pause_enable &&
                !fifo_pause_ready &&
                (d2_rx_count == fifo_pause_after_rx)) begin
                fifo_pause_ready = 1'b1;
                while (!release_fifo_pause)
                    #POLL_STEP;
            end

            read_sr(1'b0, sr);
            check_rx_irq_when_data_present(1'b0, sr, "D2");

            if (sr[2]) begin
                #POLL_STEP;
                continue;
            end

            recv_rhr(1'b0, got);

            // Exactly payload item 16 (the 17th received frame) is intentionally
            // dropped in FIFO-overrun mode. Use the payload cursor (rather
            // than actual reads) to maintain the source-array mapping.
            expected_payload_index = d2_rx_payload_cursor;
            if (fifo_overrun_mode && (d2_rx_payload_cursor >= FIFO_DEPTH))
                expected_payload_index = d2_rx_payload_cursor + 1;
            recovered_after_zero_drop = 1'b0;

            if (got !== payload[expected_payload_index]) begin
                if (is_break_sensitive_zero(payload[expected_payload_index])) begin
                    matched_payload_index = DATA_COUNT;
                    for (int j = expected_payload_index + 1; j < DATA_COUNT; j++) begin
                        if ((matched_payload_index == DATA_COUNT) && (got === payload[j]))
                            matched_payload_index = j;
                    end

                    if (matched_payload_index < DATA_COUNT) begin
                        stress_check(
                            $sformatf("DUT preserves legal 9-bit zero at D2 RX payload[%0d]", expected_payload_index),
                            1'b0);
                        #POLL_STEP;
                        if (env.scoreboard != null) begin
                            for (int k = expected_payload_index + 1;
                                 k <= matched_payload_index; k++)
                                env.scoreboard.discard_d1_to_d2_pending(1'b1);
                        end
                        d2_rx_payload_cursor = matched_payload_index + 1;
                        recovered_after_zero_drop = 1'b1;
                    end
                end

                if (!recovered_after_zero_drop) begin
                    `uvm_error("UART_STRESS",
                        $sformatf("D1->D2 stream mismatch: RX item %0d expected payload[%0d]=0x%03h received=0x%03h",
                                  d2_rx_count, expected_payload_index,
                                  payload[expected_payload_index], got))
                    d2_rx_payload_cursor++;
                end
            end
            else begin
                d2_rx_payload_cursor++;
            end
            d2_rx_count++;
        end
    endtask

    // -------------------------------------------------------------------------
    // Error injection onto D2 rx_i
    // -------------------------------------------------------------------------
    task automatic inject_error_frame(input bit [8:0] error_data);
        bit parity_value;
        virtual uart_if vif;

        vif = env.virt_seqr.d2_vif;

        vif.spec_rx_drive_en = 1'b1;
        vif.spec_rx_drive    = 1'b1;
        #(uart_bit_time());

        // Start bit.
        vif.spec_rx_drive = 1'b0;
        #(uart_bit_time());

        // Data bits, LSB first.
        for (int b = 0; b < 9; b++) begin
            if (b < cfg_data_bits) begin
                vif.spec_rx_drive = error_data[b];
                #(uart_bit_time());
            end
        end

        parity_value = calc_parity(error_data);

        if (cfg_parity_en) begin
            if (active_error == STRESS_PARITY)
                vif.spec_rx_drive = ~parity_value;
            else
                vif.spec_rx_drive = parity_value;
            #(uart_bit_time());
        end

        // Frame error: drive the first stop bit LOW.
        // Parity error: first stop bit remains HIGH.
        vif.spec_rx_drive =
            (active_error == STRESS_FRAME) ? 1'b0 : 1'b1;
        #(uart_bit_time());

        if (cfg_stop_2) begin
            // Keep the second stop bit legal unless the first stop itself is
            // the requested framing violation.
            vif.spec_rx_drive = 1'b1;
            #(uart_bit_time());
        end

        vif.spec_rx_drive = 1'b1;
    endtask

    task automatic inject_break();
        virtual uart_if vif;

        vif = env.virt_seqr.d2_vif;

        vif.spec_rx_drive_en = 1'b1;
        vif.spec_rx_drive    = 1'b1;
        #(uart_bit_time());

        $display("  [STRESS] BREAK injection: D2 rx_i LOW for 13 UART bit times");
        vif.spec_rx_drive = 1'b0;
        #(13 * uart_bit_time());
        vif.spec_rx_drive = 1'b1;
        #(2 * uart_bit_time());
    endtask

    task automatic check_and_clear_injected_error();
        bit [31:0] isr;
        bit [31:0] isr_after;
        virtual uart_if vif;
        bit expected_flag;
        bit irq_seen;

        vif = env.virt_seqr.d2_vif;

        // Allow the RX FSM to reach its error decision point.
        #(2 * uart_bit_time());

        irq_seen = 1'b0;
        if (cfg_err_irq_en) begin
            irq_seen = (vif.irq_o === 1'b1);
            stress_check(
                $sformatf("D2 error IRQ asserts for %s condition",
                          error_name(active_error)),
                irq_seen
            );
        end

        raw_apb_read(1'b0, ADDR_ISR, isr);

        case (active_error)
            STRESS_FRAME:   expected_flag = isr[5];
            STRESS_PARITY:  expected_flag = isr[4];
            STRESS_OVERRUN: expected_flag = isr[6];
            STRESS_BREAK:   expected_flag = isr[7];
            default:        expected_flag = 1'b0;
        endcase

        stress_check(
            $sformatf("D2 ISR contains expected %s error flag", error_name(active_error)),
            expected_flag
        );

        // ISR is read-to-clear in the current DUT.
        raw_apb_read(1'b0, ADDR_ISR, isr_after);
        if (expected_flag) begin
            stress_check(
                $sformatf("D2 %s sticky error clears after ISR read", error_name(active_error)),
                isr_after[7:4] == 4'b0000
            );
        end
        else begin
            // Do not print a misleading PASS for clearing an error that never
            // asserted. The read is still performed to leave ISR in a known
            // read-to-clear state for continued traffic.
            $display("  [STRESS] SKIP sticky-clear PASS: %s was not set by the injected stimulus",
                     error_name(active_error));
        end
    endtask

    task automatic inject_midstream_error(input bit [8:0] error_data);
        virtual uart_if vif;
        bit [31:0] isr_before_error;
        time t0;

        t0 = $time;
        while (error_source_ready !== 1'b1) begin
            if (($time - t0) > (uart_frame_time() * (DATA_COUNT + FIFO_DEPTH + 16))) begin
                `uvm_error("UART_STRESS", "Timed out waiting for error-injection midpoint")
                release_error_source = 1'b1;
                return;
            end
            #POLL_STEP;
        end
        wait_rx_empty(1'b0);

        // Read/clear any sticky RX error before deliberate injection. This is
        // important for 9-bit all-zero traffic: the existing RTL break detector
        // may assert early after a long continuous-low valid frame. Catch that
        // separately so an old error cannot falsely satisfy the injected-error check.
        raw_apb_read(1'b0, ADDR_ISR, isr_before_error);
        stress_check("No unexpected D2 sticky RX error before intentional injection",
                     isr_before_error[7:4] == 4'b0000);

        $display("  [STRESS] MIDSTREAM ERROR at D1 payload index %0d : %s",
                 error_index, error_name(active_error));

        vif = env.virt_seqr.d2_vif;
        vif.spec_rx_drive_en = 1'b1;
        vif.spec_rx_drive    = 1'b1;

        if (active_error == STRESS_BREAK)
            inject_break();
        else
            inject_error_frame(error_data);

        // Release the D1 producer only after the injected error has been
        // observed and the sticky status has been cleared.
        check_and_clear_injected_error();

        vif.spec_rx_drive    = 1'b1;
        vif.spec_rx_drive_en = 1'b0;

        release_error_source = 1'b1;
    endtask

    // -------------------------------------------------------------------------
    // FIFO/flow-control orchestration
    // -------------------------------------------------------------------------
    task automatic handle_fifo_full_case();
        bit [31:0] sr;
        time t0;

        t0 = $time;
        while (fifo_pause_ready !== 1'b1) begin
            if (($time - t0) > (uart_frame_time() * (DATA_COUNT + FIFO_DEPTH + 16))) begin
                `uvm_error("UART_STRESS", "Timed out waiting for RX pause before FIFO-full check")
                release_fifo_pause = 1'b1;
                release_full_source = 1'b1;
                return;
            end
            #POLL_STEP;
        end
        wait_rx_full(1'b0);

        read_sr(1'b0, sr);
        stress_check("D2 RX_FULL asserts at FIFO capacity", sr[3] === 1'b1);

        if (cfg_rx_full_irq_en) begin
            stress_check("D2 RX_FULL interrupt asserts while FIFO is full",
                         env.virt_seqr.d2_vif.irq_o === 1'b1);
        end

        // The full-only stress case must not accidentally cross into overrun.
        // ISR is read-to-clear, so this is also the isolation point for the
        // FIFO-full condition before normal service resumes.
        raw_apb_read(1'b0, ADDR_ISR, sr);
        stress_check("D2 RX FIFO FULL occurs before any OVERRUN in full-only case",
                     sr[6] === 1'b0);

        // Resume normal RX service first, then release the D1 source from its
        // one-by-one capacity gate. This ensures no intentional overrun occurs.
        release_fifo_pause = 1'b1;
        release_full_source = 1'b1;

    endtask

    task automatic handle_flow_pressure_case();
        bit [31:0] sr;
        time t0;

        t0 = $time;
        while (fifo_pause_ready !== 1'b1) begin
            if (($time - t0) > (uart_frame_time() * (DATA_COUNT + FIFO_DEPTH + 16))) begin
                `uvm_error("UART_STRESS", "Timed out waiting for RX pause before RTS/CTS check")
                release_fifo_pause = 1'b1;
                return;
            end
            #POLL_STEP;
        end

        // The receiver pauses, FIFO rises above RTS threshold, and CTS must
        // follow it. The source TX task does not need a special CTS check:
        // it keeps writing while TX has room and the DUT itself stops launching
        // new frames when CTS is high.
        t0 = $time;
        forever begin
            if (env.virt_seqr.d2_vif.rts_n_o === 1'b1)
                break;

            if (($time - t0) > (uart_frame_time() * (FIFO_DEPTH + 8))) begin
                stress_check("D2 RTS de-asserts under sustained RX pressure", 1'b0);
                break;
            end
            #POLL_STEP;
        end

        stress_check("D2 RTS de-asserts when RX FIFO crosses threshold",
                     env.virt_seqr.d2_vif.rts_n_o === 1'b1);
        stress_check("D1 CTS follows D2 RTS high",
                     env.virt_seqr.d1_vif.cts_n_i === 1'b1);

        read_sr(1'b0, sr);
        $display("  [FLOW] D2 under RTS pressure: RX_FULL=%0b", sr[3]);

        release_fifo_pause = 1'b1;

        t0 = $time;
        forever begin
            if (env.virt_seqr.d2_vif.rts_n_o === 1'b0)
                break;

            if (($time - t0) > (uart_frame_time() * (FIFO_DEPTH + 8))) begin
                stress_check("D2 RTS returns low after RX service resumes", 1'b0);
                break;
            end
            #POLL_STEP;
        end

        stress_check("D2 RTS returns low after RX service resumes",
                     env.virt_seqr.d2_vif.rts_n_o === 1'b0);
        stress_check("D1 CTS follows D2 RTS low",
                     env.virt_seqr.d1_vif.cts_n_i === 1'b0);
    endtask

    task automatic handle_overrun_case();
        bit [31:0] isr;
        bit [31:0] isr_after;
        time t0;

        t0 = $time;
        while (fifo_pause_ready !== 1'b1) begin
            if (($time - t0) > (uart_frame_time() * (DATA_COUNT + FIFO_DEPTH + 16))) begin
                `uvm_error("UART_STRESS", "Timed out waiting for RX pause before overrun check")
                release_fifo_pause = 1'b1;
                allow_overrun_frame = 1'b1;
                release_after_overrun = 1'b1;
                return;
            end
            #POLL_STEP;
        end
        wait_rx_full(1'b0);

        stress_check("D2 RX FIFO full before intentional overrun frame",
                     env.virt_seqr.d2_vif.rts_n_o === 1'b1);

        allow_overrun_frame = 1'b1;

        // Give the 17th frame time to reach the already-full receiver.
        #(uart_frame_time() + uart_bit_time());

        if (cfg_err_irq_en) begin
            stress_check("D2 error IRQ asserts for RX overrun",
                         env.virt_seqr.d2_vif.irq_o === 1'b1);
        end

        raw_apb_read(1'b0, ADDR_ISR, isr);
        stress_check("D2 ISR OVERRUN flag asserts on the 17th frame",
                     isr[6] === 1'b1);

        raw_apb_read(1'b0, ADDR_ISR, isr_after);
        stress_check("D2 OVERRUN sticky flag clears on ISR read",
                     isr_after[7:4] == 4'b0000);

        // Now allow the receiver to drain all 16 stored entries. Because the
        // D1 producer was held immediately after the intentional 17th frame,
        // the scoreboard head is exactly the dropped 17th expected item once
        // d2_rx_count reaches 16.
        release_fifo_pause = 1'b1;

        t0 = $time;
        while (d2_rx_count < FIFO_DEPTH) begin
            if (($time - t0) > (uart_frame_time() * (DATA_COUNT + FIFO_DEPTH + 16))) begin
                `uvm_error("UART_STRESS",
                    $sformatf("RX drain timed out at %0d items after overrun", d2_rx_count))
                break;
            end
            #POLL_STEP;
        end

        if (env.scoreboard != null)
            env.scoreboard.discard_d1_to_d2_pending(1'b1);

        release_after_overrun = 1'b1;
    endtask

    // -------------------------------------------------------------------------
    // One complete stress testcase
    // -------------------------------------------------------------------------
    task automatic run_stress_case(
        input int unsigned    case_id,
        input string          case_name,
        input bit [3:0]       data_bits_i,
        input bit             parity_en_i,
        input bit [1:0]       parity_mode_i,
        input bit             stop_2_i,
        input bit             flow_en_i,
        input bit [4:0]       rts_thresh_i,
        input stress_error_e  error_i,
        input bit             error_inject_i,
        input bit             fifo_full_i,
        input bit             fifo_overrun_i,
        input bit             flow_pressure_i,
        input bit             rx_irq_i,
        input bit             tx_empty_irq_i,
        input bit             err_irq_i,
        input bit             rx_full_irq_i
    );
        bit [8:0] payload_d1[DATA_COUNT];
        bit [8:0] payload_d2[DATA_COUNT];
        bit [8:0] injected_data;

        int unsigned sb_pass_before;
        int unsigned sb_fail_before;
        int unsigned sb_pass_delta;
        int unsigned sb_fail_delta;

        // Configure current case.
        cfg_data_bits       = data_bits_i;
        cfg_parity_en       = parity_en_i;
        cfg_parity_mode     = parity_mode_i;
        cfg_stop_2          = stop_2_i;
        cfg_flow_en         = flow_en_i;
        cfg_rts_thresh      = rts_thresh_i;

        active_error        = error_i;
        error_injection_enable = error_inject_i;
        fifo_full_mode      = fifo_full_i;
        fifo_overrun_mode   = fifo_overrun_i;
        fifo_pause_enable   = fifo_full_i || fifo_overrun_i || flow_pressure_i;
        flow_pressure_mode  = flow_pressure_i;

        cfg_rx_irq_en       = rx_irq_i;
        cfg_tx_empty_irq_en = tx_empty_irq_i;
        cfg_err_irq_en      = err_irq_i;
        cfg_rx_full_irq_en  = rx_full_irq_i;

        error_source_ready  = 1'b0;
        release_error_source = 1'b0;
        fifo_pause_ready    = 1'b0;
        release_fifo_pause  = 1'b0;
        release_full_source = 1'b0;
        allow_overrun_frame = 1'b0;
        release_after_overrun = 1'b0;

        d1_tx_count = 0;
        d2_tx_count = 0;
        d1_rx_count = 0;
        d2_rx_count = 0;
        d1_rx_payload_cursor = 0;
        d2_rx_payload_cursor = 0;

        case_pass = 0;
        case_fail = 0;

        // Error injection is intentionally placed in the middle portion of
        // the 50-byte stream. For the RTS pressure case, defer the injection
        // until later in the middle so source traffic can first fill RX past
        // the RTS threshold before the producer stops at the error barrier.
        if (flow_pressure_i)
            error_index = $urandom_range(31, 35);
        else
            error_index = $urandom_range(18, 32);

        // FIFO/flow events begin in the earlier-middle portion so enough data
        // remains afterward for the continuous stream and recovery phase.
        fifo_pause_after_rx = $urandom_range(8, 14);
        if (flow_pressure_i)
            // Start the flow-pressure phase before the first RHR read. This
            // gives the receiver FIFO room to rise to the RTS threshold while
            // the DUT continues accepting and shifting normal-link traffic.
            fifo_pause_after_rx = 0;
        // To prove FULL / OVERRUN, stop software draining before the first RHR
        // pop. Pausing after 8-12 reads leaves too few frames to fill a 16-entry
        // FIFO because this stress producer intentionally sends one frame at a time.
        if (fifo_full_i || fifo_overrun_i)
            fifo_pause_after_rx = 0;

        // Build randomized payloads using the exact configured width.
        for (int i = 0; i < DATA_COUNT; i++) begin
            payload_d1[i] = random_data();
            payload_d2[i] = random_data();
        end

        injected_data = random_data();

        if (env.scoreboard != null) begin
            sb_pass_before = env.scoreboard.pass_count;
            sb_fail_before = env.scoreboard.error_count;
        end
        else begin
            sb_pass_before = 0;
            sb_fail_before = 0;
        end

        stress_reset();
        configure_both();

        $display("");
        $display("============================================================");
        $display(" UART STRESS CASE %0d : %s", case_id, case_name);
        $display("============================================================");
        $display(" Mode                 : FULL_DUPLEX");
        $display(" D1->D2 data count    : %0d", DATA_COUNT);
        $display(" D2->D1 data count    : %0d", DATA_COUNT);
        $display(" Data bits            : %0d", cfg_data_bits);
        $display(" Parity               : %s", parity_name());
        $display(" Stop bits            : %0d", cfg_stop_2 ? 2 : 1);
        $display(" Flow control         : %0b", cfg_flow_en);
        $display(" RTS threshold        : %0d", cfg_rts_thresh);
        $display(" Error                : %s", error_name(active_error));
        if (error_injection_enable)
            $display(" Error midpoint       : payload index %0d + standalone malformed RX frame",
                     error_index);
        else
            $display(" Error midpoint       : N/A (FIFO-generated overrun)");
        if (fifo_pause_enable)
            $display(" FIFO/flow pause      : after %0d valid D2 RX reads", fifo_pause_after_rx);
        else
            $display(" FIFO/flow pause      : none");
        $display(" IER                  : TX_EMPTY=%0b RX=%0b ERROR=%0b RX_FULL=%0b",
                 cfg_tx_empty_irq_en,
                 cfg_rx_irq_en,
                 cfg_err_irq_en,
                 cfg_rx_full_irq_en);
        $display("============================================================");

        fork
            producer_d1(payload_d1);
            producer_d2(payload_d2);
            receiver_d1(payload_d2);
            receiver_d2(payload_d1);
            begin
                if (error_injection_enable)
                    inject_midstream_error(injected_data);
            end
            begin
                if (fifo_full_i)
                    handle_fifo_full_case();
                else if (fifo_overrun_i)
                    handle_overrun_case();
                else if (flow_pressure_i)
                    handle_flow_pressure_case();
            end
        join

        // Full-duplex streams must each have produced and consumed all 50 legal
        // data items. Any malformed injected frame is intentionally outside the
        // 50-item scoreboard transaction stream.
        stress_check("D1 transmitted all 50 legal payload items",
                     d1_tx_count == DATA_COUNT);
        stress_check("D2 transmitted all 50 legal payload items",
                     d2_tx_count == DATA_COUNT);
        stress_check("D1 received all 50 legal payload items",
                     d1_rx_count == DATA_COUNT);
        if (fifo_overrun_mode) begin
            stress_check("D2 received 49 surviving payload items after intentional overrun",
                         d2_rx_count == (DATA_COUNT - 1));
        end
        else begin
            stress_check("D2 received all 50 legal payload items",
                         d2_rx_count == DATA_COUNT);
        end

        // Explicit end-of-case scoreboard isolation. A correctly handled
        // overrun has already removed only the intentionally dropped 17th item.
        if (env.scoreboard != null)
            env.scoreboard.end_scenario_check(case_name);

        if (env.scoreboard != null) begin
            sb_pass_delta = env.scoreboard.pass_count - sb_pass_before;
            sb_fail_delta = env.scoreboard.error_count - sb_fail_before;
        end
        else begin
            sb_pass_delta = 0;
            sb_fail_delta = 0;
        end

        // TX_EMPTY is checked in the specific cases that request it. Do it
        // after the main stream so the D1 producer has reached its idle point.
        if (cfg_tx_empty_irq_en)
            check_tx_empty_irq(1'b1, "D1");

        // At the end, both RX FIFOs must have drained naturally to empty.
        begin
            bit [31:0] sr1;
            bit [31:0] sr2;
            read_sr(1'b1, sr1);
            read_sr(1'b0, sr2);
            stress_check("D1 RX FIFO empty after continuous drain", sr1[2] === 1'b1);
            stress_check("D2 RX FIFO empty after continuous drain", sr2[2] === 1'b1);
        end

        total_case_pass += case_pass + sb_pass_delta;
        total_case_fail += case_fail + sb_fail_delta;

        $display("------------------------------------------------------------");
        $display(" STRESS CASE %0d SUMMARY : %s", case_id, case_name);
        $display(" Local PASS              : %0d", case_pass);
        $display(" Local FAIL              : %0d", case_fail);
        $display(" Scoreboard PASS delta   : %0d", sb_pass_delta);
        $display(" Scoreboard FAIL delta   : %0d", sb_fail_delta);
        $display("============================================================");
    endtask

    // -------------------------------------------------------------------------
    // Main phase
    // -------------------------------------------------------------------------
    virtual task run_phase(uvm_phase phase);
        phase.raise_objection(this);

        total_case_pass = 0;
        total_case_fail = 0;

        // This stress test does not print a separate deterministic RX pair log.
        // Keep the scoreboard's per-RHR PASS messages enabled so every successful
        // APB receive/read is visible alongside THR writes and status/IRQ checks.
        // This flag controls printing only; scoreboard comparisons/counters are
        // active regardless of its value.
        if (env.scoreboard != null)
            env.scoreboard.full_duplex_pair_log = 1'b0;

        $display("");
        $display("============================================================");
        $display("              APB_UART -- STRESS TEST");
        $display("============================================================");
        $display("  8 combined full-duplex stress cases");
        $display("  50 randomized data items per side in every case");
        $display("  Mid-stream error/recovery + FIFO/flow + IRQ interactions");
        $display("  FIFO-full / overrun are intentionally limited to selected cases");
        $display("============================================================");

        // ------------------------------------------------------------------
        // Case 1
        // 7-bit + EVEN + 1 stop + FRAME ERROR + RX_FULL IRQ + FIFO FULL.
        // Flow is disabled here so RX can actually reach FIFO depth 16.
        // ------------------------------------------------------------------
        run_stress_case(
            1,
            "FULL_DUPLEX 7-bit even/1-stop + frame error + RX_FULL IRQ + FIFO FULL",
            4'd7, 1'b1, 2'b00, 1'b0,
            1'b0, 5'd14,
            STRESS_FRAME, 1'b1,
            1'b1, 1'b0, 1'b0,
            1'b0, 1'b0, 1'b0, 1'b1
        );

        // ------------------------------------------------------------------
        // Case 2
        // 8-bit + ODD + 2 stop + PARITY ERROR + RX IRQ + RTS/CTS.
        // ------------------------------------------------------------------
        run_stress_case(
            2,
            "FULL_DUPLEX 8-bit odd/2-stop + parity error + RX IRQ + RTS/CTS",
            4'd8, 1'b1, 2'b01, 1'b1,
            1'b1, 5'd14,
            STRESS_PARITY, 1'b1,
            1'b0, 1'b0, 1'b0,
            1'b1, 1'b0, 1'b0, 1'b0
        );

        // ------------------------------------------------------------------
        // Case 3
        // 9-bit + EVEN + 1 stop + BREAK + ERROR IRQ + RTS/CTS.
        // ------------------------------------------------------------------
        run_stress_case(
            3,
            "FULL_DUPLEX 9-bit even/1-stop + break error + ERROR IRQ + RTS/CTS",
            4'd9, 1'b1, 2'b00, 1'b0,
            1'b1, 5'd14,
            STRESS_BREAK, 1'b1,
            1'b0, 1'b0, 1'b0,
            1'b0, 1'b0, 1'b1, 1'b0
        );

        // ------------------------------------------------------------------
        // Case 4
        // 7-bit + ODD + 2 stop + FRAME ERROR + TX_EMPTY IRQ + RTS/CTS.
        // ------------------------------------------------------------------
        run_stress_case(
            4,
            "FULL_DUPLEX 7-bit odd/2-stop + frame error + TX_EMPTY IRQ + RTS/CTS",
            4'd7, 1'b1, 2'b01, 1'b1,
            1'b1, 5'd14,
            STRESS_FRAME, 1'b1,
            1'b0, 1'b0, 1'b0,
            1'b0, 1'b1, 1'b0, 1'b0
        );

        // ------------------------------------------------------------------
        // Case 5
        // 8-bit + MARK + 1 stop + PARITY ERROR + ERROR IRQ + RTS/CTS.
        // ------------------------------------------------------------------
        run_stress_case(
            5,
            "FULL_DUPLEX 8-bit mark/1-stop + parity error + ERROR IRQ + RTS/CTS",
            4'd8, 1'b1, 2'b10, 1'b0,
            1'b1, 5'd14,
            STRESS_PARITY, 1'b1,
            1'b0, 1'b0, 1'b0,
            1'b0, 1'b0, 1'b1, 1'b0
        );

        // ------------------------------------------------------------------
        // Case 6
        // 9-bit + SPACE + 2 stop + BREAK + RX IRQ + RX_FULL IRQ enabled.
        // Receiver is intentionally paused long enough to make RTS/CTS
        // transition, but flow control should prevent RX FIFO from reaching
        // actual FULL.
        // ------------------------------------------------------------------
        run_stress_case(
            6,
            "FULL_DUPLEX 9-bit space/2-stop + break error + RX IRQ + flow pressure",
            4'd9, 1'b1, 2'b11, 1'b1,
            1'b1, 5'd14,
            STRESS_BREAK, 1'b1,
            1'b0, 1'b0, 1'b1,
            1'b1, 1'b0, 1'b0, 1'b1
        );

        // ------------------------------------------------------------------
        // Case 7
        // 8-bit + EVEN + 1 stop + genuine RX OVERRUN + ERROR IRQ + FIFO.
        // Flow is disabled so the source continues after RX_FULL.
        // Exactly one extra normal-link frame is permitted while RX is full.
        // ------------------------------------------------------------------
        run_stress_case(
            7,
            "FULL_DUPLEX 8-bit even/1-stop + RX overrun + ERROR IRQ + FIFO OVERRUN",
            4'd8, 1'b1, 2'b00, 1'b0,
            1'b0, 5'd14,
            STRESS_OVERRUN, 1'b0,
            1'b0, 1'b1, 1'b0,
            1'b0, 1'b0, 1'b1, 1'b0
        );

        // ------------------------------------------------------------------
        // Case 8
        // 9-bit + ODD + 2 stop + PARITY ERROR + simultaneous RX/TX-empty IRQ.
        // This combines normal receive interrupt activity with the source
        // reaching TX-empty at the midpoint error barrier.
        // ------------------------------------------------------------------
        run_stress_case(
            8,
            "FULL_DUPLEX 9-bit odd/2-stop + parity error + RX/TX_EMPTY IRQ + RTS/CTS",
            4'd9, 1'b1, 2'b01, 1'b1,
            1'b1, 5'd14,
            STRESS_PARITY, 1'b1,
            1'b0, 1'b0, 1'b0,
            1'b1, 1'b1, 1'b0, 1'b0
        );

        $display("");
        $display("============================================================");
        $display("              UART STRESS TEST -- GRAND TOTAL");
        $display("============================================================");
        $display(" Cases completed : 8");
        $display(" PASS            : %0d", total_case_pass);
        $display(" FAIL            : %0d", total_case_fail);
        $display("============================================================");

        phase.drop_objection(this);
    endtask

endclass

