//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Environment: lpddr5c_env
// Instantiates every user-defined agent (each bound to its chosen
// interface group), wires its monitor to the shared scoreboard, and
// also wires it to a per-agent functional coverage collector.
// Active/passive mode is NOT set here -- see tests/base_test.sv.
class lpddr5c_env extends uvm_env;

  `uvm_component_utils(lpddr5c_env)

  lpddr5c_axi_agent axi_agent;
  lpddr5c_apb_agent apb_agent;
  lpddr5c_dfi_agent dfi_agent;
  lpddr5c_axi_agent_coverage axi_agent_cov;
  lpddr5c_apb_agent_coverage apb_agent_cov;
  lpddr5c_dfi_agent_coverage dfi_agent_cov;
  lpddr5c_scoreboard scoreboard;

  function new(string name = "lpddr5c_env", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    axi_agent = lpddr5c_axi_agent::type_id::create("axi_agent", this);
    apb_agent = lpddr5c_apb_agent::type_id::create("apb_agent", this);
    dfi_agent = lpddr5c_dfi_agent::type_id::create("dfi_agent", this);
    axi_agent_cov = lpddr5c_axi_agent_coverage::type_id::create("axi_agent_cov", this);
    apb_agent_cov = lpddr5c_apb_agent_coverage::type_id::create("apb_agent_cov", this);
    dfi_agent_cov = lpddr5c_dfi_agent_coverage::type_id::create("dfi_agent_cov", this);
    scoreboard = lpddr5c_scoreboard::type_id::create("scoreboard", this);
  endfunction

  function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    axi_agent.monitor.ap.connect(scoreboard.axi_agent_export);
    apb_agent.monitor.ap.connect(scoreboard.apb_agent_export);
    dfi_agent.monitor.ap.connect(scoreboard.dfi_agent_export);
    axi_agent.monitor.ap.connect(axi_agent_cov.analysis_export);
    apb_agent.monitor.ap.connect(apb_agent_cov.analysis_export);
    dfi_agent.monitor.ap.connect(dfi_agent_cov.analysis_export);
  endfunction

endclass : lpddr5c_env
