//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Scoreboard: lpddr5c_scoreboard
// Each agent has its own unique seq_item type, so this scoreboard
// declares one `uvm_analysis_imp_decl per agent and receives items
// via distinct write_<agent_name>() callbacks.
`uvm_analysis_imp_decl(_axi_agent)
`uvm_analysis_imp_decl(_apb_agent)
`uvm_analysis_imp_decl(_dfi_agent)

class lpddr5c_scoreboard extends uvm_scoreboard;

  `uvm_component_utils(lpddr5c_scoreboard)

  uvm_analysis_imp_axi_agent #(lpddr5c_axi_agent_seq_item, lpddr5c_scoreboard) axi_agent_export;
  uvm_analysis_imp_apb_agent #(lpddr5c_apb_agent_seq_item, lpddr5c_scoreboard) apb_agent_export;
  uvm_analysis_imp_dfi_agent #(lpddr5c_dfi_agent_seq_item, lpddr5c_scoreboard) dfi_agent_export;

  function new(string name = "lpddr5c_scoreboard", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    axi_agent_export = new("axi_agent_export", this);
    apb_agent_export = new("apb_agent_export", this);
    dfi_agent_export = new("dfi_agent_export", this);
  endfunction

  function void write_axi_agent(lpddr5c_axi_agent_seq_item t);
    // TODO: compare against a golden/reference model for agent "axi_agent"
    // (interface group "AXI").
    `uvm_info("SCBD", $sformatf("[axi_agent] Received item: %s", t.sprint()), UVM_HIGH)
  endfunction

  function void write_apb_agent(lpddr5c_apb_agent_seq_item t);
    // TODO: compare against a golden/reference model for agent "apb_agent"
    // (interface group "APB").
    `uvm_info("SCBD", $sformatf("[apb_agent] Received item: %s", t.sprint()), UVM_HIGH)
  endfunction

  function void write_dfi_agent(lpddr5c_dfi_agent_seq_item t);
    // TODO: compare against a golden/reference model for agent "dfi_agent"
    // (interface group "DFI").
    `uvm_info("SCBD", $sformatf("[dfi_agent] Received item: %s", t.sprint()), UVM_HIGH)
  endfunction

endclass : lpddr5c_scoreboard
