//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Base test: base_test
// *** Each agent's active/passive mode is toggled HERE ***, via
// uvm_resource_db, before the env (and therefore its agents) is
// created. Edit UVM_ACTIVE/UVM_PASSIVE below to change a given
// agent's mode -- no env or agent code needs to change.
class base_test extends uvm_test;

  `uvm_component_utils(base_test)

  usbh_host_env env;

  function new(string name = "base_test", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);

    // --- Agent active/passive configuration ------------------------
    uvm_resource_db#(uvm_active_passive_enum)::set({"*.", "axi4_agent"}, "is_active", UVM_ACTIVE, this);  // "axi4_agent" (axi4): flip to UVM_PASSIVE to toggle
    uvm_resource_db#(uvm_active_passive_enum)::set({"*.", "utmi_agent"}, "is_active", UVM_ACTIVE, this);  // "utmi_agent" (utmi): flip to UVM_PASSIVE to toggle
    uvm_resource_db#(uvm_active_passive_enum)::set({"*.", "reset_agent_rst_i"}, "is_active", UVM_ACTIVE, this);  // reset_agent_rst_i (rst_i)
    // -----------------------------------------------------------------

    env = usbh_host_env::type_id::create("env", this);
  endfunction

  function void end_of_elaboration_phase(uvm_phase phase);
    super.end_of_elaboration_phase(phase);
    uvm_top.print_topology();
  endfunction

endclass : base_test
