$REPO_ROOT/VERIF/uvm-1.1d/src/uvm_pkg.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/ral/plic_ral_pkg.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/ral/plic_ral_block.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/ral/plic_ral_metadata_pkg.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/interface/plic_apb_if.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/agent/apb_agent/plic_apb_item.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/ral/plic_apb_adapter.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/env/apb_env/plic_apb_predictor.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/interface/plic_reset_if.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/agent/plic_reset_agent.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/env/apb_env/plic_scoreboard.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/ral/ral_sequence/plic_ral_sequences.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/agent/apb_agent/plic_apb_sequencer.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/agent/apb_agent/plic_apb_driver.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/agent/apb_agent/plic_apb_monitor.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/agent/apb_agent/plic_apb_agent.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/env/apb_env/plic_ral_env.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/tests/plic_ral_test.sv
$REPO_ROOT/VERIF/plic_verif/plic_tb/top/plic_apb_test_top.sv
