`timescale 1ns/1ps
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Interface: lpddr5c_DFI_if
// Bundles the "DFI" signal group (24 signal(s)),
// auto-classified by AMBA naming convention (or user-assigned in the
// grouping step).
`include "uvm_macros.svh"
import uvm_pkg::*;
interface lpddr5c_DFI_if #(parameter ADDR_WIDTH        = 32,
    parameter DATA_WIDTH        = 128,      // 128-bit per beat
    parameter DFI_DATA_WIDTH    = 64,       // DFI data width per PHY
    parameter NUM_CHANNELS      = 2,
    parameter NUM_RANKS         = 1,
    parameter NUM_BANKS         = 8,
    parameter NUM_BANK_GROUPS   = 2,
    parameter ROW_WIDTH         = 16,
    parameter COL_WIDTH         = 10,
    parameter DQ_WIDTH          = 16,       // per channel
    parameter DQS_WIDTH         = 2,        // per channel
    parameter CA_WIDTH          = 6,
    parameter CS_WIDTH          = 1,
    parameter CKE_WIDTH         = 1,
    parameter CK_WIDTH          = 1,
    parameter TIMING_TCK        = 10,       // 100MHz controller clock
    parameter REFRESH_INTERVAL  = 3900,     // tREFI in ns
    parameter ECC_ENABLE        = 1,
    parameter PARITY_ENABLE     = 1)(
    input logic sys_clk
);

    logic sys_rst_n;

    logic dfi_clk;  // output
    logic dfi_rst_n;  // output
    logic [CS_WIDTH*NUM_CHANNELS-1:0] dfi_cs_n;  // output chip select dfi_cs_n = 0 → DRAM selected dfi_cs_n = 1 → DRAM not selected
    logic [CKE_WIDTH*NUM_CHANNELS-1:0] dfi_cke;  // output clock enable
    logic [CA_WIDTH*NUM_CHANNELS-1:0] dfi_ca;  // output commands/address
    logic dfi_rw;  // output                    read/write
    logic [DFI_DATA_WIDTH*NUM_CHANNELS-1:0] dfi_rddata;  // input
    logic dfi_rddata_valid;  // input
    logic [DFI_DATA_WIDTH*NUM_CHANNELS-1:0] dfi_wrdata;  // output
    logic [DFI_DATA_WIDTH/8*NUM_CHANNELS-1:0] dfi_wrdata_mask;  // output
    logic dfi_wrdata_en;  // output This indicates that dfi_wrdata is valid
     // ADD THESE
    logic [ADDR_WIDTH-1:0] dfi_cmd_addr;
    logic                  dfi_cmd_addr_valid;
    
    logic dfi_phymstr_req;  // input
    logic dfi_phymstr_ack;  // output
    logic dfi_phymstr_cs;  // output
    logic dfi_rdlvl_req;  // input
    logic dfi_rdlvl_en;  // output
    logic dfi_wrlvl_req;  // input
    logic dfi_wrlvl_en;  // output
    logic intr_init_done;  // output
    logic intr_refresh_err;  // output
    logic intr_ecc_err;  // output
    logic intr_training_err;  // output
    logic intr_parity_err;  // output
    logic [31:0] debug_bus;  // output

    clocking drv_cb @(posedge sys_clk);
        default input #1step output #1step;
        input dfi_clk;
        input dfi_rst_n;
        input dfi_cs_n;
        input dfi_cke;
        input dfi_ca;
        input dfi_rw;
        output dfi_rddata;
        output dfi_rddata_valid;
        input dfi_wrdata;
        input dfi_wrdata_mask;
        input dfi_wrdata_en;
         input dfi_cmd_addr;
    input dfi_cmd_addr_valid;
        output dfi_phymstr_req;
        input dfi_phymstr_ack;
        input dfi_phymstr_cs;
        output dfi_rdlvl_req;
        input dfi_rdlvl_en;
        output dfi_wrlvl_req;
        input dfi_wrlvl_en;
        input intr_init_done;
        input intr_refresh_err;
        input intr_ecc_err;
        input intr_training_err;
        input intr_parity_err;
        input debug_bus;
    endclocking

    clocking mon_cb @(posedge sys_clk);
        default input #1step;
        input dfi_clk;
        input dfi_rst_n;
        input dfi_cs_n;
        input dfi_cke;
        input dfi_ca;
        input dfi_rw;
        input dfi_rddata;
        input dfi_rddata_valid;
        input dfi_wrdata;
        input dfi_wrdata_mask;
        input dfi_wrdata_en;
        
         input dfi_cmd_addr;
    input dfi_cmd_addr_valid;
        input dfi_phymstr_req;
        input dfi_phymstr_ack;
        input dfi_phymstr_cs;
        input dfi_rdlvl_req;
        input dfi_rdlvl_en;
        input dfi_wrlvl_req;
        input dfi_wrlvl_en;
        input intr_init_done;
        input intr_refresh_err;
        input intr_ecc_err;
        input intr_training_err;
        input intr_parity_err;
        input debug_bus;
    endclocking

    modport DRIVER (clocking drv_cb, input sys_clk, output sys_rst_n);
    modport MONITOR (clocking mon_cb, input sys_clk, input sys_rst_n);

endinterface : lpddr5c_DFI_if
