`timescale 1ns/1ps
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Interface: lpddr5c_AXI_if
// Bundles the "AXI" signal group (25 signal(s)),
// auto-classified by AMBA naming convention (or user-assigned in the
// grouping step).
`include "uvm_macros.svh"
import uvm_pkg::*;
interface lpddr5c_AXI_if #(parameter ADDR_WIDTH        = 32,
    parameter DATA_WIDTH        = 128,      // 128-bit per beat
    parameter DFI_DATA_WIDTH    = 64,       // DFI data width per PHY
    parameter NUM_CHANNELS      = 2,
    parameter NUM_RANKS         = 1,
    parameter NUM_BANKS         = 8,
    parameter NUM_BANK_GROUPS   = 2,
    parameter ROW_WIDTH         = 16,
    parameter COL_WIDTH         = 10,
    parameter DQ_WIDTH          = 16,       // per channel
    parameter DQS_WIDTH         = 2,        // per channel
    parameter CA_WIDTH          = 6,
    parameter CS_WIDTH          = 1,
    parameter CKE_WIDTH         = 1,
    parameter CK_WIDTH          = 1,
    parameter TIMING_TCK        = 10,       // 100MHz controller clock
    parameter REFRESH_INTERVAL  = 3900,     // tREFI in ns
    parameter ECC_ENABLE        = 1,
    parameter PARITY_ENABLE     = 1)(
    input logic sys_clk
);

    logic sys_rst_n;

    logic axi_awvalid;  // input
    logic axi_awready;  // output
    logic [ADDR_WIDTH-1:0] axi_awaddr;  // input
    logic [7:0] axi_awlen;  // input
    logic [2:0] axi_awsize;  // input
    logic [1:0] axi_awburst;  // input
    logic axi_wvalid;  // input
    logic axi_wready;  // output
    logic [DATA_WIDTH-1:0] axi_wdata;  // input
    logic [DATA_WIDTH/8-1:0] axi_wstrb;  // input
    logic axi_wlast;  // input
    logic axi_bvalid;  // output
    logic axi_bready;  // input
    logic [1:0] axi_bresp;  // output
    logic axi_arvalid;  // input
    logic axi_arready;  // output
    logic [ADDR_WIDTH-1:0] axi_araddr;  // input
    logic [7:0] axi_arlen;  // input
    logic [2:0] axi_arsize;  // input
    logic [1:0] axi_arburst;  // input
    logic axi_rvalid;  // output
    logic axi_rready;  // input
    logic [DATA_WIDTH-1:0] axi_rdata;  // output
    logic [1:0] axi_rresp;  // output
    logic axi_rlast;  // output

    clocking drv_cb @(posedge sys_clk);
        default input #1step output #1step;
        output axi_awvalid;
        input axi_awready;
        output axi_awaddr;
        output axi_awlen;
        output axi_awsize;
        output axi_awburst;
        output axi_wvalid;
        input axi_wready;
        output axi_wdata;
        output axi_wstrb;
        output axi_wlast;
        input axi_bvalid;
        output axi_bready;
        input axi_bresp;
        output axi_arvalid;
        input axi_arready;
        output axi_araddr;
        output axi_arlen;
        output axi_arsize;
        output axi_arburst;
        input axi_rvalid;
        output axi_rready;
        input axi_rdata;
        input axi_rresp;
        input axi_rlast;
    endclocking

    clocking mon_cb @(posedge sys_clk);
        default input #1step;
        input axi_awvalid;
        input axi_awready;
        input axi_awaddr;
        input axi_awlen;
        input axi_awsize;
        input axi_awburst;
        input axi_wvalid;
        input axi_wready;
        input axi_wdata;
        input axi_wstrb;
        input axi_wlast;
        input axi_bvalid;
        input axi_bready;
        input axi_bresp;
        input axi_arvalid;
        input axi_arready;
        input axi_araddr;
        input axi_arlen;
        input axi_arsize;
        input axi_arburst;
        input axi_rvalid;
        input axi_rready;
        input axi_rdata;
        input axi_rresp;
        input axi_rlast;
    endclocking

    modport DRIVER (clocking drv_cb, input sys_clk, output sys_rst_n);
    modport MONITOR (clocking mon_cb, input sys_clk, input sys_rst_n);

endinterface : lpddr5c_AXI_if
