`timescale 1ns/1ps
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------
`include "uvm_macros.svh"
import uvm_pkg::*;

// Interface: lpddr5c_APB_if
// Bundles the "APB" signal group (10 signal(s)),
// auto-classified by AMBA naming convention (or user-assigned in the
// grouping step).
`timescale 1ns/1ps

interface lpddr5c_APB_if #(parameter ADDR_WIDTH        = 32,
    parameter DATA_WIDTH        = 128,      // 128-bit per beat
    parameter DFI_DATA_WIDTH    = 64,       // DFI data width per PHY
    parameter NUM_CHANNELS      = 2,
    parameter NUM_RANKS         = 1,
    parameter NUM_BANKS         = 8,
    parameter NUM_BANK_GROUPS   = 2,
    parameter ROW_WIDTH         = 16,
    parameter COL_WIDTH         = 10,
    parameter DQ_WIDTH          = 16,       // per channel
    parameter DQS_WIDTH         = 2,        // per channel
    parameter CA_WIDTH          = 6,
    parameter CS_WIDTH          = 1,
    parameter CKE_WIDTH         = 1,
    parameter CK_WIDTH          = 1,
    parameter TIMING_TCK        = 10,       // 100MHz controller clock
    parameter REFRESH_INTERVAL  = 3900,     // tREFI in ns
    parameter ECC_ENABLE        = 1,
    parameter PARITY_ENABLE     = 1)(
    
   //input logic sys_clk
    input logic pclk
);


    logic sys_rst_n;

    logic psel;  // input
    logic penable;  // input
    logic pwrite;  // input
    logic [15:0] paddr;  // input
    logic [31:0] pwdata;  // input
    logic [31:0] prdata;  // output
    logic pready;  // output
    logic pslverr;  // output
   // logic pclk;  // input
    logic preset_n;  // input

    clocking drv_cb @(posedge pclk);
        default input #1step output #1step;
        output psel;
        output penable;
        output pwrite;
        output paddr;
        output pwdata;
        input prdata;
        input pready;
        input pslverr;
        //output pclk;
        output preset_n;
    endclocking

    clocking mon_cb @(posedge pclk);
        default input #1step;
        input psel;
        input penable;
        input pwrite;
        input paddr;
        input pwdata;
        input prdata;
        input pready;
        input pslverr;
        input pclk;
        input preset_n;
    endclocking

    modport DRIVER (clocking drv_cb, input pclk, output sys_rst_n);
    modport MONITOR (clocking mon_cb, input pclk, input sys_rst_n);

endinterface : lpddr5c_APB_if
