//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Environment: usbh_host_env
// Instantiates every user-defined agent (each bound to its chosen
// interface group), wires its monitor to the shared scoreboard, and
// also wires it to a per-agent functional coverage collector.
// Also instantiates one reset_agent per distinct reset (1: rst_i).
// Active/passive mode is NOT set here -- see tests/base_test.sv.
class usbh_host_env extends uvm_env;

  `uvm_component_utils(usbh_host_env)

  usbh_host_axi4_agent axi4_agent;
  //usbh_host_utmi_agent utmi_agent;
  //usbh_host_axi4_agent_coverage axi4_agent_cov;
  //usbh_host_utmi_agent_coverage utmi_agent_cov;
  //reset_agent reset_agent_rst_i;
  //usbh_host_scoreboard scoreboard;

  function new(string name = "usbh_host_env", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    axi4_agent = usbh_host_axi4_agent::type_id::create("axi4_agent", this);
    //utmi_agent = usbh_host_utmi_agent::type_id::create("utmi_agent", this);
    //axi4_agent_cov = usbh_host_axi4_agent_coverage::type_id::create("axi4_agent_cov", this);
    //utmi_agent_cov = usbh_host_utmi_agent_coverage::type_id::create("utmi_agent_cov", this);
    //reset_agent_rst_i = reset_agent::type_id::create("reset_agent_rst_i", this);
    //scoreboard = usbh_host_scoreboard::type_id::create("scoreboard", this);
  endfunction

  /*function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    axi4_agent.monitor.ap.connect(scoreboard.axi4_agent_export);
    utmi_agent.monitor.ap.connect(scoreboard.utmi_agent_export);
    axi4_agent.monitor.ap.connect(axi4_agent_cov.analysis_export);
    utmi_agent.monitor.ap.connect(utmi_agent_cov.analysis_export);
  endfunction*/

endclass : usbh_host_env
