//==================================================================================
//  Copyright (c) 2024 Chipweave Technologies Private Limited. All rights reserved.
//  THIS PROGRAM IS AN UNPUBLISHED WORK FULLY PROTECTED BY
//  COPYRIGHT LAWS AND IS CONSIDERED A TRADE SECRET BELONGING
//  TO THE CHIPWEAVE TECHNOLOGIES PRIVATE LIMITED.
//
//  Chipweave Technologies Confidential
//==================================================================================
//  Project           				: 
//  Module            				: 
//  Primary Unit Owner                         	: 
//  Secondary Contact                           : 
//  Source [SystemVerilog|Verilog|VHDL|Other]   : 
//=================================================================================
//  Description: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
//=================================================================================
//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-09-08 04:32
// DUT module   : usbh_host
// IP name      : usbh_host
// Groups       : axi4(18 sig), utmi(13 sig)
// Agents       : axi4_agent->axi4[ACT], utmi_agent->utmi[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Scoreboard: usbh_host_scoreboard
// Each agent has its own unique seq_item type, so this scoreboard
// declares one `uvm_analysis_imp_decl per agent and receives items
// via distinct write_<agent_name>() callbacks.
`uvm_analysis_imp_decl(_axi4_agent)
`uvm_analysis_imp_decl(_utmi_agent)

class usbh_host_scoreboard extends uvm_scoreboard;

  `uvm_component_utils(usbh_host_scoreboard)

  uvm_analysis_imp_axi4_agent #(usbh_host_axi4_agent_seq_item, usbh_host_scoreboard) axi4_agent_export;
  uvm_analysis_imp_utmi_agent #(usbh_host_utmi_agent_seq_item, usbh_host_scoreboard) utmi_agent_export;

  function new(string name = "usbh_host_scoreboard", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    axi4_agent_export = new("axi4_agent_export", this);
    utmi_agent_export = new("utmi_agent_export", this);
  endfunction

  function void write_axi4_agent(usbh_host_axi4_agent_seq_item t);
    // TODO: compare against a golden/reference model for agent "axi4_agent"
    // (interface group "axi4").
    `uvm_info("SCBD", $sformatf("[axi4_agent] Received item: %s", t.sprint()), UVM_HIGH)
  endfunction

  function void write_utmi_agent(usbh_host_utmi_agent_seq_item t);
    // TODO: compare against a golden/reference model for agent "utmi_agent"
    // (interface group "utmi").
    `uvm_info("SCBD", $sformatf("[utmi_agent] Received item: %s", t.sprint()), UVM_HIGH)
  endfunction

endclass : usbh_host_scoreboard
