//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Monitor for agent "dfi_agent" -- observes interface group "DFI".
class lpddr5c_dfi_agent_monitor extends uvm_monitor;

  `uvm_component_utils(lpddr5c_dfi_agent_monitor)

  virtual lpddr5c_DFI_if vif;
  uvm_analysis_port #(lpddr5c_dfi_agent_seq_item) ap;

  function new(string name = "lpddr5c_dfi_agent_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    ap = new("ap", this);
    if (!uvm_resource_db#(virtual lpddr5c_DFI_if)::read_by_name(
            get_full_name(), "vif", vif, this))
      `uvm_fatal("NOVIF", $sformatf("[%s] Virtual interface not found in resource_db", get_full_name()))
  endfunction

  task run_phase(uvm_phase phase);
    lpddr5c_dfi_agent_seq_item item;
    forever begin
      @(vif.mon_cb);
      item = lpddr5c_dfi_agent_seq_item::type_id::create("item");
      item.dfi_clk = vif.mon_cb.dfi_clk;
      item.dfi_rst_n = vif.mon_cb.dfi_rst_n;
      item.dfi_cs_n = vif.mon_cb.dfi_cs_n;
      item.dfi_cke = vif.mon_cb.dfi_cke;
      item.dfi_ca = vif.mon_cb.dfi_ca;
      item.dfi_rw = vif.mon_cb.dfi_rw;
      item.dfi_rddata = vif.mon_cb.dfi_rddata;
      item.dfi_rddata_valid = vif.mon_cb.dfi_rddata_valid;
      item.dfi_wrdata = vif.mon_cb.dfi_wrdata;
      item.dfi_wrdata_mask = vif.mon_cb.dfi_wrdata_mask;
      item.dfi_wrdata_en = vif.mon_cb.dfi_wrdata_en;
      item.dfi_phymstr_req = vif.mon_cb.dfi_phymstr_req;
      item.dfi_phymstr_ack = vif.mon_cb.dfi_phymstr_ack;
      item.dfi_phymstr_cs = vif.mon_cb.dfi_phymstr_cs;
      item.dfi_rdlvl_req = vif.mon_cb.dfi_rdlvl_req;
      item.dfi_rdlvl_en = vif.mon_cb.dfi_rdlvl_en;
      item.dfi_wrlvl_req = vif.mon_cb.dfi_wrlvl_req;
      item.dfi_wrlvl_en = vif.mon_cb.dfi_wrlvl_en;
      item.intr_init_done = vif.mon_cb.intr_init_done;
      item.intr_refresh_err = vif.mon_cb.intr_refresh_err;
      item.intr_ecc_err = vif.mon_cb.intr_ecc_err;
      item.intr_training_err = vif.mon_cb.intr_training_err;
      item.intr_parity_err = vif.mon_cb.intr_parity_err;
      item.debug_bus = vif.mon_cb.debug_bus;
      // TODO: gate on a valid/done condition specific to "DFI".
      ap.write(item);
    end
  endtask

endclass : lpddr5c_dfi_agent_monitor
