//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Driver for agent "dfi_agent" -- drives interface group "DFI".
class lpddr5c_dfi_agent_driver extends uvm_driver #(lpddr5c_dfi_agent_seq_item);

  `uvm_component_utils(lpddr5c_dfi_agent_driver)

  virtual lpddr5c_DFI_if vif;

  function new(string name = "lpddr5c_dfi_agent_driver", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_resource_db#(virtual lpddr5c_DFI_if)::read_by_name(
            get_full_name(), "vif", vif, this))
      `uvm_fatal("NOVIF", $sformatf("[%s] Virtual interface not found in resource_db", get_full_name()))
  endfunction

  task run_phase(uvm_phase phase);
    forever begin
      seq_item_port.get_next_item(req);
      drive_item(req);
      seq_item_port.item_done();
    end
  endtask

  task drive_item(lpddr5c_dfi_agent_seq_item req);
    @(vif.drv_cb);
      vif.drv_cb.dfi_rddata <= req.dfi_rddata;
      vif.drv_cb.dfi_rddata_valid <= req.dfi_rddata_valid;
      vif.drv_cb.dfi_phymstr_req <= req.dfi_phymstr_req;
      vif.drv_cb.dfi_rdlvl_req <= req.dfi_rdlvl_req;
      vif.drv_cb.dfi_wrlvl_req <= req.dfi_wrlvl_req;
    // TODO: add protocol handshake wait specific to "DFI".
  endtask

endclass : lpddr5c_dfi_agent_driver
