//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Sequence item for agent "dfi_agent" (bound to interface group "DFI").
class lpddr5c_dfi_agent_seq_item extends uvm_sequence_item;

       bit dfi_clk;
       bit dfi_rst_n;
       bit dfi_cs_n;
       bit dfi_cke;
       bit dfi_ca;
       bit dfi_rw;
  rand bit dfi_rddata;
  rand bit dfi_rddata_valid;
       bit dfi_wrdata;
       bit dfi_wrdata_mask;
       bit dfi_wrdata_en;
       
  rand bit dfi_phymstr_req;
       bit dfi_phymstr_ack;
       bit dfi_phymstr_cs;
  rand bit dfi_rdlvl_req;
       bit dfi_rdlvl_en;
  rand bit dfi_wrlvl_req;
       bit dfi_wrlvl_en;
       bit intr_init_done;
       bit intr_refresh_err;
       bit intr_ecc_err;
       bit intr_training_err;
       bit intr_parity_err;
       bit [31:0] debug_bus;

  `uvm_object_utils_begin(lpddr5c_dfi_agent_seq_item)
    `uvm_field_int(dfi_clk, UVM_ALL_ON)
    `uvm_field_int(dfi_rst_n, UVM_ALL_ON)
    `uvm_field_int(dfi_cs_n, UVM_ALL_ON)
    `uvm_field_int(dfi_cke, UVM_ALL_ON)
    `uvm_field_int(dfi_ca, UVM_ALL_ON)
    `uvm_field_int(dfi_rw, UVM_ALL_ON)
    `uvm_field_int(dfi_rddata, UVM_ALL_ON)
    `uvm_field_int(dfi_rddata_valid, UVM_ALL_ON)
    `uvm_field_int(dfi_wrdata, UVM_ALL_ON)
    `uvm_field_int(dfi_wrdata_mask, UVM_ALL_ON)
    `uvm_field_int(dfi_wrdata_en, UVM_ALL_ON)
    `uvm_field_int(dfi_phymstr_req, UVM_ALL_ON)
    `uvm_field_int(dfi_phymstr_ack, UVM_ALL_ON)
    `uvm_field_int(dfi_phymstr_cs, UVM_ALL_ON)
    `uvm_field_int(dfi_rdlvl_req, UVM_ALL_ON)
    `uvm_field_int(dfi_rdlvl_en, UVM_ALL_ON)
    `uvm_field_int(dfi_wrlvl_req, UVM_ALL_ON)
    `uvm_field_int(dfi_wrlvl_en, UVM_ALL_ON)
    `uvm_field_int(intr_init_done, UVM_ALL_ON)
    `uvm_field_int(intr_refresh_err, UVM_ALL_ON)
    `uvm_field_int(intr_ecc_err, UVM_ALL_ON)
    `uvm_field_int(intr_training_err, UVM_ALL_ON)
    `uvm_field_int(intr_parity_err, UVM_ALL_ON)
    `uvm_field_int(debug_bus, UVM_ALL_ON)
  `uvm_object_utils_end

  function new(string name = "lpddr5c_dfi_agent_seq_item");
    super.new(name);
  endfunction

  constraint c_default {
    // TODO: add constraints specific to agent "dfi_agent"
  }

endclass : lpddr5c_dfi_agent_seq_item
