//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Functional coverage collector for agent "dfi_agent" (interface group
// "DFI"). Implemented as a uvm_subscriber so it plugs
// directly into the monitor's existing analysis port (ap.connect) with
// no extra TLM export declarations needed.
class lpddr5c_dfi_agent_coverage extends uvm_subscriber #(lpddr5c_dfi_agent_seq_item);

  `uvm_component_utils(lpddr5c_dfi_agent_coverage)

  lpddr5c_dfi_agent_seq_item item;

  covergroup cg_dfi_agent;
    option.per_instance = 1;
    option.name = $sformatf("%s_cg_dfi_agent", get_full_name());
    cp_dfi_clk: coverpoint item.dfi_clk;  // 1-bit -- auto bins (0/1)
    cp_dfi_rst_n: coverpoint item.dfi_rst_n;  // 1-bit -- auto bins (0/1)
    cp_dfi_cs_n: coverpoint item.dfi_cs_n;  // 1-bit -- auto bins (0/1)
    cp_dfi_cke: coverpoint item.dfi_cke;  // 1-bit -- auto bins (0/1)
    cp_dfi_ca: coverpoint item.dfi_ca;  // 1-bit -- auto bins (0/1)
    cp_dfi_rw: coverpoint item.dfi_rw;  // 1-bit -- auto bins (0/1)
    cp_dfi_rddata: coverpoint item.dfi_rddata;  // 1-bit -- auto bins (0/1)
    cp_dfi_rddata_valid: coverpoint item.dfi_rddata_valid;  // 1-bit -- auto bins (0/1)
    cp_dfi_wrdata: coverpoint item.dfi_wrdata;  // 1-bit -- auto bins (0/1)
    cp_dfi_wrdata_mask: coverpoint item.dfi_wrdata_mask;  // 1-bit -- auto bins (0/1)
    cp_dfi_wrdata_en: coverpoint item.dfi_wrdata_en;  // 1-bit -- auto bins (0/1)
    cp_dfi_phymstr_req: coverpoint item.dfi_phymstr_req;  // 1-bit -- auto bins (0/1)
    cp_dfi_phymstr_ack: coverpoint item.dfi_phymstr_ack;  // 1-bit -- auto bins (0/1)
    cp_dfi_phymstr_cs: coverpoint item.dfi_phymstr_cs;  // 1-bit -- auto bins (0/1)
    cp_dfi_rdlvl_req: coverpoint item.dfi_rdlvl_req;  // 1-bit -- auto bins (0/1)
    cp_dfi_rdlvl_en: coverpoint item.dfi_rdlvl_en;  // 1-bit -- auto bins (0/1)
    cp_dfi_wrlvl_req: coverpoint item.dfi_wrlvl_req;  // 1-bit -- auto bins (0/1)
    cp_dfi_wrlvl_en: coverpoint item.dfi_wrlvl_en;  // 1-bit -- auto bins (0/1)
    cp_intr_init_done: coverpoint item.intr_init_done;  // 1-bit -- auto bins (0/1)
    cp_intr_refresh_err: coverpoint item.intr_refresh_err;  // 1-bit -- auto bins (0/1)
    cp_intr_ecc_err: coverpoint item.intr_ecc_err;  // 1-bit -- auto bins (0/1)
    cp_intr_training_err: coverpoint item.intr_training_err;  // 1-bit -- auto bins (0/1)
    cp_intr_parity_err: coverpoint item.intr_parity_err;  // 1-bit -- auto bins (0/1)
    cp_debug_bus: coverpoint item.debug_bus {
      bins zero    = {0};
      bins nonzero = {[1:$]};
      // TODO: replace with meaningful range/boundary bins for 'debug_bus'
    }
    cx_dfi_clk_dfi_rst_n: cross cp_dfi_clk, cp_dfi_rst_n;  // TODO: prune/expand as needed

  endgroup

  function new(string name = "lpddr5c_dfi_agent_coverage", uvm_component parent = null);
    super.new(name, parent);
    cg_dfi_agent = new();
  endfunction

  function void write(lpddr5c_dfi_agent_seq_item t);
    item = t;
    cg_dfi_agent.sample();
  endfunction

  function void report_phase(uvm_phase phase);
    super.report_phase(phase);
    `uvm_info("COV", $sformatf("[%s] Coverage = %0.2f%%", get_full_name(),
              cg_dfi_agent.get_coverage()), UVM_LOW)
  endfunction

endclass : lpddr5c_dfi_agent_coverage
