//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Sequence item for agent "apb_agent" (bound to interface group "APB").
class lpddr5c_apb_agent_seq_item extends uvm_sequence_item;

  rand bit psel;
  rand bit penable;
  rand bit pwrite;
  rand bit [15:0] paddr;
  rand bit [31:0] pwdata;
       bit [31:0] prdata;
       bit pready;
       bit pslverr;
  rand bit pclk;
  rand bit preset_n;

  `uvm_object_utils_begin(lpddr5c_apb_agent_seq_item)
    `uvm_field_int(psel, UVM_ALL_ON)
    `uvm_field_int(penable, UVM_ALL_ON)
    `uvm_field_int(pwrite, UVM_ALL_ON)
    `uvm_field_int(paddr, UVM_ALL_ON)
    `uvm_field_int(pwdata, UVM_ALL_ON)
    `uvm_field_int(prdata, UVM_ALL_ON)
    `uvm_field_int(pready, UVM_ALL_ON)
    `uvm_field_int(pslverr, UVM_ALL_ON)
    `uvm_field_int(pclk, UVM_ALL_ON)
    `uvm_field_int(preset_n, UVM_ALL_ON)
  `uvm_object_utils_end

  function new(string name = "lpddr5c_apb_agent_seq_item");
    super.new(name);
  endfunction

  constraint c_default {
    // TODO: add constraints specific to agent "apb_agent"
  }

endclass : lpddr5c_apb_agent_seq_item
