//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Monitor for agent "apb_agent" -- observes interface group "APB".
class lpddr5c_apb_agent_monitor extends uvm_monitor;

  `uvm_component_utils(lpddr5c_apb_agent_monitor)

  virtual lpddr5c_APB_if vif;
  uvm_analysis_port #(lpddr5c_apb_agent_seq_item) ap;

  function new(string name = "lpddr5c_apb_agent_monitor", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    ap = new("ap", this);
    if (!uvm_resource_db#(virtual lpddr5c_APB_if)::read_by_name(
            get_full_name(), "vif", vif, this))
      `uvm_fatal("NOVIF", $sformatf("[%s] Virtual interface not found in resource_db", get_full_name()))
  endfunction

  task run_phase(uvm_phase phase);
    lpddr5c_apb_agent_seq_item item;
    forever begin
      @(vif.mon_cb);
      item = lpddr5c_apb_agent_seq_item::type_id::create("item");
      item.psel = vif.mon_cb.psel;
      item.penable = vif.mon_cb.penable;
      item.pwrite = vif.mon_cb.pwrite;
      item.paddr = vif.mon_cb.paddr;
      item.pwdata = vif.mon_cb.pwdata;
      item.prdata = vif.mon_cb.prdata;
      item.pready = vif.mon_cb.pready;
      item.pslverr = vif.mon_cb.pslverr;
      item.pclk = vif.mon_cb.pclk;
      item.preset_n = vif.mon_cb.preset_n;
      // TODO: gate on a valid/done condition specific to "APB".
      ap.write(item);
    end
  endtask

endclass : lpddr5c_apb_agent_monitor
