//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Agent "apb_agent" -- unique agent shell bound to interface group
// "APB". Active/passive mode is set by tests/base_test.sv
// via uvm_resource_db, scoped by this agent's instance name.
class lpddr5c_apb_agent extends uvm_agent;

  `uvm_component_utils(lpddr5c_apb_agent)

  lpddr5c_apb_agent_driver    driver;
  lpddr5c_apb_agent_sequencer sequencer;
  lpddr5c_apb_agent_monitor   monitor;
  virtual lpddr5c_APB_if         vif;

  function new(string name = "lpddr5c_apb_agent", uvm_component parent = null);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    uvm_active_passive_enum mode;
    super.build_phase(phase);

    if (!uvm_resource_db#(virtual lpddr5c_APB_if)::read_by_name(
            get_full_name(), "vif", vif, this))
      `uvm_fatal("NOVIF", $sformatf("[%s] Virtual interface not found in resource_db", get_full_name()))

    if (!uvm_resource_db#(uvm_active_passive_enum)::read_by_name(
            get_full_name(), "is_active", mode, this)) begin
      `uvm_warning("NOMODE", $sformatf(
          "[%s] No is_active resource found from test -- defaulting to UVM_PASSIVE",
          get_full_name()))
      mode = UVM_PASSIVE;
    end
    is_active = mode;

    uvm_resource_db#(virtual lpddr5c_APB_if)::set(
        {get_full_name(), ".*"}, "vif", vif, this);

    monitor = lpddr5c_apb_agent_monitor::type_id::create("monitor", this);

    if (is_active == UVM_ACTIVE) begin
      driver    = lpddr5c_apb_agent_driver::type_id::create("driver", this);
      sequencer = lpddr5c_apb_agent_sequencer::type_id::create("sequencer", this);
    end
  endfunction

  function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    if (is_active == UVM_ACTIVE)
      driver.seq_item_port.connect(sequencer.seq_item_export);
  endfunction

endclass : lpddr5c_apb_agent
