//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Functional coverage collector for agent "apb_agent" (interface group
// "APB"). Implemented as a uvm_subscriber so it plugs
// directly into the monitor's existing analysis port (ap.connect) with
// no extra TLM export declarations needed.
class lpddr5c_apb_agent_coverage extends uvm_subscriber #(lpddr5c_apb_agent_seq_item);

  `uvm_component_utils(lpddr5c_apb_agent_coverage)

  lpddr5c_apb_agent_seq_item item;

  covergroup cg_apb_agent;
    option.per_instance = 1;
    option.name = $sformatf("%s_cg_apb_agent", get_full_name());
    cp_psel: coverpoint item.psel;  // 1-bit -- auto bins (0/1)
    cp_penable: coverpoint item.penable;  // 1-bit -- auto bins (0/1)
    cp_pwrite: coverpoint item.pwrite;  // 1-bit -- auto bins (0/1)
    cp_paddr: coverpoint item.paddr {
      bins zero    = {0};
      bins nonzero = {[1:$]};
      // TODO: replace with meaningful range/boundary bins for 'paddr'
    }
    cp_pwdata: coverpoint item.pwdata {
      bins zero    = {0};
      bins nonzero = {[1:$]};
      // TODO: replace with meaningful range/boundary bins for 'pwdata'
    }
    cp_prdata: coverpoint item.prdata {
      bins zero    = {0};
      bins nonzero = {[1:$]};
      // TODO: replace with meaningful range/boundary bins for 'prdata'
    }
    cp_pready: coverpoint item.pready;  // 1-bit -- auto bins (0/1)
    cp_pslverr: coverpoint item.pslverr;  // 1-bit -- auto bins (0/1)
    cp_pclk: coverpoint item.pclk;  // 1-bit -- auto bins (0/1)
    cp_preset_n: coverpoint item.preset_n;  // 1-bit -- auto bins (0/1)
    cx_psel_penable: cross cp_psel, cp_penable;  // TODO: prune/expand as needed

  endgroup

  function new(string name = "lpddr5c_apb_agent_coverage", uvm_component parent = null);
    super.new(name, parent);
    cg_apb_agent = new();
  endfunction

  function void write(lpddr5c_apb_agent_seq_item t);
    item = t;
    cg_apb_agent.sample();
  endfunction

  function void report_phase(uvm_phase phase);
    super.report_phase(phase);
    `uvm_info("COV", $sformatf("[%s] Coverage = %0.2f%%", get_full_name(),
              cg_apb_agent.get_coverage()), UVM_LOW)
  endfunction

endclass : lpddr5c_apb_agent_coverage
