# ==========================================
# Caliptra
# ==========================================
$REPO_ROOT/DSN/ip/caliptra/rtl/src/integration/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/integration/rtl/caliptra_reg
$REPO_ROOT/DSN/ip/caliptra/rtl/src/libs/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/keyvault/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/pcrvault/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/datavault/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/include
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ahb_lite_bus/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/lc_ctrl/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/edn/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim_generic/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha256/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512_masked/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/hmac/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/hmac_drbg/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/kmac/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_combiner/rtl


$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_top/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_sampler_top/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim_generic/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/rej_bounded/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/rej_sampler/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/exp_mask/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sample_in_ball/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/cbd_sampler/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_sha3/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/barrett_reduction/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompose/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sk_decode/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sk_encode/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/makehint/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/norm_check/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sig_encode_z/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sigdecode_h/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sig_decode_z/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/pk_decode/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/power2round/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/compress/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompress/rtl
