# ==========================================
# Caliptra
# ==========================================
$REPO_ROOT/DSN/ip/caliptra/rtl/src/integration/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/integration/rtl/caliptra_reg
$REPO_ROOT/DSN/ip/caliptra/rtl/src/libs/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/keyvault/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/pcrvault/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/datavault/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/include
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ahb_lite_bus/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/lc_ctrl/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/edn/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim_generic/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha256/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512_masked/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/hmac/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/hmac_drbg/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/kmac/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_combiner/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_top/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_sampler_top/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim_generic/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/rej_bounded/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/rej_sampler/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/exp_mask/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sample_in_ball/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/cbd_sampler/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_sha3/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/barrett_reduction/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompose/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sk_decode/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sk_encode/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/makehint/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/norm_check/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sig_encode_z/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sigdecode_h/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sig_decode_z/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/pk_decode/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/power2round/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/compress/rtl
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompress/rtl


$REPO_ROOT/DSN/ip/caliptra/rtl/src/integration/rtl/config_defines.svh
$REPO_ROOT/DSN/ip/caliptra/rtl/src/integration/rtl/caliptra_reg/caliptra_reg_defines.svh
$REPO_ROOT/DSN/ip/caliptra/rtl/src/libs/rtl/caliptra_sram.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/libs/rtl/ahb_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/libs/rtl/caliptra_ahb_srom.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/libs/rtl/ahb_slv_sif.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/libs/rtl/caliptra_icg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/libs/rtl/clk_gate.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/libs/rtl/caliptra_2ff_sync.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/libs/rtl/ahb_to_reg_adapter.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/libs/rtl/skidbuffer.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/keyvault/rtl/kv_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/pcrvault/rtl/pv_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/pcrvault/rtl/pv_gen_hash.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/datavault/rtl/dv_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/include/el2_def.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/common_defines.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lib/beh_lib.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/dbg/el2_dbg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/dec/el2_dec_decode_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/dec/el2_dec_gpr_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/dec/el2_dec_ib_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/dec/el2_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/dec/el2_dec_tlu_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/dec/el2_dec_trigger.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/dec/el2_dec_pmp_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/dmi/dmi_mux.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/dmi/dmi_jtag_to_core_sync.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/dmi/dmi_wrapper.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/dmi/rvjtag_tap.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/exu/el2_exu_alu_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/exu/el2_exu_div_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/exu/el2_exu_mul_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/exu/el2_exu.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/ifu/el2_ifu_aln_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/ifu/el2_ifu_bp_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/ifu/el2_ifu_compress_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/ifu/el2_ifu_iccm_mem.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/ifu/el2_ifu_ic_mem.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/ifu/el2_ifu_ifc_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/ifu/el2_ifu_mem_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/ifu/el2_ifu.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lib/ahb_to_axi4.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lib/axi4_to_ahb.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lib/el2_lib.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lib/mem_lib.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lib/el2_mem_if.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lsu/el2_lsu_addrcheck.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lsu/el2_lsu_bus_buffer.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lsu/el2_lsu_bus_intf.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lsu/el2_lsu_clkdomain.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lsu/el2_lsu_dccm_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lsu/el2_lsu_dccm_mem.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lsu/el2_lsu_ecc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lsu/el2_lsu_lsc_ctl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lsu/el2_lsu_stbuf.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lsu/el2_lsu.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/lsu/el2_lsu_trigger.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/el2_mem.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/el2_dma_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/el2_pic_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/el2_pmp.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/el2_veer.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/riscv_core/veer_el2/rtl/el2_veer_wrapper.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ahb_lite_bus/rtl/ahb_lite_bus_inf.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ahb_lite_bus/rtl/ahb_lite_address_decoder.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ahb_lite_bus/rtl/ahb_lite_bus.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ahb_lite_bus/rtl/ahb_lite_2to1_mux.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_util_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_alert_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_subreg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_mubi_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_cipher_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_sparse_fsm_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_trivium_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_otp_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_ram_1p_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_esc_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_count_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/keymgr_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/lc_ctrl/rtl/lc_ctrl_state_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/lc_ctrl/rtl/lc_ctrl_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_main_sm_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_ack_sm_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl/csrng_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl/csrng_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/edn/rtl/edn_pkg.sv
${CALIPTRA_PRIM_ROOT}/rtl/${CALIPTRA_PRIM_MODULE_PREFIX}_flop_en.sv
${CALIPTRA_PRIM_ROOT}/rtl/${CALIPTRA_PRIM_MODULE_PREFIX}_flop.sv
${CALIPTRA_PRIM_ROOT}/rtl/${CALIPTRA_PRIM_MODULE_PREFIX}_buf.sv
${CALIPTRA_PRIM_ROOT}/rtl/${CALIPTRA_PRIM_MODULE_PREFIX}_ram_1p.sv
${CALIPTRA_PRIM_ROOT}/rtl/${CALIPTRA_PRIM_MODULE_PREFIX}_and2.sv
${CALIPTRA_PRIM_ROOT}/rtl/${CALIPTRA_PRIM_MODULE_PREFIX}_clock_mux2.sv
${CALIPTRA_PRIM_ROOT}/rtl/${CALIPTRA_PRIM_MODULE_PREFIX}_clock_inv.sv
${CALIPTRA_PRIM_ROOT}/rtl/${CALIPTRA_PRIM_MODULE_PREFIX}_xor2.sv
${CALIPTRA_PRIM_ROOT}/rtl/${CALIPTRA_PRIM_MODULE_PREFIX}_xnor2.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_flop_en.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_cdc_rand_delay.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_flop_2sync.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_lfsr.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_double_lfsr.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_arbiter_fixed.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_arbiter_tree.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_edn_req.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_present.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_lc_sender.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_sync_reqack.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_sync_reqack_data.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_mubi4_sync.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_diff_decode.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_sec_anchor_buf.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_slicer.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_count.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_sparse_fsm_flop.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_dom_and_2share.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_sec_anchor_flop.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_reg_we_check.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_packer_fifo.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_max_tree.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_subreg_arb.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_subreg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_intr_hw.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_onehot_check.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_onehot_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_onehot_mux.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_mubi8_sync.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_mubi8_sender.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_fifo_sync_cnt.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_buf.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_lc_sync.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_alert_receiver.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_flop.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_alert_sender.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_fifo_sync.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_arbiter_ppc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_sum_tree.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_subreg_ext.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_edge_detector.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_trivium.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_blanker.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_ram_1p_adv.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_mubi4_sender.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_packer.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_subreg_shadow.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_esc_receiver.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_mubi4_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_clock_mux2.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_fifo_async.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_fifo_async_simple.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_gf_mult.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/keyvault/rtl/kv_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/keyvault/rtl/kv_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/keyvault/rtl/kv.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/keyvault/rtl/kv_fsm.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/keyvault/rtl/kv_read_client.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/keyvault/rtl/kv_write_client.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/keyvault/rtl/kv_read_rule_check.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/keyvault/rtl/kv_write_rule_check.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/pcrvault/rtl/pv_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/pcrvault/rtl/pv_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/pcrvault/rtl/pv.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512/rtl/sha512_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512/rtl/sha512_params_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512/rtl/sha512_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512/rtl/sha512.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512/rtl/sha512_core.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512/rtl/sha512_h_constants.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512/rtl/sha512_k_constants.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512/rtl/sha512_w_mem.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512/rtl/sha512_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha256/rtl/sha256_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha256/rtl/sha256_params_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha256/rtl/sha256_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha256/rtl/sha256.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha256/rtl/sha256_core.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha256/rtl/sha256_k_constants.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha256/rtl/sha256_w_mem.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha256/rtl/sha256_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl/doe_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl/doe_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl/doe_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl/doe_decipher_block.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl/doe_encipher_block.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl/doe_inv_sbox.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl/doe_key_mem.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl/doe_sbox.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl/doe_cbc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl/doe_core_cbc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl/doe_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/doe/rtl/doe_fsm.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512_masked/rtl/sha512_masked_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512_masked/rtl/sha512_masked_core.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha512_masked/rtl/sha512_masked_w_mem.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/hmac/rtl/hmac_param_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/hmac/rtl/hmac_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/hmac/rtl/hmac_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/hmac/rtl/hmac.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/hmac/rtl/hmac_core.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/hmac/rtl/hmac_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/hmac_drbg/rtl/hmac_drbg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_params_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_dsa_uop_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_pm_uop_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_dsa_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_dsa_sequencer.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_scalar_blinding.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_hmac_drbg_interface.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_arith_unit.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_pm_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_pm_sequencer.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_ram_tdp_file.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_fau.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_montgomerymultiplier.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_pe_first.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_pe.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_pe_final.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_mult_dsp.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_add_sub_mod_alter.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/ecc/rtl/ecc_adder.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_top/rtl/abr_params_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_top/rtl/abr_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_sampler_top/rtl/abr_sampler_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_top/rtl/abr_ctrl_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl/ntt_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_1r1w_ram.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_1r1w_be_ram.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_1r1w_512x4_ram.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_ram_regout.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_icg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_2ff_sync.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_piso_multi.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_piso.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_sample_buffer.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_msg_buffer.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_rd_lat_buffer.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_ahb_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_ahb_slv_sif.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_adder.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_add_sub_mod.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_ntt_add_sub_mod.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_splitter.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_libs/rtl/abr_recombiner.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_util_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_alert_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_subreg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_mubi_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_cipher_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_sparse_fsm_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim_generic/rtl/abr_prim_generic_flop_en.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim_generic/rtl/abr_prim_generic_flop.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim_generic/rtl/abr_prim_generic_buf.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim_generic/rtl/abr_prim_generic_xor2.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_flop_en.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_cdc_rand_delay.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_flop_2sync.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_lfsr.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_mubi4_sync.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_diff_decode.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_sec_anchor_buf.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_slicer.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_count.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_sparse_fsm_flop.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_dom_and_2share.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_sec_anchor_flop.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_reg_we_check.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_packer_fifo.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_max_tree.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_subreg_arb.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_subreg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_intr_hw.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_onehot_check.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_mubi8_sync.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_fifo_sync_cnt.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_buf.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_alert_receiver.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_flop.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_alert_sender.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_fifo_sync.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_arbiter_ppc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_sum_tree.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_subreg_ext.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_prim/rtl/abr_prim_edge_detector.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/rej_bounded/rtl/rej_bounded_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/rej_bounded/rtl/rej_bounded2.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/rej_sampler/rtl/rej_sampler_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/rej_sampler/rtl/rej_sampler.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/exp_mask/rtl/exp_mask_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/exp_mask/rtl/exp_mask.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sample_in_ball/rtl/sample_in_ball_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sample_in_ball/rtl/sib_mem.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sample_in_ball/rtl/sample_in_ball_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sample_in_ball/rtl/sample_in_ball_shuffler.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sample_in_ball/rtl/sample_in_ball.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/cbd_sampler/rtl/cbd_sampler_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/cbd_sampler/rtl/cbd_sampler.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_sha3/rtl/abr_sha3_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_sha3/rtl/abr_keccak_round.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_sha3/rtl/abr_keccak_2share.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_sha3/rtl/abr_sha3pad.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_sha3/rtl/abr_sha3.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_sampler_top/rtl/abr_sampler_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/barrett_reduction/rtl/barrett_reduction.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl/ntt_butterfly.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl/ntt_mult_dsp.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl/ntt_div2.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl/ntt_buffer.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl/ntt_shuffle_buffer.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl/ntt_twiddle_lookup.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl/ntt_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl/ntt_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl/ntt_hybrid_butterfly_2x2.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/ntt_top/rtl/ntt_karatsuba_pairwm.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompose/rtl/decompose_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompose/rtl/decompose.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompose/rtl/decompose_r1_lut.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompose/rtl/decompose_w1_mem.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompose/rtl/decompose_mod_2gamma2.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompose/rtl/decompose_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompose/rtl/decompose_w1_encode.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompose/rtl/decompose_usehint.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sk_decode/rtl/skdecode_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sk_encode/rtl/skencode.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sk_decode/rtl/skdecode_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sk_decode/rtl/skdecode_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sk_decode/rtl/skdecode_s1s2_unpack.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sk_decode/rtl/skdecode_t0_unpack.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/makehint/rtl/makehint_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/makehint/rtl/hintgen.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/makehint/rtl/makehint.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/norm_check/rtl/norm_check_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/norm_check/rtl/norm_check.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/norm_check/rtl/norm_check_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/norm_check/rtl/norm_check_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sig_encode_z/rtl/sigencode_z_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sig_encode_z/rtl/sigencode_z_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sig_encode_z/rtl/sigencode_z_unit.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sigdecode_h/rtl/sigdecode_h_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sigdecode_h/rtl/sigdecode_h.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sigdecode_h/rtl/sigdecode_h_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sig_decode_z/rtl/sigdecode_z_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sig_decode_z/rtl/sigdecode_z_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/sig_decode_z/rtl/sigdecode_z_unit.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/pk_decode/rtl/pkdecode.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/power2round/rtl/power2round_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/power2round/rtl/power2round_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/power2round/rtl/power2round_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/power2round/rtl/power2round_core.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/power2round/rtl/power2round_skencode.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/compress/rtl/compress_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/compress/rtl/compress_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/compress/rtl/compress.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/compress/rtl/compress_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompress/rtl/decompress_defines_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompress/rtl/decompress_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompress/rtl/decompress.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/decompress/rtl/decompress_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_top/rtl/abr_mem_if.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_top/rtl/abr_mem_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_top/rtl/abr_seq.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_top/rtl/abr_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_top/rtl/abr_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/submodules/adams-bridge/src/abr_top/rtl/abr_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/datavault/rtl/dv_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/datavault/rtl/dv_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/datavault/rtl/dv.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_if.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_addr.v
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_sub_rd.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_sub_wr.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_sub_arb.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_sub.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/soc_ifc_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/mbox_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/mbox_csr_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/sha512_acc_csr_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/soc_ifc_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_dma_req_if.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_dma_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_dma_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_mgr_rd.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_mgr_wr.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_dma_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/axi/rtl/axi_dma_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/soc_ifc_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/soc_ifc_boot_fsm.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/soc_ifc_arb.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/soc_ifc_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/mbox.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/mbox_csr.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/sha512_acc_iccm_hash.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/sha512_acc_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/sha512_acc_csr.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/soc_ifc/rtl/wdt.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/kmac/rtl/sha3_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/kmac/rtl/keccak_round.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/kmac/rtl/keccak_2share.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/kmac/rtl/sha3pad.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/kmac/rtl/sha3.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_reg_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_bucket_ht.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_cntr_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_enable_delay.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_markov_ht.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_watermark_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_main_sm.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_repcnts_ht.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_adaptp_ht.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_core.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_repcnt_ht.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src_ack_sm.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_src/rtl/entropy_src.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_sbox_canright_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_clp_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_22_16_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_22_16_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_28_22_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_28_22_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_39_32_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_39_32_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_64_57_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_64_57_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_72_64_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_72_64_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_hamming_22_16_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_hamming_22_16_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_hamming_39_32_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_hamming_39_32_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_hamming_72_64_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_hamming_72_64_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_hamming_76_68_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_hamming_76_68_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_22_16_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_22_16_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_28_22_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_28_22_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_39_32_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_39_32_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_64_57_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_64_57_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_72_64_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_72_64_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_hamming_22_16_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_hamming_22_16_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_hamming_39_32_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_hamming_39_32_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_hamming_72_64_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_hamming_72_64_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_hamming_76_68_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_prim/rtl/caliptra_prim_secded_inv_hamming_76_68_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_adapter_vh.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_adapter_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_cmd_intg_gen.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_cmd_intg_chk.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_rsp_intg_gen.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_rsp_intg_chk.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_data_integ_dec.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_data_integ_enc.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_err.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_err_resp.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_fifo_sync.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_socket_1n.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_sram_byte.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/caliptra_tlul/rtl/caliptra_tlul_adapter_sram.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_sbox_canright.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_sbox_canright_masked.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_cipher_core.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_sbox.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_cipher_control_fsm_n.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_cipher_control_fsm_p.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_sbox_lut.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_mix_columns.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_sbox_dom.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_sub_bytes.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_sbox_canright_masked_noreuse.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_sel_buf_chk.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_cipher_control_fsm.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_shift_rows.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_mix_single_column.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_cipher_control.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_prng_masking.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_key_expand.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_control.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_control_fsm.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_control_fsm_n.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_control_fsm_p.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_core.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_ctr.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_ctr_fsm.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_ctr_fsm_n.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_ctr_fsm_p.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_ctrl_gcm_reg_shadowed.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_ctrl_reg_shadowed.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_ghash.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_prng_clearing.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_reduced_round.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_reg_status.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_reg_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_clp_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/aes/rtl/aes_clp_wrapper.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl/csrng_core.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl/csrng_main_sm.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl/csrng_ctr_drbg_upd.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl/csrng_ctr_drbg_cmd.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl/csrng_reg_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl/csrng_ctr_drbg_gen.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl/csrng_block_encrypt.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl/csrng_state_db.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl/csrng_cmd_stage.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/csrng/rtl/csrng.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/ot_sha3_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/kmac_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/kmac_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/sha3_param_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/sha3_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/ot_keccak_2share.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/ot_keccak_round.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/kmac_app.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/kmac_core.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/kmac_entropy.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/kmac_errchk.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/kmac_msgfifo.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/kmac_reg_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/kmac_staterd.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/kmac.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/ot_sha3pad.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/sha3_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/ot_sha3.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/sha3/rtl/sha3_ctrl.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_combiner/rtl/entropy_combiner_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_combiner/rtl/entropy_combiner_reg_pkg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_combiner/rtl/entropy_combiner_reg.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/entropy_combiner/rtl/entropy_combiner.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/integration/rtl/caliptra_top.sv
$REPO_ROOT/DSN/ip/caliptra/rtl/src/integration/rtl/boot_flow_monitor.sv





