//----------------------------------------------------------------------
// Auto-generated by uvm_protocol_signal_addon.py on 2026-08-20 11:41
// DUT module   : lpddr5c_top
// IP name      : lpddr5c_top
// Groups       : AXI(25 sig), APB(10 sig), DFI(24 sig)
// Agents       : axi_agent->AXI[ACT], apb_agent->APB[ACT], dfi_agent->DFI[ACT]
// Uses uvm_resource_db exclusively (no uvm_config_db).
// Each agent is its own unique, independent set of UVM
// classes. Active/passive mode is toggled from base_test.
// NOTE: Foundational scaffold -- extend all TODOs.
//----------------------------------------------------------------------


// Base sequence for agent "axi_agent"
/*class lpddr5c_axi_agent_base_seq extends uvm_sequence #(lpddr5c_axi_agent_seq_item);

  `uvm_object_utils(lpddr5c_axi_agent_base_seq)

  rand int unsigned num_items = 10;

  function new(string name = "lpddr5c_axi_agent_base_seq");
    super.new(name);
  endfunction

  task body();
    lpddr5c_axi_agent_seq_item item;
    repeat (num_items) begin
      item = lpddr5c_axi_agent_seq_item::type_id::create("item");
      start_item(item);
      if (!item.randomize())
        `uvm_error("RANDFAIL", "Item randomization failed")
        
         `uvm_info("AXI_SEQ",
              $sformatf("Generated AXI transaction:\n%s",
                        item.sprint()),
              UVM_MEDIUM)
              
      finish_item(item);
    end
  endtask

endclass : lpddr5c_axi_agent_base_seq

*/


class lpddr5c_axi_agent_base_seq extends uvm_sequence #(lpddr5c_axi_agent_seq_item);

  `uvm_object_utils(lpddr5c_axi_agent_base_seq)

  function new(string name = "lpddr5c_axi_agent_base_seq");
    super.new(name);
  endfunction


  task body();

    lpddr5c_axi_agent_seq_item item;

    item = lpddr5c_axi_agent_seq_item::type_id::create("req");

    start_item(item);
item.is_write = 1'b1;
    //========================================================
    // AXI WRITE ADDRESS
    //========================================================

    item.axi_awaddr  = 32'hC1B8_0C66;
    item.axi_awlen   = 8'd0;       // 1 beat
    item.axi_awsize  = 3'd4;       // 2^4 = 16 bytes = 128 bits
    item.axi_awburst = 2'b01;      // INCR

    //========================================================
    // AXI WRITE DATA
    //========================================================

    item.axi_wdata   = 128'h1122_3344_5566_7788_99AA_BBCC_DDEE_FF00;
    item.axi_wstrb   = 16'hFFFF;   // all 16 bytes valid
    item.axi_wlast   = 1'b1;

    //========================================================
    // VALID signals
    // Driver will actually drive these
    //========================================================

    item.axi_awvalid = 1'b1;
    item.axi_wvalid  = 1'b1;

    //========================================================
    // Response ready
    //========================================================

    item.axi_bready  = 1'b1;

    `uvm_info("AXI_WRITE_SEQ",
              $sformatf(
              "AXI WRITE: ADDR=0x%08h DATA=0x%032h LEN=%0d SIZE=%0d",
              item.axi_awaddr,
              item.axi_wdata,
              item.axi_awlen,
              item.axi_awsize),
              UVM_MEDIUM)

    finish_item(item);

  endtask

endclass

class lpddr5c_axi_agent_base_read_seq extends uvm_sequence #(lpddr5c_axi_agent_seq_item);

  `uvm_object_utils(lpddr5c_axi_agent_base_read_seq)

  function new(string name = "lpddr5c_axi_agent_base_read_seq");
    super.new(name);
  endfunction


  task body();

    lpddr5c_axi_agent_seq_item item;

    item = lpddr5c_axi_agent_seq_item::type_id::create("req");

    start_item(item);
item.is_write = 1'b0;

    //========================================================
    // AXI READ ADDRESS
    //========================================================

    item.axi_araddr  = 32'hC1B8_0C66;
    item.axi_arlen   = 8'd0;       // 1 beat
    item.axi_arsize  = 3'd4;       // 2^4 = 16 bytes = 128 bits
    item.axi_arburst = 2'b01;      // INCR

    //========================================================
    // READ ADDRESS VALID
    //========================================================

    item.axi_arvalid = 1'b1;

    //========================================================
    // READ DATA READY
    //========================================================

    item.axi_rready  = 1'b1;

    `uvm_info("AXI_READ_SEQ",
              $sformatf(
              "AXI READ: ADDR=0x%08h LEN=%0d SIZE=%0d BURST=%0d",
              item.axi_araddr,
              item.axi_arlen,
              item.axi_arsize,
              item.axi_arburst),
              UVM_MEDIUM)

    finish_item(item);

  endtask

endclass

