// probe_jtag_bridge.v

// Generated using ACDS version 25.1 1129

`timescale 1 ps / 1 ps
module probe_jtag_bridge (
		input  wire        clk_clk,                   //         clk.clk
		output wire [31:0] jtag_master_address,       // jtag_master.address
		input  wire [31:0] jtag_master_readdata,      //            .readdata
		output wire        jtag_master_read,          //            .read
		output wire        jtag_master_write,         //            .write
		output wire [31:0] jtag_master_writedata,     //            .writedata
		input  wire        jtag_master_waitrequest,   //            .waitrequest
		input  wire        jtag_master_readdatavalid, //            .readdatavalid
		output wire [3:0]  jtag_master_byteenable,    //            .byteenable
		input  wire        reset_reset_n              //       reset.reset_n
	);

	probe_jtag_bridge_jtagm #(
		.USE_PLI     (0),
		.PLI_PORT    (50000),
		.FIFO_DEPTHS (2)
	) jtagm (
		.clk_clk              (clk_clk),                   //          clk.clk
		.clk_reset_reset      (~reset_reset_n),            //    clk_reset.reset
		.master_address       (jtag_master_address),       //       master.address
		.master_readdata      (jtag_master_readdata),      //             .readdata
		.master_read          (jtag_master_read),          //             .read
		.master_write         (jtag_master_write),         //             .write
		.master_writedata     (jtag_master_writedata),     //             .writedata
		.master_waitrequest   (jtag_master_waitrequest),   //             .waitrequest
		.master_readdatavalid (jtag_master_readdatavalid), //             .readdatavalid
		.master_byteenable    (jtag_master_byteenable),    //             .byteenable
		.master_reset_reset   ()                           // master_reset.reset
	);

endmodule
